"""Tabiiy fan, 4-sinf: assets/data/school/science_g4.json + bank_science_g4.json.

Mavzular O‘zbekiston maktab dasturi ("Tabiiy fan", 4-sinf) yo‘nalishida: Yer va koinot, globus va xarita,
materiklar va okeanlar, ufq tomonlari, O‘zbekiston tabiati, daryolari va foydali qazilmalari, jism va moddalar,
yashash muhitlari, o‘simliklarning ko‘payishi, inson organizmi, sog‘lom ovqatlanish, xavfsizlik, tabiatni asrash.
Hamma qoida matnlari va savollar o‘zimizniki (darslikdan ko‘chirilmagan). Sonli javoblar Python’da hisoblanadi.
Qayta yaratish: python3 tool/content/school/science_g4.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from schoolkit import *  # noqa: E402,F403

T = Course("science", 4, L("Tabiiy fan", "Science", "Естествознание"))

C1 = "1-chorak. Yer, koinot va xarita"
C2 = "2-chorak. O‘zbekiston tabiati va moddalar"
C3 = "3-chorak. Tirik organizmlar va inson organizmi"
C4 = "4-chorak. Salomatlik, xavfsizlik va tabiatni asrash"

S = "So‘zlardan gap tuzing"


def near(ans, cands, k=4, lo=0):
    """Sonli javob uchun noto'g'ri variantlar: takrorsiz, javobdan farqli, `lo` dan kichik emas."""
    out = []
    for c in cands:
        if c != ans and c >= lo and c not in out:
            out.append(c)
    return out[:k]


# ============================================================ 1-chorak
T.topic("space", "🔭", L("Yer va koinot", "The Earth and space", "Земля и космос"),
        chapter=C1,
        theory="Koinot — cheksiz fazo: unda yulduzlar, sayyoralar, yo‘ldoshlar va boshqa osmon jismlari bor.\n"
               "• Quyosh — Yerga eng yaqin yulduz. U o‘zidan yorug‘lik va issiqlik chiqaradi.\n"
               "• Quyosh atrofida 8 ta sayyora aylanadi. Yer — Quyoshdan hisoblaganda 3-sayyora, unda hayot bor.\n"
               "• Oy — Yerning tabiiy yo‘ldoshi. U Yer atrofini taxminan bir oyda aylanib chiqadi va Quyosh nurini qaytarib yorug‘ ko‘rinadi.\n"
               "Yer o‘z o‘qi atrofida 24 soatda aylanadi — kecha va kunduz almashadi; Quyosh atrofini 1 yilda aylanib chiqadi.",
        items=[
            Q("Osmonda o‘zidan yorug‘lik va issiqlik chiqaradigan ulkan jism nima?", "Yulduz", ["Sayyora", "Yo‘ldosh", "Bulut"],
              x="Yulduzlar, jumladan Quyosh ham, o‘zidan yorug‘lik va issiqlik chiqaradi."),
            Q("Yerga eng yaqin yulduz qaysi?", "Quyosh", ["Oy", "Qutb yulduzi", "Mars"], e="☀️",
              x="Quyosh — yulduz, u Yerga boshqa yulduzlardan ancha yaqin."),
            Q("Quyosh atrofida nechta sayyora aylanadi?", "8 ta", ["5 ta", "3 ta", "12 ta"],
              x="Merkuriy, Venera, Yer, Mars, Yupiter, Saturn, Uran va Neptun — jami 8 ta."),
            Q("Quyoshdan hisoblaganda Yer nechanchi o‘rinda turadi?", "3-o‘rinda", ["1-o‘rinda", "2-o‘rinda", "5-o‘rinda"],
              x="Quyoshdan boshlab: Merkuriy, Venera, keyin Yer."),
            Q("Yer atrofida aylanadigan osmon jismi qaysi?", "Oy", ["Quyosh", "Mars", "Venera"], e="🌙",
              x="Oy — Yerning tabiiy yo‘ldoshi, u Yer atrofida aylanadi."),
            Q("Oy tunda nima uchun yorug‘ ko‘rinadi?", "Quyosh nurini qaytaradi", ["O‘zi nur sochadi", "Unda chiroqlar yonadi", "U alanga bilan yonadi"],
              x="Oy o‘zidan nur chiqarmaydi, uning yuzasi Quyosh nurini qaytaradi."),
            Q("Yer o‘z o‘qi atrofida bir marta necha soatda aylanadi?", "24 soatda", ["12 soatda", "7 soatda", "365 soatda"],
              x="Bir marta aylanish — bir sutka, ya’ni 24 soat."),
            Q("Yer Quyosh atrofini necha kunda aylanib chiqadi?", "365 kunda", ["30 kunda", "7 kunda", "100 kunda"],
              x="Bir yil — 365 kun, kabisa yilida esa 366 kun."),
            Q("Hayot borligi ma’lum bo‘lgan sayyora qaysi?", "Yer", ["Mars", "Venera", "Yupiter"],
              x="Hozircha hayot faqat Yerda borligi aniq ma’lum."),
            Q("Osmon jismlarini kuzatadigan asbob qaysi?", "Teleskop", ["Mikroskop", "Termometr", "Kompas"], e="🔭",
              x="Teleskop uzoqdagi osmon jismlarini yaqinlashtirib ko‘rsatadi."),
            Q("Koinotga uchadigan odam nima deb ataladi?", "Kosmonavt", ["Dengizchi", "Geolog", "Shifokor"], e="🚀",
              x="Koinotga uchuvchi odam kosmonavt yoki astronavt deb ataladi."),
            TF("Quyosh — sayyora.", False, x="Quyosh — yulduz, sayyoralar esa uning atrofida aylanadi."),
            TF("Oy — Yerning tabiiy yo‘ldoshi.", True, x="Oy Yer atrofida aylanadi, u Yerning yagona tabiiy yo‘ldoshi."),
            TF("Quyosh Yerdan ancha katta.", True, x="Quyosh juda ulkan, u bizdan uzoqda bo‘lgani uchun kichik doiradek ko‘rinadi."),
            TF("Oyda odamlar doimiy yashaydi.", False, x="Oyda nafas olish uchun havo yo‘q, u yerda hech kim doimiy yashamaydi."),
            ORDER(S, "Yer Quyosh atrofida aylanadi"),
            Q("Koinotga birinchi bo‘lib uchgan inson kim?", "Yuriy Gagarin", ["Nil Armstrong", "Mirzo Ulug‘bek", "Isaak Nyuton"], d=2,
              x="Yuriy Gagarin 1961-yil 12-aprelda koinotga uchgan."),
            Q("Samarqandda rasadxona qurib, yulduzlarni o‘rgangan buyuk olim kim?", "Mirzo Ulug‘bek", ["Alisher Navoiy", "Yuriy Gagarin", "Abdulla Qodiriy"], d=2,
              x="Mirzo Ulug‘bek XV asrda Samarqandda rasadxona qurdirgan va yulduzlar jadvalini tuzgan."),
            Q("Oyda nima yo‘q?", "Havo", ["Tog‘lar", "Chuqurliklar", "Tosh va chang"], d=2,
              x="Oyda havo yo‘q, shuning uchun u yerda nafas olib bo‘lmaydi va tovush eshitilmaydi."),
            Q("Yulduzlar kunduzi nima uchun ko‘rinmaydi?", "Quyosh nuri juda yorqin", ["Ular o‘chib qoladi", "Ular yerga tushadi", "Ular uxlab qoladi"], d=2,
              x="Yulduzlar kunduzi ham osmonda bor, lekin Quyoshning yorqin nuri ularni ko‘rsatmaydi."),
            Q("Oy Yer atrofini taxminan qancha vaqtda aylanib chiqadi?", "Bir oyda", ["Bir kunda", "Bir soatda", "Bir yilda"], d=2,
              x="Oy Yer atrofini taxminan bir oyda aylanadi, “oy” so‘zi ham shundan."),
            Q("Oyning to‘liq yorug‘ doira bo‘lib ko‘rinishi nima deyiladi?", "To‘lin oy", ["Yangi oy", "Hilol", "Oy tutilishi"], d=2,
              x="To‘lin oyda Oyning Yerga qaragan tomoni to‘liq yoritilgan bo‘ladi."),
            Q("Osmonda yulduzlar hosil qilgan shakllar nima deb ataladi?", "Yulduz turkumlari", ["Sayyoralar", "Kometalar", "Kraterlar"], d=2,
              x="Masalan, Katta Ayiq turkumining yorqin yulduzlari cho‘michga o‘xshaydi."),
            TF("Yulduzlar faqat tunda paydo bo‘lib, ertalab yo‘qoladi.", False, d=2,
               x="Yulduzlar doim osmonda, kunduzi ularni Quyosh yorug‘ligi to‘sadi."),
            MATCH("Osmon jismini ta’rifi bilan juftlang",
                  [("Quyosh", "Yerga eng yaqin yulduz"), ("Yer", "biz yashaydigan sayyora"), ("Oy", "Yerning yo‘ldoshi"),
                   ("Mars", "qizil sayyora"), ("Saturn", "halqali sayyora"), ("Somon yo‘li", "bizning galaktika")], d=2,
                  x="Quyosh — yulduz, Yer, Mars va Saturn — sayyoralar, Oy — yo‘ldosh, Somon yo‘li — galaktika."),
            Q("Oyga birinchi qadam qo‘ygan inson kim?", "Nil Armstrong", ["Yuriy Gagarin", "Mirzo Ulug‘bek", "Xristofor Kolumb"], d=3,
              x="1969-yilda Nil Armstrong Oy yuzasiga birinchi bo‘lib qadam qo‘ygan."),
            Q("Quyosh kiradigan ulkan yulduzlar to‘plami — galaktikamiz qanday ataladi?", "Somon yo‘li", ["Katta Ayiq", "Quyosh tizimi", "Kamalak"], d=3,
              x="Quyosh — Somon yo‘li galaktikasidagi milliardlab yulduzlardan biri."),
            Q("Oy nima uchun shaklini o‘zgartirgandek ko‘rinadi?", "Yoritilgan qismi turlicha ko‘rinadi", ["Oy o‘zi kichrayadi", "Oy ba’zan o‘chib qoladi", "Oyni bulut yeydi"], d=3,
              x="Oy o‘z shaklini o‘zgartirmaydi: biz uning Quyosh yoritgan qismini har kuni turlicha ko‘ramiz."),
            Q("Yerdan Quyoshgacha taxminan qancha masofa bor?", "150 million km", ["150 km", "1500 km", "150 ming km"], d=3,
              x="Quyosh juda uzoqda — taxminan 150 million kilometr."),
        ])

T.topic("globe_map", "🗺️", L("Globus va xarita", "Globe and map", "Глобус и карта"),
        chapter=C1,
        theory="Globus — Yerning kichraytirilgan hajmli modeli. U ham Yer kabi shar shaklida.\n"
               "• Ekvator — Yerni Shimoliy va Janubiy yarimsharlarga ajratuvchi xayoliy chiziq. Shimoliy va Janubiy qutblar ekvatordan eng uzoq nuqtalar.\n"
               "• Xarita — Yer yuzasining tekislikdagi kichraytirilgan tasviri. Undagi maxsus belgilar shartli belgilar deyiladi.\n"
               "• Ranglar: ko‘k — suv, yashil — pasttekislik, sariq va jigarrang — tepalik va tog‘lar, oq — muzliklar.\n"
               "Xaritada yuqori tomon — shimol, pastki — janub, o‘ng — sharq, chap — g‘arb.",
        items=[
            Q("Yerning kichraytirilgan hajmli modeli nima?", "Globus", ["Xarita", "Kompas", "Teleskop"], e="🌍",
              x="Globus Yer kabi shar shaklida, lekin undan millionlab marta kichik."),
            Q("Yer yuzasining tekis qog‘ozdagi kichraytirilgan tasviri nima?", "Xarita", ["Globus", "Fotoalbom", "Kompas"], e="🗺️",
              x="Xarita Yer yuzasini tekislikda, kichraytirib tasvirlaydi."),
            Q("Yerni Shimoliy va Janubiy yarimsharlarga nima ajratadi?", "Ekvator", ["Daryo", "Tog‘ tizmasi", "Okean"],
              x="Ekvator — globus va xaritada chiziladigan xayoliy chiziq."),
            Q("Ekvator Yerni nechta yarimsharga ajratadi?", "2 ta", ["3 ta", "4 ta", "6 ta"],
              x="Ekvatordan shimolda — Shimoliy, janubda — Janubiy yarimshar."),
            Q("Xaritada ko‘k rang nimani bildiradi?", "Suvni", ["Tog‘larni", "Cho‘lni", "O‘rmonni"],
              x="Okean, dengiz, ko‘l va daryolar ko‘k rangda tasvirlanadi."),
            Q("Xaritada yashil rang nimani bildiradi?", "Pasttekislikni", ["Dengizni", "Baland tog‘ni", "Muzlikni"],
              x="Yashil rang past, tekis joylarni ko‘rsatadi."),
            Q("Xaritada jigarrang nimani bildiradi?", "Tog‘larni", ["Daryolarni", "Ko‘llarni", "Pasttekisliklarni"],
              x="Joy qancha baland bo‘lsa, jigarrang shuncha quyuq bo‘ladi."),
            Q("Xaritaning yuqori tomoni qaysi ufq tomoni?", "Shimol", ["Janub", "Sharq", "G‘arb"],
              x="Odatda xaritaning yuqorisi — shimol, pasti — janub."),
            Q("Xaritadagi narsalarni ko‘rsatuvchi maxsus belgilar nima deyiladi?", "Shartli belgilar", ["Harflar", "Yo‘l belgilari", "Notalar"],
              x="Shahar, daryo, tog‘ kabi joylar shartli belgilar bilan ko‘rsatiladi."),
            TF("Ekvator — Yer yuzasida chizilgan haqiqiy chiziq.", False, x="Ekvator xayoliy chiziq, u faqat globus va xaritada chiziladi."),
            TF("Globus ham Yer kabi shar shaklida.", True, x="Globus — Yerning kichik modeli, shuning uchun u ham shar shaklida."),
            TF("Xaritada daryo va ko‘llar ko‘k rangda tasvirlanadi.", True, x="Ko‘k rang — suvning rangi."),
            ORDER(S, "Globus Yerning kichik modeli"),
            Q("Xaritaning o‘ng tomoni qaysi ufq tomoni?", "Sharq", ["G‘arb", "Shimol", "Janub"], d=2,
              x="Xaritada o‘ng — sharq, chap — g‘arb."),
            Q("Globusda oq rang bilan ko‘pincha nima ko‘rsatiladi?", "Muzliklar", ["Cho‘llar", "O‘rmonlar", "Shaharlar"], d=2,
              x="Antarktida va Grenlandiyadagi muzliklar oq rangda ko‘rsatiladi."),
            Q("Ekvatordan eng uzoqda joylashgan nuqtalar qaysilar?", "Qutblar", ["Tog‘ cho‘qqilari", "Okeanlar markazi", "Poytaxtlar"], d=2,
              x="Shimoliy va Janubiy qutblar ekvatordan eng uzoqda."),
            Q("O‘zbekiston qaysi yarimsharda joylashgan?", "Shimoliy yarimsharda", ["Janubiy yarimsharda", "Ekvator ustida", "Janubiy qutbda"], d=2,
              x="O‘zbekiston ekvatordan shimolda joylashgan."),
            Q("Globusning afzalligi nima?", "Yer shaklini to‘g‘ri ko‘rsatadi", ["Cho‘ntakka sig‘adi", "Ko‘chalarni ko‘rsatadi", "Mayda joylarni batafsil ko‘rsatadi"], d=2,
              x="Globus Yer kabi shar shaklida, lekin undagi tasvir juda kichik."),
            TF("Shimoliy qutb ekvatorda joylashgan.", False, d=2, x="Qutblar ekvatordan eng uzoqdagi nuqtalar."),
            TF("Ekvator yaqinida yil bo‘yi issiq bo‘ladi.", True, d=2,
               x="Ekvator yaqinida Quyosh nurlari deyarli tik tushadi, shuning uchun u yerda issiq."),
            MATCH("Xaritadagi belgini ma’nosi bilan juftlang",
                  [("Ko‘k rang", "dengiz va ko‘llar"), ("Yashil rang", "pasttekislik"), ("Jigarrang", "tog‘lar"),
                   ("Oq rang", "muzliklar"), ("Ko‘k ingichka chiziq", "daryo")], d=2,
                  x="Xaritani o‘qish uchun ranglar va shartli belgilarni bilish kerak."),
            Q("Xaritaning globusdan afzalligi nima?", "Batafsil va olib yurish qulay", ["Yer shaklini aniq ko‘rsatadi", "U shar shaklida", "Unda ranglar bo‘lmaydi"], d=3,
              x="Xaritani buklab olib yurish mumkin, unda kichik hudud ham batafsil ko‘rsatiladi."),
            Q("Maktab hovlisining yuqoridan qaraganda chizilgan batafsil tasviri nima deyiladi?", "Joy plani", ["Globus", "Dunyo xaritasi", "Kompas"], d=3,
              x="Plan kichik joyni batafsil ko‘rsatadi, xarita esa katta hududni."),
            Q("Shimoliy qutbdan qaysi tomonga yurmang, qaysi tomonga borasiz?", "Janubga", ["Shimolga", "Sharqqa", "G‘arbga"], d=3,
              x="Shimoliy qutbda barcha yo‘nalishlar janubga qaraydi."),
        ])

T.topic("continents", "🌏", L("Materiklar va okeanlar", "Continents and oceans", "Материки и океаны"),
        chapter=C1,
        theory="Yer yuzasining katta qismini okean va dengizlar egallaydi, qolgan qismi — quruqlik.\n"
               "• 6 ta materik bor: Yevrosiyo, Afrika, Shimoliy Amerika, Janubiy Amerika, Antarktida, Avstraliya.\n"
               "• Eng katta materik — Yevrosiyo (O‘zbekiston shu materikda), eng kichigi — Avstraliya, eng sovug‘i — Antarktida, eng issig‘i — Afrika.\n"
               "• 5 ta okean bor: Tinch, Atlantika, Hind, Shimoliy Muz va Janubiy okean. Eng katta va eng chuquri — Tinch okeani, eng kichigi — Shimoliy Muz okeani.\n"
               "Materik — okean suvlari bilan o‘ralgan ulkan quruqlik, orol — suv bilan o‘ralgan kichikroq quruqlik.",
        items=[
            Q("Yer yuzida nechta materik bor?", "6 ta", ["3 ta", "4 ta", "10 ta"],
              x="Yevrosiyo, Afrika, Shimoliy Amerika, Janubiy Amerika, Antarktida va Avstraliya."),
            Q("Eng katta materik qaysi?", "Yevrosiyo", ["Afrika", "Avstraliya", "Antarktida"],
              x="Yevrosiyo — eng katta materik, unda Yevropa va Osiyo joylashgan."),
            Q("Eng kichik materik qaysi?", "Avstraliya", ["Yevrosiyo", "Afrika", "Shimoliy Amerika"],
              x="Avstraliya — materiklarning eng kichigi."),
            Q("O‘zbekiston qaysi materikda joylashgan?", "Yevrosiyoda", ["Afrikada", "Avstraliyada", "Janubiy Amerikada"],
              x="O‘zbekiston Yevrosiyo materigining Osiyo qismida joylashgan."),
            Q("Eng sovuq materik qaysi?", "Antarktida", ["Afrika", "Avstraliya", "Janubiy Amerika"], e="❄️",
              x="Antarktidani qalin muz qatlami qoplagan."),
            Q("Eng issiq materik qaysi?", "Afrika", ["Antarktida", "Yevrosiyo", "Shimoliy Amerika"],
              x="Afrikaning katta qismi ekvator atrofidagi issiq mintaqada joylashgan."),
            Q("Yer yuzida nechta okean bor?", "5 ta", ["2 ta", "8 ta", "10 ta"],
              x="Tinch, Atlantika, Hind, Shimoliy Muz va Janubiy okean."),
            Q("Maydoni eng katta va eng chuqur okean qaysi?", "Tinch okeani", ["Atlantika okeani", "Hind okeani", "Shimoliy Muz okeani"],
              x="Tinch okeani barcha materiklardan ham katta maydonni egallaydi."),
            Q("Materik nima?", "Suv bilan o‘ralgan ulkan quruqlik", ["Kichik orol", "Katta ko‘l", "Baland tog‘"],
              x="Materik — okeanlar bilan o‘ralgan juda katta quruqlik."),
            Q("Suv bilan o‘ralgan kichikroq quruqlik nima deyiladi?", "Orol", ["Materik", "Okean", "Daryo"],
              x="Orol har tomondan suv bilan o‘ralgan, lekin materikdan ancha kichik."),
            TF("Afrika — eng kichik materik.", False, x="Eng kichik materik — Avstraliya."),
            TF("Yer yuzasida quruqlik suvdan ko‘p.", False, x="Yer yuzasining taxminan 71 foizini suv egallaydi."),
            TF("Tinch okeani — okeanlarning eng kattasi.", True, x="Tinch okeani maydoni bo‘yicha birinchi o‘rinda."),
            ORDER(S, "Yevrosiyo eng katta materik"),
            Q("Eng kichik okean qaysi?", "Shimoliy Muz okeani", ["Tinch okeani", "Atlantika okeani", "Hind okeani"], d=2,
              x="Shimoliy Muz okeani — eng kichik va eng sovuq okean."),
            Q("Yevrosiyo qaysi ikki dunyo qismidan iborat?", "Yevropa va Osiyo", ["Afrika va Osiyo", "Amerika va Yevropa", "Avstraliya va Osiyo"], d=2,
              x="Yevrosiyo nomi ikki so‘zdan tuzilgan: Yevropa + Osiyo."),
            Q("Qaysi materik davlat nomi bilan bir xil ataladi?", "Avstraliya", ["Afrika", "Antarktida", "Yevrosiyo"], d=2,
              x="Avstraliya davlati butun bir materikni egallaydi."),
            Q("Qaysi materikda doimiy aholi yo‘q?", "Antarktida", ["Avstraliya", "Afrika", "Janubiy Amerika"], d=2,
              x="Antarktidada faqat ilmiy stansiyalarda vaqtincha ishlaydigan olimlar bo‘ladi."),
            Q("Yevropa va Amerika orasida qaysi okean joylashgan?", "Atlantika okeani", ["Hind okeani", "Tinch okeani", "Janubiy okean"], d=2,
              x="Atlantika okeani g‘arbda Amerikani, sharqda Yevropa va Afrikani yuvadi."),
            Q("Antarktidani o‘rab turgan okean qaysi?", "Janubiy okean", ["Shimoliy Muz okeani", "Hind okeani", "Atlantika okeani"], d=2,
              x="Janubiy okean Antarktida atrofidagi sovuq suvlardan iborat."),
            TF("Yevrosiyo ikki dunyo qismidan iborat.", True, d=2, x="Yevrosiyoda Yevropa va Osiyo dunyo qismlari joylashgan."),
            MATCH("Materikni ta’rifi bilan juftlang",
                  [("Yevrosiyo", "eng katta materik"), ("Avstraliya", "eng kichik materik"), ("Antarktida", "eng sovuq materik"),
                   ("Afrika", "eng issiq materik"), ("Janubiy Amerika", "Amazonka daryosi oqadi")], d=2,
                  x="Har bir materikning o‘ziga xos belgisi bor."),
            Q("Dunyodagi eng baland cho‘qqi — Jomolungma qaysi materikda?", "Yevrosiyoda", ["Afrikada", "Avstraliyada", "Antarktidada"], d=3,
              x="Jomolungma (Everest) Osiyodagi Himolay tog‘larida joylashgan."),
            Q("Afrikadagi ulkan issiq cho‘l qaysi?", "Sahroi Kabir", ["Qizilqum", "Qoraqum", "Gobi"], d=3,
              x="Sahroi Kabir Afrikaning shimolida joylashgan, Qizilqum esa O‘zbekistonda."),
            MATCH("Okeanni ta’rifi bilan juftlang",
                  [("Tinch okeani", "eng katta va chuqur"), ("Shimoliy Muz okeani", "eng kichik"), ("Janubiy okean", "Antarktidani o‘rab turadi"),
                   ("Atlantika okeani", "Yevropa va Amerika orasida"), ("Hind okeani", "Afrika va Avstraliya orasida")], d=3,
                  x="Okeanlarning joylashuvini globusda kuzatib chiqing."),
        ])

# --- Ufq tomonlari: burilish savollari Python'da hisoblanadi.
_dirs = ["shimol", "sharq", "janub", "g‘arb"]  # soat mili bo'yicha
_dat = {"shimol": "shimolga", "sharq": "sharqqa", "janub": "janubga", "g‘arb": "g‘arbga"}
_turns = {"o‘ngga burilsangiz": 1, "chapga burilsangiz": -1, "orqaga o‘girilsangiz": 2, "ikki marta o‘ngga burilsangiz": 2}
_dirq = []
for start, turn, d in [("shimol", "o‘ngga burilsangiz", 2), ("sharq", "o‘ngga burilsangiz", 2), ("shimol", "chapga burilsangiz", 2),
                       ("janub", "chapga burilsangiz", 3), ("g‘arb", "orqaga o‘girilsangiz", 2), ("sharq", "ikki marta o‘ngga burilsangiz", 3)]:
    end = _dirs[(_dirs.index(start) + _turns[turn]) % 4]
    ans = _dat[end][0].upper() + _dat[end][1:]
    wrong = [_dat[v][0].upper() + _dat[v][1:] for v in _dirs if v != end]
    _dirq.append(Q(f"Siz {_dat[start]} qarab turibsiz. {turn[0].upper() + turn[1:]}, qaysi tomonga qaraysiz?", ans, wrong, d=d,
                   x="Soat mili bo‘yicha tartib: shimol → sharq → janub → g‘arb. O‘ngga burilish — keyingi tomon, chapga — oldingi tomon, "
                     f"orqaga — qarama-qarshi tomon. Javob: {_dat[end]}."))
assert _dirs[(_dirs.index("shimol") + 1) % 4] == "sharq" and _dirs[(_dirs.index("janub") - 1) % 4] == "sharq"

T.topic("directions", "🧭", L("Ufq tomonlari va kompas", "Cardinal directions and the compass", "Стороны горизонта и компас"),
        chapter=C1,
        theory="Ufq — osmon yer bilan tutashgandek ko‘rinadigan chiziq. Asosiy ufq tomonlari: shimol, janub, sharq, g‘arb.\n"
               "Oraliq tomonlar: shimoli-sharq, shimoli-g‘arb, janubi-sharq, janubi-g‘arb.\n"
               "• Kompasning magnitlangan mili doim shimol–janub yo‘nalishida turadi. Kompasni tekis tuting va temir buyumlardan uzoqlashtiring.\n"
               "• Quyosh bo‘yicha: ertalab Quyosh sharq tomonda, tushda (bizda) janubda, kechqurun g‘arbda bo‘ladi. Tunda shimolni Qutb yulduzi ko‘rsatadi.\n"
               "Shimolga qarab tursangiz: orqangizda — janub, o‘ngda — sharq, chapda — g‘arb.",
        items=[
            Q("Nechta asosiy ufq tomoni bor?", "4 ta", ["2 ta", "3 ta", "10 ta"],
              x="Asosiy tomonlar: shimol, janub, sharq, g‘arb."),
            Q("Ufq tomonlarini aniqlaydigan asbob qaysi?", "Kompas", ["Termometr", "Tarozi", "Soat"],
              x="Kompas mili magnitlangan, u shimolni ko‘rsatadi."),
            Q("Kompasning magnitlangan mili qaysi yo‘nalishda turadi?", "Shimol–janub", ["Sharq–g‘arb", "Yuqori–past", "Har safar boshqacha"],
              x="Mil bir uchi bilan shimolga, ikkinchi uchi bilan janubga qaraydi."),
            Q("Ufq nima?", "Osmon yer bilan tutashgandek chiziq", ["Tog‘ning eng baland nuqtasi", "Daryoning qirg‘og‘i", "Yo‘lning chekkasi"],
              x="Ufq chizig‘iga qancha yursak ham, u uzoqlashib boraveradi."),
            Q("Shimol va sharq orasidagi tomon qanday ataladi?", "Shimoli-sharq", ["Janubi-g‘arb", "Shimoli-g‘arb", "Janubi-sharq"],
              x="Oraliq tomon nomi ikki asosiy tomon nomidan tuziladi."),
            Q("Shimolning qarama-qarshi tomoni qaysi?", "Janub", ["Sharq", "G‘arb", "Shimoli-sharq"],
              x="Shimol va janub — qarama-qarshi tomonlar."),
            Q("Sharqning qarama-qarshi tomoni qaysi?", "G‘arb", ["Janub", "Shimol", "Janubi-sharq"],
              x="Quyosh sharqdan chiqib, qarama-qarshi tomonga — g‘arbga botadi."),
            Q("Ertalab Quyosh osmonning qaysi tomonida bo‘ladi?", "Sharqda", ["G‘arbda", "Shimolda", "Janubda"],
              x="Quyosh ertalab sharq tomondan chiqadi."),
            Q("Tunda shimolni qaysi yulduz bo‘yicha topish mumkin?", "Qutb yulduzi", ["Quyosh", "Oy", "Mars"],
              x="Qutb yulduzi doim osmonning shimol tomonida ko‘rinadi."),
            TF("Kompas mili magnitlangan.", True, x="Magnitlangan mil Yerning magnit maydoni ta’sirida shimol–janub bo‘ylab turadi."),
            TF("Quyosh kechqurun sharqqa botadi.", False, x="Quyosh kechqurun g‘arbga botadi."),
            TF("Shimoli-g‘arb — shimol va g‘arb orasidagi tomon.", True, x="Oraliq tomon ikki asosiy tomon orasida bo‘ladi."),
            ORDER(S, "Kompas ufq tomonlarini aniqlaydi"),
            Q("Janub va g‘arb orasidagi tomon qanday ataladi?", "Janubi-g‘arb", ["Shimoli-sharq", "Janubi-sharq", "Shimoli-g‘arb"], d=2,
              x="Janub + g‘arb = janubi-g‘arb."),
            Q("Tushda soyangiz qaysi tomonga tushadi?", "Shimolga", ["Janubga", "Sharqqa", "G‘arbga"], d=2,
              x="Bizda tushda Quyosh janubda turadi, soya esa unga qarama-qarshi — shimolga tushadi."),
            Q("Kompas bilan ishlaganda nimaga e’tibor berish kerak?", "Temir buyumlardan uzoq tutish", ["Uni silkitib turish", "Magnit yoniga qo‘yish", "Suvga botirish"], d=2,
              x="Temir va magnit kompas milini og‘dirib, noto‘g‘ri ko‘rsatishiga sabab bo‘ladi."),
            TF("Kompasni magnit yoniga qo‘ysak, u noto‘g‘ri ko‘rsatishi mumkin.", True, d=2,
               x="Magnit kompas milini o‘ziga tortib, yo‘nalishni buzadi."),
            MATCH("Siz shimolga qarab turibsiz. Juftlang",
                  [("Oldingizda", "shimol"), ("Orqangizda", "janub"), ("O‘ng qo‘lingiz tomonda", "sharq"), ("Chap qo‘lingiz tomonda", "g‘arb"),
                   ("Oldinga va o‘ngga orasida", "shimoli-sharq"), ("Orqaga va chapga orasida", "janubi-g‘arb")], d=2,
                  x="Shimolga qaraganda o‘ngda sharq, chapda g‘arb, orqada janub bo‘ladi."),
            Q("Kechqurun soyangiz qaysi tomonga tushadi?", "Sharqqa", ["G‘arbga", "Janubga", "Shimolga"], d=3,
              x="Kechqurun Quyosh g‘arbda bo‘ladi, soya esa unga qarama-qarshi — sharqqa tushadi."),
            Q("Qutb yulduzi qaysi yulduz turkumida joylashgan?", "Kichik Ayiq", ["Katta Ayiq", "Orion", "Qo‘y"], d=3,
              x="Qutb yulduzi Kichik Ayiq turkumining eng yorqin yulduzi."),
            Q("Kompas birinchi bo‘lib qaysi mamlakatda ixtiro qilingan?", "Xitoyda", ["Avstraliyada", "Braziliyada", "Kanadada"], d=3,
              x="Magnit mil bilan yo‘nalish topishni qadimgi Xitoyda o‘ylab topishgan."),
        ] + _dirq)

T.test("test1", L("1-nazorat ishi", "Test 1", "Контрольная работа 1"),
       ["space", "globe_map", "continents", "directions"], chapter=C1)

# ============================================================ 2-chorak
T.topic("zones", "🏜️", L("O‘zbekiston tabiat zonalari", "Natural zones of Uzbekistan", "Природные зоны Узбекистана"),
        chapter=C2,
        theory="O‘zbekistonning katta qismini tekislik va cho‘llar, sharq va janubi-sharqini tog‘lar egallaydi. Iqlimi keskin kontinental: yozi issiq va quruq, qishi sovuq.\n"
               "• Cho‘l: yog‘in juda kam, yozda jazirama. O‘simliklari — saksovul, yantoq, qandim; hayvonlari — jayron, echkemar, toshbaqa. Eng katta cho‘l — Qizilqum.\n"
               "• Adir (dasht): tog‘ etagidagi tepaliklar; bahorda lola va qizg‘aldoqqa burkanadi, yozda o‘tlar quriydi.\n"
               "• Tog‘: salqin, yog‘in ko‘proq; archa, yong‘oq, pista o‘sadi; qor qoploni, tog‘ echkisi, ayiq yashaydi. Eng baland nuqta — Hazrati Sulton cho‘qqisi.\n"
               "• Vodiy: tog‘lar orasidagi tekislik, tuprog‘i unumdor, suvi ko‘p — bog‘ va dalalar ko‘p. Eng kattasi — Farg‘ona vodiysi.",
        items=[
            Q("Qaysi tabiat zonasida yog‘in eng kam?", "Cho‘lda", ["Tog‘da", "Vodiyda", "Adirda"],
              x="Cho‘lda yil bo‘yi juda kam yomg‘ir yog‘adi, yozda jazirama issiq bo‘ladi."),
            Q("Qaysi o‘simlik cho‘lda o‘sadi?", "Yantoq", ["Archa", "Sholi", "Nilufar"],
              x="Yantoqning uzun ildizi yer ostidagi suvgacha yetib boradi."),
            Q("Saksovul qaysi zonada o‘sadi?", "Cho‘lda", ["Baland tog‘da", "Ko‘l tubida", "Muzlikda"],
              x="Saksovul qumli cho‘llarda o‘sadi va qumni ushlab turadi."),
            Q("Qaysi hayvon cho‘lda yashaydi?", "Echkemar", ["Qor qoploni", "Tog‘ echkisi", "Qo‘ng‘ir ayiq"],
              x="Echkemar — cho‘l issig‘iga moslashgan yirik kaltakesak."),
            Q("Archa o‘rmonlari qaysi zonada uchraydi?", "Tog‘larda", ["Cho‘lda", "Qumliklarda", "Sho‘rxoklarda"],
              x="Archa tog‘ yonbag‘irlarida o‘sadi."),
            Q("Bahorda lola va qizg‘aldoqqa burkanadigan tepaliklar nima deb ataladi?", "Adirlar", ["Cho‘llar", "Muzliklar", "Vohalar"],
              x="Adirlar tog‘ etagida joylashgan, bahorda ular gilamdek gullaydi."),
            Q("Tog‘lar orasidagi keng tekislik nima deb ataladi?", "Vodiy", ["Cho‘l", "Adir", "Cho‘qqi"],
              x="Masalan, Farg‘ona vodiysi tog‘lar orasida joylashgan."),
            Q("Qaysi hayvon tog‘larda yashaydi?", "Tog‘ echkisi", ["Jayron", "Echkemar", "Qumsichqon"],
              x="Tog‘ echkisi tik qoyalarda chaqqon yuradi."),
            TF("Cho‘lda yozda juda issiq, yog‘in kam bo‘ladi.", True, x="Cho‘lning asosiy belgisi — issiq va quruqlik."),
            TF("Farg‘ona vodiysi — cho‘l.", False, x="Farg‘ona — tog‘lar orasidagi unumdor vodiy."),
            TF("Adirlar bahorda gullarga burkanadi.", True, x="Bahorda adirlar lola va qizg‘aldoqqa to‘ladi."),
            TF("Tog‘larda archa o‘rmonlari o‘sadi.", True, x="Archa tog‘larning salqin yonbag‘irlarida o‘sadi."),
            ORDER(S, "Vodiylarda tuproq unumdor bo‘ladi"),
            Q("Amudaryo va Sirdaryo oralig‘idagi ulkan cho‘l qaysi?", "Qizilqum", ["Qoraqum", "Sahroi Kabir", "Gobi"], d=2,
              x="Qizilqum — O‘zbekistondagi eng katta cho‘l, u ikki daryo oralig‘ida."),
            Q("O‘zbekistondagi eng katta vodiy qaysi?", "Farg‘ona vodiysi", ["Zarafshon vodiysi", "Surxondaryo vodiysi", "Chirchiq vodiysi"], d=2,
              x="Farg‘ona vodiysi uch tomondan tog‘lar bilan o‘ralgan."),
            Q("Nima uchun vodiylarda bog‘ va dalalar ko‘p?", "Tuproq unumdor, suv ko‘p", ["Yog‘in umuman yo‘q", "Yil bo‘yi qor yotadi", "Tuproq qumli"], d=2,
              x="Tog‘dan tushgan daryolar vodiyni sug‘oradi, tuproq esa unumdor."),
            Q("O‘zbekistonning eng baland nuqtasi qaysi?", "Hazrati Sulton cho‘qqisi", ["Jomolungma", "Katta Chimyon", "Elbrus"], d=2,
              x="Hazrati Sulton cho‘qqisi Surxondaryo viloyatidagi Hisor tizmasida joylashgan."),
            Q("O‘zbekiston iqlimi qanday?", "Keskin kontinental", ["Tropik va nam", "Qutbiy va sovuq", "Yil bo‘yi bir xil iliq"], d=2,
              x="Yozi issiq va quruq, qishi sovuq — bu keskin kontinental iqlim."),
            Q("Tog‘da yuqoriga ko‘tarilgan sari havo qanday bo‘ladi?", "Sovuqroq", ["Issiqroq", "O‘zgarmaydi", "Quruqroq va issiqroq"], d=2,
              x="Balandlik oshgan sari havo soviydi, shuning uchun cho‘qqilarda yozda ham qor bo‘ladi."),
            Q("Adirlarda yozda o‘tlar nima uchun sarg‘ayib quriydi?", "Issiq va yog‘in kam", ["Qor ko‘p yog‘adi", "Suv toshqini bo‘ladi", "Qattiq sovuq bo‘ladi"], d=2,
              x="Yozda adirlarda yomg‘ir deyarli yog‘maydi, issiq esa kuchli."),
            TF("Jayron baland tog‘ cho‘qqilarida yashaydi.", False, d=2, x="Jayron cho‘l va dashtlarda yashaydi."),
            MATCH("Tabiat zonasini belgisi bilan juftlang",
                  [("Cho‘l", "saksovul va yantoq"), ("Adir", "bahorda lolazor"), ("Tog‘", "archa va qor qoploni"),
                   ("Vodiy", "unumdor tuproq, bog‘lar"), ("To‘qay", "daryo bo‘yidagi chakalakzor")], d=2,
                  x="Har bir tabiat zonasining o‘z o‘simlik va hayvonlari bor."),
            Q("Adirlarda qaysi dehqonchilik turi keng tarqalgan?", "Lalmikor dehqonchilik", ["Sholikorlik", "Baliqchilik", "Choy yetishtirish"], d=3,
              x="Lalmikor yerlarda bug‘doy sug‘orilmaydi, u yomg‘ir suvi hisobiga o‘sadi."),
            Q("Daryo bo‘yidagi to‘qaylarda qaysi kamyob hayvon yashaydi?", "Buxoro bug‘usi", ["Qor qoploni", "Tog‘ echkisi", "Echkemar"], d=3,
              x="Buxoro bug‘usi Amudaryo bo‘yidagi to‘qay o‘rmonlarida yashaydi."),
            Q("Cho‘lda suv manbai atrofidagi yashil, obod joy nima deyiladi?", "Voha", ["Adir", "Cho‘qqi", "Muzlik"], d=3,
              x="Masalan, Buxoro va Xorazm vohalari daryo suvi bilan obod bo‘lgan."),
        ])

T.topic("rivers", "🏞️", L("O‘zbekiston daryolari va ko‘llari", "Rivers and lakes of Uzbekistan", "Реки и озёра Узбекистана"),
        chapter=C2,
        theory="Daryolar tog‘lardagi qor va muzliklarning erishidan, buloq va yomg‘ir suvlaridan to‘yinadi.\n"
               "• Daryo boshlanadigan joy — manba, quyiladigan joy — mansab. Unga qo‘shiladigan kichik daryolar — irmoqlar, suv oqadigan chuqurlik — o‘zan.\n"
               "• Eng katta daryolar — Amudaryo va Sirdaryo, ular Orol dengiziga quyilgan. Amudaryo — O‘rta Osiyodagi eng sersuv daryo.\n"
               "• Sirdaryo Farg‘ona vodiysida Norin va Qoradaryoning qo‘shilishidan hosil bo‘ladi. Boshqa daryolar: Zarafshon, Chirchiq, Qashqadaryo, Surxondaryo.\n"
               "Ko‘l va suv omborlari: Orol, Aydarko‘l, Chorvoq. Daryo suvi ekinlarni sug‘orishga va elektr olishga ishlatiladi.",
        items=[
            Q("Amudaryo va Sirdaryo qayerga quyilgan?", "Orol dengiziga", ["Kaspiy dengiziga", "Qora dengizga", "Hind okeaniga"],
              x="Ikkala daryo ham Orol dengiziga quyilgan."),
            Q("Daryo boshlanadigan joy qanday ataladi?", "Manba", ["Mansab", "Irmoq", "O‘zan"],
              x="Manba — daryoning boshlanishi, ko‘pincha tog‘dagi buloq yoki muzlik."),
            Q("Katta daryoga qo‘shiladigan kichik daryo nima deyiladi?", "Irmoq", ["Manba", "Mansab", "Kanal"],
              x="Irmoqlar katta daryoga qo‘shilib, uni sersuv qiladi."),
            Q("Tog‘ daryolari asosan nimadan to‘yinadi?", "Qor va muzlik suvlaridan", ["Dengiz suvidan", "Quduq suvidan", "Kanal suvidan"],
              x="Tog‘dagi qor va muzliklar erib, daryolarga suv beradi."),
            Q("Daryo suvidan qanday foydalaniladi?", "Ekinlarni sug‘orishda", ["Tosh eritishda", "Temir yasashda", "Qum ishlab chiqarishda"],
              x="Daryo suvi kanal va ariqlar orqali dalalarga boradi."),
            Q("Odamlar qazib chiqargan sun’iy suv yo‘li nima deyiladi?", "Kanal", ["Daryo", "Irmoq", "Buloq"],
              x="Kanal daryo suvini uzoqdagi dalalarga olib boradi."),
            Q("Yer ostidan o‘z-o‘zidan chiqib turadigan suv nima?", "Buloq", ["Kanal", "Suv ombori", "Dengiz"],
              x="Buloq suvi yer ostidan tabiiy ravishda chiqadi."),
            Q("Suv ombori nima uchun quriladi?", "Suvni to‘plab saqlash uchun", ["Daryoni quritish uchun", "Qum to‘plash uchun", "Baliqlarni haydash uchun"],
              x="Suv omborida to‘plangan suv yozda dalalarni sug‘orishga ishlatiladi."),
            TF("Irmoq — daryoning boshlanish joyi.", False, x="Boshlanish joyi — manba, irmoq esa daryoga qo‘shiladigan kichik daryo."),
            TF("Suv baland joydan past joyga qarab oqadi.", True, x="Shuning uchun daryolar tog‘dan tekislikka qarab oqadi."),
            TF("Ariq va daryolarga chiqindi tashlash mumkin.", False, x="Chiqindi suvni ifloslaydi, bu suvni odam va hayvonlar ichadi."),
            ORDER(S, "Daryolar tog‘lardan boshlanadi"),
            Q("Daryoning boshqa daryo, ko‘l yoki dengizga quyiladigan joyi?", "Mansab", ["Manba", "Irmoq", "Buloq"], d=2,
              x="Mansab — daryoning oxiri, u quyiladigan joy."),
            Q("Daryo suvi oqadigan chuqurlik nima deyiladi?", "O‘zan", ["Manba", "Qirg‘oq", "Irmoq"], d=2,
              x="O‘zan — daryo suvi oqadigan joy, qirg‘oq esa uning cheti."),
            Q("O‘rta Osiyodagi eng sersuv daryo qaysi?", "Amudaryo", ["Chirchiq", "Zarafshon", "Qashqadaryo"], d=2,
              x="Amudaryoda suv eng ko‘p oqadi."),
            Q("Chorvoq suv ombori qaysi viloyatda?", "Toshkent viloyatida", ["Xorazm viloyatida", "Buxoro viloyatida", "Navoiy viloyatida"], d=2,
              x="Chorvoq suv ombori Toshkent viloyatining tog‘li qismida joylashgan."),
            Q("Qaysi daryo Samarqand va Buxoro yerlarini sug‘oradi?", "Zarafshon", ["Chirchiq", "Norin", "Surxondaryo"], d=2,
              x="Zarafshon — Samarqand va Buxoro vohalarining asosiy suv manbai."),
            MATCH("Daryoni o‘ziga mos ma’lumot bilan juftlang",
                  [("Amudaryo", "O‘rta Osiyoning eng sersuv daryosi"), ("Sirdaryo", "Norin va Qoradaryodan hosil bo‘ladi"),
                   ("Zarafshon", "Samarqand va Buxoroni sug‘oradi"), ("Chirchiq", "Chorvoq suv omboridan boshlanadi"),
                   ("Surxondaryo", "Amudaryoga quyiladi")], d=2,
                  x="Har bir daryoning o‘z yo‘li va ahamiyati bor."),
            Q("Sirdaryo qaysi ikki daryoning qo‘shilishidan hosil bo‘ladi?", "Norin va Qoradaryo", ["Panj va Vaxsh", "Chotqol va Pskom", "Chirchiq va Ohangaron"], d=3,
              x="Norin va Qoradaryo Farg‘ona vodiysida qo‘shilib, Sirdaryoni hosil qiladi."),
            Q("Amudaryo qaysi ikki daryoning qo‘shilishidan hosil bo‘ladi?", "Panj va Vaxsh", ["Norin va Qoradaryo", "Chotqol va Pskom", "Zarafshon va Surxondaryo"], d=3,
              x="Tog‘lardan tushgan Panj va Vaxsh daryolari qo‘shilib, Amudaryoni hosil qiladi."),
            Q("Tog‘ daryolari qaysi paytda eng sersuv bo‘ladi?", "Bahor oxiri va yozda", ["Qish o‘rtasida", "Kech kuzda", "Yanvarda"], d=3,
              x="Bahor oxiri va yozda tog‘dagi qor va muzliklar tez eriydi."),
            Q("Farg‘ona vodiysidagi xalq hashari bilan qurilgan mashhur kanal qaysi?", "Katta Farg‘ona kanali", ["Suvaysh kanali", "Panama kanali", "Qarshi kanali"], d=3,
              x="Katta Farg‘ona kanali 1939-yilda qurilgan."),
            Q("Orol dengizi aslida nima?", "Katta sho‘r ko‘l", ["Okeanning bir qismi", "Tog‘ daryosi", "Sun’iy kanal"], d=3,
              x="Orol hech qaysi okeanga tutashmaydi, shuning uchun u ko‘l hisoblanadi."),
            TF("Chirchiq — Sirdaryoning irmog‘i.", True, d=3, x="Chirchiq daryosi Sirdaryoga quyiladi."),
        ])

T.topic("minerals", "⛏️", L("Foydali qazilmalar", "Mineral resources", "Полезные ископаемые"),
        chapter=C2,
        theory="Foydali qazilmalar — yer bag‘ridan qazib olinadigan va inson foydalanadigan tabiiy boyliklar. Ular to‘plangan joy — kon.\n"
               "• Yonuvchi qazilmalar: neft, tabiiy gaz, ko‘mir — yoqilg‘i va energiya manbai.\n"
               "• Metall rudalari: oltin, mis, temir, kumush. Misdan elektr simlari, oltindan zargarlik buyumlari yasaladi.\n"
               "• Qurilish va boshqa qazilmalar: qum, shag‘al, marmar, ohaktosh, osh tuzi.\n"
               "O‘zbekistonda: oltin — Muruntov (Qizilqum), mis — Olmaliq, ko‘mir — Angren, gaz — Buxoro va Qashqadaryo viloyatlari. Qazilmalar tiklanmaydi, ularni tejash kerak.",
        items=[
            Q("Yer bag‘ridan qazib olinadigan tabiiy boyliklar nima deyiladi?", "Foydali qazilmalar", ["O‘simliklar", "Tuproqlar", "Buloqlar"],
              x="Neft, gaz, ko‘mir, oltin, mis — foydali qazilmalar."),
            Q("Foydali qazilma to‘plangan joy nima deyiladi?", "Kon", ["Zavod", "Bozor", "Ombor"],
              x="Masalan, Muruntov — oltin koni."),
            Q("Qaysi biri yonuvchi foydali qazilma?", "Ko‘mir", ["Marmar", "Qum", "Mis"],
              x="Ko‘mir yonadi va issiqlik beradi."),
            Q("Qaysi biri metall?", "Mis", ["Neft", "Qum", "Ko‘mir"],
              x="Mis — qizg‘ish rangli metall."),
            Q("Elektr simlari ko‘pincha qaysi metalldan yasaladi?", "Misdan", ["Oltindan", "Ko‘mirdan", "Tuzdan"],
              x="Mis elektr tokini yaxshi o‘tkazadi."),
            Q("Uylarda ovqat pishirish va isitish uchun qaysi qazilma yoqiladi?", "Tabiiy gaz", ["Marmar", "Mis", "Qum"],
              x="Tabiiy gaz quvurlar orqali uylarga keladi."),
            Q("Benzin qaysi qazilmadan olinadi?", "Neftdan", ["Ko‘mirdan", "Misdan", "Qumdan"],
              x="Neft zavodlarda qayta ishlanib, benzin va boshqa yoqilg‘ilar olinadi."),
            Q("Zargarlik buyumlari ko‘pincha nimadan yasaladi?", "Oltin va kumushdan", ["Ko‘mir va qumdan", "Neft va gazdan", "Tuz va ohaktoshdan"],
              x="Oltin va kumush chiroyli yaltiraydi va zanglamaydi."),
            Q("Qaysi qazilma gaz holatida?", "Tabiiy gaz", ["Ko‘mir", "Neft", "Marmar"],
              x="Nomining o‘zi aytib turibdi — tabiiy gaz."),
            TF("Oltin — yonuvchi qazilma.", False, x="Oltin — qimmatbaho metall, u yonmaydi."),
            TF("Ko‘mir yoqilganda issiqlik ajraladi.", True, x="Shuning uchun ko‘mir yoqilg‘i sifatida ishlatiladi."),
            TF("Foydali qazilmalar tez tiklanadi.", False, x="Ular millionlab yillar davomida hosil bo‘lgan, qayta tiklanmaydi."),
            ORDER(S, "Muruntovda oltin qazib olinadi"),
            Q("Oyna (shisha) asosan qaysi xomashyodan tayyorlanadi?", "Qumdan", ["Ko‘mirdan", "Neftdan", "Oltindan"], d=2,
              x="Shisha maxsus qumni juda yuqori haroratda eritib olinadi."),
            Q("Muruntov koni qaysi qazilma bilan mashhur?", "Oltin", ["Ko‘mir", "Neft", "Tuz"], d=2,
              x="Muruntov — Qizilqumdagi dunyoga mashhur oltin koni."),
            Q("Angren shahri yaqinida qaysi qazilma qazib olinadi?", "Ko‘mir", ["Oltin", "Marmar", "Neft"], d=2,
              x="Angren ko‘mir koni Toshkent viloyatida joylashgan."),
            Q("Gazli shahri nomi qaysi qazilma bilan bog‘liq?", "Tabiiy gaz", ["Oltin", "Mis", "Tuz"], d=2,
              x="Buxoro viloyatidagi Gazli shahri gaz koni yonida qurilgan."),
            Q("Nima uchun foydali qazilmalarni tejash kerak?", "Ular tiklanmaydi", ["Ular juda yengil", "Ular tez o‘sadi", "Ular har yili ko‘payadi"], d=2,
              x="Tugagan qazilma qayta paydo bo‘lmaydi."),
            Q("Neft qanday holatdagi qazilma?", "Suyuq", ["Qattiq", "Gaz", "Kukun"], d=2,
              x="Neft — quyuq, qora rangli suyuqlik."),
            Q("Foydali qazilmalarni izlab topadigan mutaxassis kim?", "Geolog", ["Shifokor", "Oshpaz", "Uchuvchi"], d=2,
              x="Geologlar yer qatlamlarini o‘rganib, konlarni topadi."),
            MATCH("Qazilmani ishlatilishi bilan juftlang",
                  [("Neft", "benzin olinadi"), ("Mis", "elektr simlari"), ("Oltin", "zargarlik buyumlari"), ("Qum", "shisha tayyorlash"),
                   ("Tabiiy gaz", "uyni isitish"), ("Marmar", "binolarni bezash")], d=2,
                  x="Har bir qazilma o‘z sohasida ishlatiladi."),
            Q("Olmaliq kon-metallurgiya kombinati asosan qaysi metallni ishlab chiqaradi?", "Mis", ["Temir", "Qalay", "Platina"], d=3,
              x="Olmaliq — O‘zbekistonning asosiy mis ishlab chiqaruvchi korxonasi."),
            Q("Sho‘rtan va Muborak konlarida nima qazib olinadi?", "Tabiiy gaz", ["Oltin", "Ko‘mir", "Marmar"], d=3,
              x="Qashqadaryo viloyatidagi bu konlar gazi bilan mashhur."),
            Q("Ko‘mir va neft nimalarning qoldiqlaridan hosil bo‘lgan?", "Qadimgi o‘simlik va jonivorlar", ["Muzlagan suv", "Quyosh nuri", "Oddiy qum"], d=3,
              x="Ular millionlab yillar davomida yer ostida o‘zgarib hosil bo‘lgan."),
            MATCH("Kon yoki shaharni qazilma bilan juftlang",
                  [("Muruntov", "oltin"), ("Angren", "ko‘mir"), ("Olmaliq", "mis"), ("Gazli", "tabiiy gaz"), ("G‘ozg‘on", "marmar")], d=3,
                  x="O‘zbekiston foydali qazilmalarga boy."),
        ])

T.topic("matter", "💧", L("Jismlar va moddalar", "Objects and substances", "Тела и вещества"),
        chapter=C2,
        theory="Jism — atrofimizdagi har bir narsa: qalam, tosh, tomchi. Modda — jism nimadan yasalgan bo‘lsa, o‘sha: yog‘och, temir, shisha, suv.\n"
               "Moddalar uch holatda bo‘ladi:\n"
               "• qattiq — shakli va hajmi saqlanadi (muz, tosh, temir);\n"
               "• suyuq — oqadi, idish shaklini oladi, hajmi saqlanadi (suv, sut, yog‘);\n"
               "• gaz — o‘ziga berilgan butun joyni egallaydi (havo, bug‘, tabiiy gaz).\n"
               "Isitilganda ko‘pchilik jismlar kengayadi, sovitilganda torayadi. Tuz va shakar suvda eriydi, qum va bo‘r erimaydi.",
        items=[
            Q("Qaysi so‘z jismni bildiradi?", "Qoshiq", ["Temir", "Kumush", "Yog‘och"],
              x="Qoshiq — jism, temir, kumush va yog‘och esa moddalar."),
            Q("Qaysi so‘z moddani bildiradi?", "Plastmassa", ["Chelak", "Tugma", "Qopqoq"],
              x="Plastmassa — modda, undan chelak, tugma va qopqoq yasaladi."),
            Q("Mix qaysi moddadan yasaladi?", "Temirdan", ["Shishadan", "Qog‘ozdan", "Rezinadan"],
              x="Mix — temirdan yasalgan jism."),
            Q("Qaysi modda qattiq holatda?", "Tosh", ["Sut", "Havo", "Bug‘"],
              x="Toshning shakli va hajmi saqlanadi."),
            Q("Qaysi modda suyuq holatda?", "Sut", ["Muz", "Qum", "Havo"],
              x="Sut oqadi va idish shaklini oladi."),
            Q("Qaysi modda gaz holatida?", "Havo", ["Suv", "Tuz", "Temir"],
              x="Havo xonaning butun hajmini egallaydi."),
            Q("Sharbatni stakandan kosaga quysak, uning shakli nima bo‘ladi?", "Kosa shaklini oladi", ["Stakan shaklida qoladi", "Shar shakliga kiradi", "Qotib qoladi"],
              x="Suyuqlik o‘zi quyilgan idish shaklini oladi."),
            Q("Qaysi modda suvda eriydi?", "Shakar", ["Qum", "Bo‘r", "Tosh"],
              x="Shakar suvda erib, ko‘rinmay qoladi."),
            Q("Qaysi modda suvda erimaydi?", "Qum", ["Tuz", "Shakar", "Soda"],
              x="Qum suvga solinsa, idish tubiga cho‘kadi."),
            Q("Qaysi xossa qattiq jismlarga xos?", "Shaklini saqlaydi", ["Oqadi", "Idish shaklini oladi", "Butun xonaga tarqaladi"],
              x="Qattiq jism tashqi kuch bo‘lmasa, shaklini o‘zgartirmaydi."),
            TF("Suyuqlik idish shaklini oladi.", True, x="Suv stakanda stakan, kosada kosa shaklida bo‘ladi."),
            TF("Qattiq jismning shakli o‘z-o‘zidan o‘zgarib turadi.", False, x="Qattiq jism o‘z shaklini saqlaydi."),
            TF("Havo — gaz holatidagi modda.", True, x="Havo gazlardan iborat, u butun hajmni egallaydi."),
            ORDER(S, "Havo gaz holatida bo‘ladi"),
            Q("Isitilganda jismlar bilan odatda nima bo‘ladi?", "Kengayadi", ["Torayadi", "Yo‘qolib ketadi", "Og‘irlashadi"], d=2,
              x="Qizdirilgan jism biroz kattalashadi — kengayadi."),
            Q("Termometrdagi suyuqlik isiganda nima uchun ko‘tariladi?", "Kengayadi", ["Bug‘lanadi", "Qotadi", "Muzlaydi"], d=2,
              x="Suyuqlik isiganda kengayib, naycha bo‘ylab ko‘tariladi."),
            Q("Gazni qanday idishda saqlash mumkin?", "Yopiq idishda", ["Ochiq likopchada", "Savatda", "To‘rda"], d=2,
              x="Gaz butun hajmni egallaydi va ochiq idishdan tarqalib ketadi."),
            Q("Bir xil moddadan yasalgan jismlar guruhi qaysi?", "Daftar, kitob, gazeta", ["Stol, stakan, qoshiq", "Muz, bug‘, tosh", "Olma, qalam, sut"], d=2,
              x="Daftar, kitob va gazeta qog‘ozdan tayyorlanadi."),
            Q("Choyga solingan shakar ko‘rinmay qolsa, u qayerga ketadi?", "Suvda eriydi", ["Yo‘qolib ketadi", "Bug‘lanadi", "Havoga uchadi"], d=2,
              x="Shakar erib, suv bilan aralashib ketadi — choy shirin bo‘ladi."),
            TF("Sovitilganda jismlar kengayadi.", False, d=2, x="Sovitilganda jismlar torayadi, isitilganda kengayadi."),
            TF("Gazning o‘ziga xos doimiy shakli yo‘q.", True, d=2, x="Gaz qaysi idishda bo‘lsa, o‘sha idishni to‘liq egallaydi."),
            MATCH("Jismni moddasi bilan juftlang",
                  [("Mix", "temir"), ("Deraza oynasi", "shisha"), ("Daftar", "qog‘oz"), ("Stol", "yog‘och"), ("Koptok", "rezina"), ("Uzuk", "oltin")], d=2,
                  x="Har bir jism biror moddadan yasalgan."),
            Q("Nima uchun yozda elektr simlari salqiroq osilib turadi?", "Issiqda kengayib uzayadi", ["Shamol cho‘zadi", "Qushlar tortadi", "Ular eriydi"], d=3,
              x="Issiqda sim kengayib biroz uzayadi, qishda esa qisqarib taranglashadi."),
            Q("Temir yo‘l relslari orasida nima uchun kichik tirqish qoldiriladi?", "Issiqda kengayishi uchun", ["Suv oqishi uchun", "Chiroyli bo‘lishi uchun", "Poyezd sekinlashishi uchun"], d=3,
              x="Yozda relslar kengayadi, tirqish bo‘lmasa, ular egilib qolishi mumkin."),
        ])

T.test("test2", L("2-nazorat ishi", "Test 2", "Контрольная работа 2"),
       ["zones", "rivers", "minerals", "matter"], chapter=C2)

# ============================================================ 3-chorak
T.topic("habitats", "🐟", L("Tirik organizmlar va yashash muhiti", "Living things and their habitats", "Живые организмы и среды обитания"),
        chapter=C3,
        theory="Yashash muhiti — organizm yashaydigan, undan oziq, suv va boshpana oladigan joy.\n"
               "• Suv muhiti: baliqlar, delfin, kit, suvo‘tlar. Baliqlar jabra bilan nafas oladi, tanasi suyri, suzgich qanotlari bor.\n"
               "• Quruqlik-havo muhiti: ko‘pchilik hayvonlar, qushlar va o‘simliklar. Havoda kislorod ko‘p, lekin harorat tez o‘zgaradi.\n"
               "• Tuproq muhiti: yomg‘ir chuvalchangi, ko‘rsichqon, qo‘ng‘iz lichinkalari. Tuproqda qorong‘i va zich.\n"
               "Organizmlar muhitga moslashgan: tuyaning o‘rkachida yog‘ zaxirasi bor, o‘rdak oyog‘ida suzgich parda bor.",
        items=[
            Q("Baliqlar qaysi muhitda yashaydi?", "Suv muhitida", ["Tuproq muhitida", "Quruqlik-havo muhitida", "Qum ichida"], e="🐟",
              x="Baliqlar faqat suvda yashay oladi."),
            Q("Yomg‘ir chuvalchangi qaysi muhitda yashaydi?", "Tuproqda", ["Suvda", "Havoda", "Daraxt shoxida"],
              x="Yomg‘ir chuvalchangi tuproqda yo‘l ochib yashaydi."),
            Q("Burgut qaysi muhitda yashaydi?", "Quruqlik-havo muhitida", ["Suv muhitida", "Tuproq muhitida", "Muz ostida"],
              x="Burgut havoda uchadi, uyasini qoyalarda quradi."),
            Q("Baliq qaysi a’zo bilan nafas oladi?", "Jabra bilan", ["O‘pka bilan", "Qanot bilan", "Dum bilan"],
              x="Jabralar suvdagi kislorodni o‘zlashtiradi."),
            Q("O‘rdak oyog‘idagi parda nima uchun kerak?", "Suzish uchun", ["Uchish uchun", "Yer kovlash uchun", "Isinish uchun"], e="🦆",
              x="Parda eshkakdek suvni itarib, o‘rdakka suzishga yordam beradi."),
            Q("Qaysi hayvon suvda ham, quruqlikda ham yashaydi?", "Baqa", ["Laqqa", "Chumchuq", "Tulki"], e="🐸",
              x="Baqa suvda tuxum qo‘yadi, katta bo‘lgach quruqlikka ham chiqadi."),
            Q("Qaysi o‘simlik suvda o‘sadi?", "Nilufar", ["Saksovul", "Yantoq", "Archa"],
              x="Nilufarning barglari suv yuzasida suzib turadi."),
            Q("Ko‘rsichqonning oldingi oyoqlari nimaga moslashgan?", "Yer kovlashga", ["Suzishga", "Uchishga", "Daraxtga chiqishga"],
              x="Ko‘rsichqonning kurakdek keng oyoqlari tuproqni kovlaydi."),
            TF("Baqa suvda ham, quruqlikda ham yashay oladi.", True, x="Baqa — suvda hamda quruqlikda yashovchi hayvon."),
            TF("Tuproq ichida yorug‘lik ko‘p bo‘ladi.", False, x="Tuproq ichida qorong‘i, Quyosh nuri u yerga yetib bormaydi."),
            TF("Har bir organizm o‘z yashash muhitiga moslashgan.", True, x="Masalan, baliq suvga, ko‘rsichqon tuproqqa moslashgan."),
            ORDER(S, "Baliqlar suvda jabra bilan nafas oladi"),
            Q("Kit qanday nafas oladi?", "O‘pka bilan, havodan", ["Jabra bilan", "Teri bilan", "Nafas olmaydi"], d=2,
              x="Kit — sut emizuvchi, u suv yuzasiga chiqib havo oladi."),
            Q("Delfin qaysi hayvonlar guruhiga kiradi?", "Sut emizuvchilar", ["Baliqlar", "Qushlar", "Hasharotlar"], d=2,
              x="Delfin bolasini sut bilan boqadi va o‘pka bilan nafas oladi."),
            Q("Yomg‘ir chuvalchangi tuproqqa qanday foyda keltiradi?", "Tuproqni yumshatadi", ["Tuproqni quritadi", "Tuproqni zaharlaydi", "Ildizlarni kemiradi"], d=2,
              x="Chuvalchang yo‘llari orqali tuproqqa havo va suv kiradi."),
            Q("Baliq tanasining suyri shakli nima uchun kerak?", "Suvda oson suzish uchun", ["Uchish uchun", "Yer kovlash uchun", "Isinish uchun"], d=2,
              x="Suyri tana suvni oson yorib o‘tadi."),
            Q("Tuyaning o‘rkachida nima to‘planadi?", "Yog‘", ["Suv", "Havo", "Qum"], d=2,
              x="O‘rkachdagi yog‘ zaxirasi tuyaga uzoq vaqt ovqatsiz yurishga yordam beradi."),
            Q("Oq ayiqni sovuqdan nima himoya qiladi?", "Qalin mo‘yna va yog‘ qatlami", ["Qanotlari", "Tangachalari", "Uzun dumi"], d=2,
              x="Qalin mo‘yna va teri ostidagi yog‘ issiqlikni saqlaydi."),
            TF("Kit — baliq.", False, d=2, x="Kit — sut emizuvchi hayvon, u suvda yashasa ham baliq emas."),
            MATCH("Organizmni moslashuvi bilan juftlang",
                  [("Baliq", "jabra va suzgich qanotlar"), ("Ko‘rsichqon", "kurakdek oldingi oyoqlar"), ("O‘rdak", "oyoqdagi suzgich parda"),
                   ("Tuya", "o‘rkachdagi yog‘"), ("Oq ayiq", "qalin oq mo‘yna"), ("Kaktus", "tikanga aylangan barglar")], d=2,
                  x="Har bir organizm o‘z muhitida yashashga moslashgan."),
            Q("Nima uchun ko‘rsichqonning ko‘zlari juda kichik?", "Tuproq ichi qorong‘i", ["U doim uxlaydi", "U suvda yashaydi", "U tunda uchadi"], d=3,
              x="Qorong‘i tuproqda ko‘rish deyarli kerak emas, ko‘rsichqon hid va sezish bilan mo‘ljal oladi."),
            Q("Kaktusning tikanlari aslida nima?", "O‘zgargan barglar", ["Ildizlar", "Gullar", "Mevalar"], d=3,
              x="Barglar tikanga aylangani uchun kaktus suvni kam bug‘latadi."),
            Q("Qaysi muhitda harorat eng tez o‘zgaradi?", "Quruqlik-havo muhitida", ["Suv muhitida", "Tuproq muhitida", "Chuqur ko‘l tubida"], d=3,
              x="Havo tez isib, tez soviydi, suv va tuproqda esa harorat ancha barqaror."),
        ])

T.topic("plant_repro", "🌷", L("O‘simliklarning ko‘payishi", "How plants reproduce", "Размножение растений"),
        chapter=C3,
        theory="O‘simliklar ikki xil yo‘l bilan ko‘payadi.\n"
               "• Urug‘ bilan: bug‘doy, g‘o‘za, loviya, qovun, kungaboqar. Urug‘ unishi uchun namlik, havo va issiqlik kerak.\n"
               "• Vegetativ yo‘l bilan — o‘simlik qismlaridan: qalamcha (tol, terak, uzum), piyozbosh (piyoz, lola, sarimsoq), tuganak (kartoshka), ildizpoya (ajriq), mo‘ylov (qulupnay).\n"
               "Urug‘larni shamol (qoqio‘t), suv, hayvon va qushlar tarqatadi.\n"
               "Bog‘bonlar mevali daraxtlarni payvand qilib ham ko‘paytiradi.",
        items=[
            Q("Bug‘doy qanday ko‘paytiriladi?", "Urug‘ bilan", ["Qalamcha bilan", "Piyozbosh bilan", "Tuganak bilan"], e="🌾",
              x="Dalaga bug‘doy doni — urug‘i sepiladi."),
            Q("Kartoshka odatda nima bilan ekiladi?", "Tuganagi bilan", ["Guli bilan", "Bargi bilan", "Qalamcha bilan"],
              x="Kartoshka tuganagidagi ko‘zchalardan yangi o‘simlik o‘sadi."),
            Q("Piyoz qanday ko‘payadi?", "Piyozbosh bilan", ["Qalamcha bilan", "Mo‘ylov bilan", "Tuganak bilan"],
              x="Yerga ekilgan kichik piyozboshdan yangi piyoz o‘sadi."),
            Q("Tol va terak qanday oson ko‘payadi?", "Qalamcha bilan", ["Piyozbosh bilan", "Tuganak bilan", "Mo‘ylov bilan"],
              x="Nam yerga sanchilgan tol qalamchasi tez ildiz otadi."),
            Q("Qalamcha nima?", "Kesib olingan novda bo‘lagi", ["Guldan olingan chang", "Urug‘ning po‘sti", "Ildiz tukchasi"],
              x="Qalamcha — kurtaklari bor novda bo‘lagi, u ekilsa ildiz chiqaradi."),
            Q("Qoqio‘t urug‘ini nima tarqatadi?", "Shamol", ["Suv", "Baliqlar", "Chuvalchang"],
              x="Qoqio‘t urug‘ining momiq “parashyuti” bor, shamol uni uzoqqa uchiradi."),
            Q("Gulni changlatishda kimlar yordam beradi?", "Hasharotlar", ["Baliqlar", "Chuvalchanglar", "Ko‘rsichqonlar"],
              x="Asalari va kapalaklar gul changini bir guldan boshqasiga tashiydi."),
            Q("Uzum ko‘chatini qanday ko‘paytirish qulay?", "Qalamcha bilan", ["Piyozbosh bilan", "Tuganak bilan", "Mo‘ylov bilan"],
              x="Uzum novdasidan kesilgan qalamcha ekilsa, ildiz otadi."),
            TF("Barcha o‘simliklar faqat urug‘ bilan ko‘payadi.", False, x="Ko‘p o‘simliklar qalamcha, piyozbosh, tuganak bilan ham ko‘payadi."),
            TF("Urug‘ tarqalishida hayvonlar ham yordam beradi.", True, x="Qushlar mevani yeb, urug‘ini boshqa joyga olib boradi."),
            TF("Qalamcha ekilganda ildiz chiqarmaydi.", False, x="Qalamcha nam tuproqda ildiz chiqaradi va yangi o‘simlikka aylanadi."),
            ORDER(S, "Tol qalamcha bilan tez ko‘payadi"),
            Q("Qulupnay qanday ko‘payadi?", "Mo‘ylovlari bilan", ["Piyozbosh bilan", "Tuganak bilan", "Qalamcha bilan"], d=2,
              x="Qulupnayning yer bag‘irlab o‘sadigan mo‘ylovlari ildiz otib, yangi tup hosil qiladi."),
            Q("Urug‘ quruq qopda nima uchun unib chiqmaydi?", "Namlik yo‘q", ["Havo juda ko‘p", "Qop juda katta", "Issiqlik ortiqcha"], d=2,
              x="Urug‘ unishi uchun namlik, havo va issiqlik kerak."),
            Q("Olcha mevasini yegan qushlar nimaga yordam beradi?", "Urug‘ tarqalishiga", ["Barg to‘kilishiga", "Ildiz chirishiga", "Gul so‘lishiga"], d=2,
              x="Qushlar urug‘ni uzoqqa olib borib tashlaydi, u yerda yangi daraxt unadi."),
            Q("O‘simlikning bir qismidan yangi o‘simlik o‘stirish nima deyiladi?", "Vegetativ ko‘payish", ["Urug‘dan ko‘payish", "Changlanish", "Gullash"], d=2,
              x="Qalamcha, piyozbosh, tuganak — vegetativ ko‘payish usullari."),
            Q("Sarimsoq qanday ekiladi?", "Tishchalari bilan", ["Barglari bilan", "Guli bilan", "Qalamcha bilan"], d=2,
              x="Sarimsoq boshidagi har bir tishchadan yangi o‘simlik o‘sadi."),
            TF("Kartoshka tuganagida kurtaklar — ko‘zchalar bo‘ladi.", True, d=2, x="Ko‘zchalardan yangi novdalar o‘sib chiqadi."),
            MATCH("O‘simlikni ko‘payish usuli bilan juftlang",
                  [("Bug‘doy", "urug‘"), ("Terak", "qalamcha"), ("Lola", "piyozbosh"), ("Kartoshka", "tuganak"), ("Qulupnay", "mo‘ylov"), ("Ajriq", "ildizpoya")], d=2,
                  x="O‘simliklar turli yo‘llar bilan ko‘payadi."),
            Q("Bog‘bon yovvoyi olma ko‘chatiga shirin olma novdasini ulab qo‘ydi. Bu nima?", "Payvand", ["Qalamcha", "Changlanish", "Sug‘orish"], d=3,
              x="Payvandlangan daraxt shirin olma navining mevasini beradi."),
            Q("Loviya urug‘i unganda birinchi bo‘lib nima chiqadi?", "Ildizcha", ["Gul", "Meva", "Barg"], d=3,
              x="Avval ildizcha chiqib tuproqqa kiradi, keyin poyacha yuqoriga o‘sadi."),
            Q("Urug‘ ichidagi kelajakdagi kichik o‘simlik nima deyiladi?", "Murtak", ["Po‘st", "Meva eti", "Chang"], d=3,
              x="Murtakda ildizcha, poyacha va kurtakcha bor."),
            Q("Qaysi o‘simlik urug‘ini dengiz suvi tarqatadi?", "Kokos palmasi", ["Qoqio‘t", "Kungaboqar", "Bug‘doy"], d=3,
              x="Kokos yong‘og‘i suvda cho‘kmaydi va boshqa qirg‘oqqa suzib boradi."),
        ])

T.topic("digestion", "🍽️", L("Ovqat hazm qilish", "Digestion", "Пищеварение"),
        chapter=C3,
        theory="Ovqat hazm qilish — ovqatning organizm o‘zlashtira oladigan mayda moddalarga aylanishi.\n"
               "Yo‘li: og‘iz bo‘shlig‘i → halqum → qizilo‘ngach → oshqozon → ingichka ichak → yo‘g‘on ichak.\n"
               "• Og‘izda tishlar ovqatni maydalaydi, so‘lak uni namlaydi. Oshqozonda ovqat me’da shirasi bilan aralashadi.\n"
               "• Ingichka ichakda oziq moddalar qonga so‘riladi. Jigar o‘t suyuqligi ishlab chiqaradi.\n"
               "Qoidalar: ovqatni yaxshilab chaynang, ovqatdan oldin qo‘l yuving, bir vaqtda ovqatlaning, ovqat paytida gaplashmang.",
        items=[
            Q("Ovqat hazm qilish qayerdan boshlanadi?", "Og‘iz bo‘shlig‘idan", ["Oshqozondan", "Ichakdan", "Jigardan"],
              x="Og‘izda ovqat maydalanib, so‘lak bilan namlanadi."),
            Q("Ovqat oshqozonga qaysi naycha orqali o‘tadi?", "Qizilo‘ngach", ["Kekirdak", "Qon tomir", "Bronx"],
              x="Qizilo‘ngach — halqumdan oshqozonga boradigan mushakli naycha."),
            Q("Ovqat og‘izda nima bilan namlanadi?", "So‘lak bilan", ["O‘t suyuqligi bilan", "Qon bilan", "Havo bilan"],
              x="So‘lak ovqatni namlaydi va yutishni osonlashtiradi."),
            Q("Oshqozonda ovqat bilan nima bo‘ladi?", "Me’da shirasi bilan aralashadi", ["Havoga aylanadi", "Qonni haydaydi", "Tovush chiqaradi"],
              x="Oshqozon devorlari qisqarib, ovqatni me’da shirasi bilan aralashtiradi."),
            Q("Ovqatni nima uchun yaxshilab chaynash kerak?", "Oson hazm bo‘lishi uchun", ["Tez yutish uchun", "Tish og‘rishi uchun", "Ko‘p yeyish uchun"],
              x="Yaxshi maydalangan ovqat oshqozon va ichakda oson hazm bo‘ladi."),
            Q("Ovqatdan oldin nima qilish kerak?", "Qo‘lni sovunlab yuvish", ["Yugurib kelish", "Uxlab olish", "Shirinlik yeyish"],
              x="Iflos qo‘ldagi mikroblar ovqat bilan birga tanaga tushishi mumkin."),
            Q("Yuvilmagan meva-sabzavot nima uchun xavfli?", "Unda mikroblar bo‘lishi mumkin", ["U juda shirin", "U tez eriydi", "U juda og‘ir"],
              x="Meva va sabzavotni yeyishdan oldin toza suvda yuvish kerak."),
            Q("Qaysi a’zo hazm qilish a’zolariga kiradi?", "Oshqozon", ["O‘pka", "Yurak", "Miya"],
              x="O‘pka — nafas olish, yurak — qon aylanish, miya — asab tizimiga kiradi."),
            TF("Qizilo‘ngach ovqatni oshqozonga olib boradi.", True, x="Qizilo‘ngach halqumni oshqozon bilan bog‘laydi."),
            TF("Ovqat hazm qilish oshqozonda boshlanadi.", False, x="Hazm qilish og‘iz bo‘shlig‘ida boshlanadi."),
            TF("Ko‘p shirinlik yeyish tishlarga zarar.", True, x="Shirinlik qoldiqlari tishda kariesga sabab bo‘ladi."),
            ORDER(S, "Ovqatni shoshilmay yaxshilab chaynang"),
            Q("Oziq moddalar asosan qayerda qonga so‘riladi?", "Ingichka ichakda", ["Og‘izda", "Qizilo‘ngachda", "Halqumda"], d=2,
              x="Ingichka ichak devorlari orqali oziq moddalar qonga o‘tadi."),
            Q("O‘t suyuqligini qaysi a’zo ishlab chiqaradi?", "Jigar", ["Yurak", "O‘pka", "Buyrak"], d=2,
              x="Jigar o‘t suyuqligi ishlab chiqaradi, u yog‘larni hazm qilishga yordam beradi."),
            Q("Ovqatni kesib, tishlab oladigan old tishlar qanday ataladi?", "Kurak tishlar", ["Oziq tishlar", "Qoziq tishlar", "Aql tishlari"], d=2,
              x="Kurak tishlar o‘tkir va yassi, ular ovqatni kesadi."),
            Q("Ovqatni maydalab chaynaydigan keng tishlar qaysi?", "Oziq tishlar", ["Kurak tishlar", "Qoziq tishlar", "Tish milki"], d=2,
              x="Oziq tishlarning keng yuzasi ovqatni ezib maydalaydi."),
            Q("Katta odamda nechta doimiy tish bo‘ladi?", "32 ta", ["20 ta", "12 ta", "50 ta"], d=2,
              x="Bolalarda 20 ta sut tishi bo‘ladi, keyin ular doimiy tishlarga almashadi, jami 32 ta."),
            Q("Nima uchun ovqatlanayotganda gaplashmaslik kerak?", "Ovqat nafas yo‘liga tushishi mumkin", ["Ovqat sovib qoladi", "Tish tushib ketadi", "Ishtaha yo‘qoladi"], d=2,
              x="Gapirganda ovqat bo‘lagi kekirdakka tushib, qaqqirishga sabab bo‘lishi mumkin."),
            Q("Hazm bo‘lmagan qoldiqlar qayerda to‘planadi?", "Yo‘g‘on ichakda", ["Oshqozonda", "Og‘izda", "Qizilo‘ngachda"], d=2,
              x="Yo‘g‘on ichakda suv so‘riladi, qoldiqlar esa tanadan chiqariladi."),
            ORDER("Ovqat yo‘lini tartib bilan tuzing", "Og‘iz → Qizilo‘ngach → Oshqozon → Ingichka ichak → Yo‘g‘on ichak", sep=" → ", d=2,
                  x="Ovqat og‘izdan boshlab ichaklargacha shu tartibda o‘tadi."),
            MATCH("A’zoni vazifasi bilan juftlang",
                  [("Tishlar", "ovqatni maydalaydi"), ("So‘lak", "ovqatni namlaydi"), ("Qizilo‘ngach", "ovqatni oshqozonga o‘tkazadi"),
                   ("Oshqozon", "ovqatni shira bilan aralashtiradi"), ("Ingichka ichak", "oziq moddalarni qonga o‘tkazadi"),
                   ("Jigar", "o‘t suyuqligi ishlab chiqaradi")], d=2,
                  x="Hazm qilish a’zolari birgalikda ishlaydi."),
            Q("Bolalarning sut tishlari nechta?", "20 ta", ["32 ta", "10 ta", "28 ta"], d=3,
              x="Sut tishlari 20 ta, ular taxminan 6 yoshdan boshlab doimiy tishlarga almashadi."),
            Q("Odam tanasidagi eng qattiq modda qaysi?", "Tish emali", ["Suyak", "Tirnoq", "Soch"], d=3,
              x="Tishni qoplab turgan emal suyakdan ham qattiq."),
            TF("Juda issiq va juda sovuq ovqatni ketma-ket yeyish tish emaliga zarar.", True, d=3,
               x="Harorat keskin o‘zgarsa, emalda mayda yoriqlar paydo bo‘lishi mumkin."),
        ])

# --- Puls: yurak urishini sanash (Python'da hisoblanadi).
_pulse = []
for sec, beats, d in [(10, 14, 2), (15, 20, 2), (30, 42, 3), (10, 16, 3)]:
    per_min = beats * (60 // sec)
    assert per_min == beats * 60 / sec
    _pulse.append(Q(f"Ali {sec} soniyada tomir urishini sanadi: {beats} marta. 1 daqiqada yuragi necha marta uradi?", per_min,
                    near(per_min, [beats * 2, per_min + 10, per_min - 10, beats + 60, beats * 10], lo=1), d=d,
                    x=f"1 daqiqa = 60 soniya. 60 : {sec} = {60 // sec}, demak {beats} · {60 // sec} = {per_min}."))

T.topic("breathing_blood", "❤️", L("Nafas olish va qon aylanishi", "Breathing and blood circulation", "Дыхание и кровообращение"),
        chapter=C3,
        theory="Nafas olish a’zolari: burun bo‘shlig‘i → hiqildoq → kekirdak → bronxlar → o‘pka.\n"
               "• Burunda havo isiydi, namlanadi va changdan tozalanadi. Organizm havodan kislorodni oladi, karbonat angidridni chiqaradi.\n"
               "• Yurak — qonni tomirlar bo‘ylab haydovchi mushakli “nasos”. U ko‘krak qafasida, biroz chaproqda joylashgan, kattaligi mushtdek.\n"
               "• Qon tomirlari: arteriyalar qonni yurakdan olib ketadi, venalar yurakka olib keladi, kapillyarlar — eng ingichka tomirlar.\n"
               "Qon kislorod va oziq moddalarni butun tanaga yetkazadi. Tomir urishini (pulsni) bilakda sanash mumkin.",
        items=[
            Q("Asosiy nafas olish a’zosi qaysi?", "O‘pka", ["Oshqozon", "Jigar", "Ichak"],
              x="O‘pkada havodagi kislorod qonga o‘tadi."),
            Q("Organizm havodan qaysi gazni o‘zlashtiradi?", "Kislorod", ["Karbonat angidrid", "Is gazi", "Tabiiy gaz"],
              x="Kislorod qon orqali barcha hujayralarga yetkaziladi."),
            Q("Nafas chiqarganda organizmdan qaysi keraksiz gaz chiqariladi?", "Karbonat angidrid", ["Kislorod", "Vodorod", "Tabiiy gaz"],
              x="Karbonat angidrid hujayralarda hosil bo‘lib, o‘pka orqali chiqariladi."),
            Q("Nima uchun burun orqali nafas olish foydali?", "Havo isiydi va tozalanadi", ["Ovoz chiroyli chiqadi", "Tez yugurish mumkin", "Ishtaha ochiladi"],
              x="Burun bo‘shlig‘ida havo isiydi, namlanadi va changdan tozalanadi."),
            Q("Qonni tomirlar bo‘ylab haydaydigan a’zo qaysi?", "Yurak", ["O‘pka", "Oshqozon", "Miya"],
              x="Yurak to‘xtovsiz qisqarib, qonni tomirlarga haydaydi."),
            Q("Qon organizmda nimani tashiydi?", "Kislorod va oziq moddalar", ["Faqat suv", "Tosh va qum", "Havo pufaklari"],
              x="Qon kislorod va oziqni hujayralarga yetkazadi, keraksiz moddalarni olib ketadi."),
            Q("Pulsni qayerda sanash qulay?", "Bilakda", ["Tizzada", "Tirnoqda", "Tovonda"],
              x="Bilakning ichki tomonida tomir urishi yaxshi seziladi."),
            Q("Yugurgandan keyin yurak urishi qanday o‘zgaradi?", "Tezlashadi", ["Sekinlashadi", "To‘xtaydi", "O‘zgarmaydi"],
              x="Harakat paytida mushaklarga ko‘proq kislorod kerak, yurak tezroq uradi."),
            TF("Yurak kecha-yu kunduz to‘xtovsiz ishlaydi.", True, x="Yurak uxlaganimizda ham ishlaydi."),
            TF("Sport yurak mushaklarini chiniqtiradi.", True, x="Muntazam harakat yurakni baquvvat qiladi."),
            TF("Tamaki tutuni o‘pkaga foydali.", False, x="Tutun o‘pkani zararlaydi, tutunli xonada o‘tirish ham zararli."),
            ORDER(S, "Yurak qonni butun tanaga haydaydi"),
            Q("Yurakning kattaligi taxminan qanday?", "Egasining mushtidek", ["No‘xatdek", "Tarvuzdek", "Ko‘krak qafasidek"], d=2,
              x="Har bir odamning yuragi taxminan o‘z mushtidek bo‘ladi."),
            Q("Yurak nimadan tuzilgan?", "Mushakdan", ["Suyakdan", "Yog‘dan", "Tog‘aydan"], d=2,
              x="Yurak — kuchli mushakli a’zo, u qisqarib qonni haydaydi."),
            Q("Qonni yurakdan olib ketadigan tomirlar qanday ataladi?", "Arteriyalar", ["Venalar", "Kapillyarlar", "Bronxlar"], d=2,
              x="Arteriyalar qonni yurakdan a’zolarga olib boradi."),
            Q("Qonni yurakka olib keladigan tomirlar qanday ataladi?", "Venalar", ["Arteriyalar", "Kapillyarlar", "Nervlar"], d=2,
              x="Venalar qonni a’zolardan yurakka qaytaradi."),
            Q("Kekirdak qaysi a’zolar tizimiga kiradi?", "Nafas olish", ["Hazm qilish", "Qon aylanish", "Sezgi"], d=2,
              x="Kekirdak havoni hiqildoqdan bronxlarga o‘tkazadi."),
            TF("Arteriyalar qonni yurakka olib keladi.", False, d=2, x="Arteriyalar qonni yurakdan olib ketadi, venalar yurakka olib keladi."),
            MATCH("A’zoni vazifasi bilan juftlang",
                  [("Burun bo‘shlig‘i", "havoni isitadi va tozalaydi"), ("Kekirdak", "havoni bronxlarga o‘tkazadi"), ("O‘pka", "havodan kislorod oladi"),
                   ("Yurak", "qonni haydaydi"), ("Arteriya", "qonni yurakdan olib ketadi"), ("Vena", "qonni yurakka olib keladi")], d=2,
                  x="Nafas olish va qon aylanish a’zolari birgalikda ishlaydi."),
            Q("Eng ingichka qon tomirlari qanday ataladi?", "Kapillyarlar", ["Arteriyalar", "Venalar", "Bronxlar"], d=3,
              x="Kapillyarlar sochdan ham ingichka, ular orqali qon hujayralarga kislorod beradi."),
            Q("Katta odam tanasida taxminan qancha qon bor?", "5 litr", ["1 litr", "20 litr", "50 litr"], d=3,
              x="Katta odamda taxminan 5 litr qon bo‘ladi."),
            Q("Mikroblarga qarshi kurashadigan qon hujayralari qaysi?", "Oq qon tanachalari", ["Qizil qon tanachalari", "Suyak hujayralari", "Teri hujayralari"], d=3,
              x="Oq qon tanachalari organizmni mikroblardan himoya qiladi, qizillari esa kislorod tashiydi."),
        ] + _pulse)

T.test("test3", L("3-nazorat ishi", "Test 3", "Контрольная работа 3"),
       ["habitats", "plant_repro", "digestion", "breathing_blood"], chapter=C3)

# ============================================================ 4-chorak
T.topic("senses_hygiene", "👀", L("Sezgi a’zolari gigiyenasi", "Caring for the sense organs", "Гигиена органов чувств"),
        chapter=C4,
        theory="Sezgi a’zolari: ko‘z, quloq, burun, til va teri. Ularni asrash uchun gigiyena qoidalariga amal qilamiz.\n"
               "• Ko‘z: kitobni 30–35 sm uzoqlikda, yorug‘ joyda o‘qing; yotib va yurib ketayotgan transportda o‘qimang; ekrandan har 20–30 daqiqada ko‘zga dam bering.\n"
               "• Quloq: o‘tkir narsa bilan tozalamang, baland ovozli musiqa tinglamang, sovuqda qulog‘ingizni yoping.\n"
               "• Burun: dastro‘moldan foydalaning. Til: juda issiq ovqat tilni kuydiradi.\n"
               "• Teri: har kuni yuvining, jazirama Quyoshda uzoq qolmang, jarohatni tozalab, kattalarga ayting.",
        items=[
            Q("Kitobni ko‘zdan qancha uzoqlikda tutib o‘qish kerak?", "30–35 sm", ["5 sm", "1 metr", "2 metr"], e="📖",
              x="Kitob juda yaqin bo‘lsa, ko‘z tez charchaydi."),
            Q("O‘qiganda yorug‘lik qanday bo‘lishi kerak?", "Yetarli va bir tekis", ["Juda xira", "Ko‘zga to‘g‘ri tushadigan", "Miltillovchi"],
              x="Xira yoki miltillovchi yorug‘lik ko‘zni charchatadi."),
            Q("Qaysi odat ko‘z uchun zararli?", "Yotib kitob o‘qish", ["Yashil daraxtlarga qarash", "Ko‘zga dam berish", "Yorug‘ joyda o‘qish"],
              x="Yotib o‘qiganda kitob ko‘zga notekis masofada turadi."),
            Q("Quloqchinda musiqani qanday tinglash kerak?", "Past ovozda, qisqa vaqt", ["Eng baland ovozda", "Tun bo‘yi", "Kun bo‘yi"], e="🎧",
              x="Baland ovoz eshitish qobiliyatini susaytiradi."),
            Q("Qishda sovuqda quloqni nima himoya qiladi?", "Issiq shapka", ["Ko‘zoynak", "Qo‘lqop", "Soyabon"],
              x="Sovuqda qolgan quloq shamollashi mumkin."),
            Q("Aksirganda nima qilish kerak?", "Og‘izni dastro‘mol bilan yopish", ["Boshqalarga qarab aksirish", "Qo‘lni yuvmaslik", "Baland kulish"],
              x="Aksirganda mikroblar atrofga tarqaladi."),
            Q("Juda issiq choy ichsak, qaysi a’zo zarar ko‘radi?", "Til", ["Quloq", "Ko‘z", "Tirnoq"],
              x="Juda issiq ichimlik tilni kuydiradi va ta’m sezish buziladi."),
            Q("Yozda jazirama Quyoshda nima kiyish kerak?", "Bosh kiyim", ["Qalin po‘stin", "Qishki etik", "Jun qo‘lqop"],
              x="Bosh kiyim Quyosh urishidan saqlaydi."),
            Q("Tirnoqlarni qanday parvarish qilamiz?", "Muntazam olib, toza tutamiz", ["Tishlab olamiz", "Hech qachon olmaymiz", "Iflos qoldiramiz"],
              x="Tirnoq ostida mikroblar to‘planadi."),
            TF("Yurib ketayotgan avtobusda kitob o‘qish ko‘zga foydali.", False, x="Silkinishda harflar sakraydi va ko‘z tez charchaydi."),
            TF("Baland ovozli shovqin eshitish qobiliyatini susaytiradi.", True, x="Kuchli shovqin quloqni jarohatlaydi."),
            TF("Ko‘zni iflos qo‘l bilan ishqalash mumkin.", False, x="Iflos qo‘ldan ko‘zga mikrob tushib, yallig‘lanish bo‘lishi mumkin."),
            ORDER(S, "Kitobni yorug‘ joyda o‘qing"),
            Q("Ko‘zni changdan nima himoya qiladi?", "Kiprik va qovoq", ["Burun va lab", "Tirnoq va soch", "Quloq suprasi"], d=2,
              x="Kipriklar chang zarralarini ushlaydi, qovoq ko‘zni yopib himoya qiladi."),
            Q("Kompyuterda ishlaganda ko‘zga qanchada bir dam berish kerak?", "Har 20–30 daqiqada", ["Kuniga bir marta", "Hech qachon", "Haftada bir marta"], d=2,
              x="Uzoqqa qarab, ko‘z mashqlarini bajarish ko‘zni dam oldiradi."),
            Q("Ko‘zga chang tushsa nima qilish kerak?", "Toza suv bilan yuvish", ["Qattiq ishqalash", "Barmoq bilan kavlash", "Iflos ro‘molcha bilan artish"], d=2,
              x="Toza suv changni yuvib chiqaradi, ishqalash esa ko‘zni tirnaydi."),
            Q("Quloqni tozalashda nima xavfli?", "O‘tkir narsa tiqish", ["Tashqi qismini sochiq bilan artish", "Yuvinganda yuvish", "Kattalardan yordam so‘rash"], d=2,
              x="O‘tkir narsa quloq pardasini teshishi mumkin."),
            Q("Qo‘l kesilsa, avvalo nima qilish kerak?", "Yarani tozalab, kattalarga aytish", ["Yarani yalash", "Tuproq sepish", "Hech kimga aytmaslik"], d=2,
              x="Toza bo‘lmagan yaraga mikrob tushib, yiringlashi mumkin."),
            Q("Nima uchun Quyoshga to‘g‘ridan-to‘g‘ri qarash mumkin emas?", "Ko‘zni jarohatlaydi", ["Burun bitib qoladi", "Quloq og‘riydi", "Soch oqaradi"], d=2,
              x="Quyoshning kuchli nuri ko‘zning nozik qismlarini shikastlaydi."),
            TF("Kiyim va ichki kiyimni muntazam almashtirish kerak.", True, d=2, x="Toza kiyim teri sog‘lig‘i uchun muhim."),
            MATCH("Sezgi a’zosini gigiyena qoidasi bilan juftlang",
                  [("Ko‘z", "yorug‘ joyda o‘qish"), ("Quloq", "baland shovqindan saqlanish"), ("Burun", "dastro‘moldan foydalanish"),
                   ("Til", "juda issiq ovqat yemaslik"), ("Teri", "har kuni yuvinish")], d=2,
                  x="Har bir sezgi a’zosini o‘z qoidasi bilan asraymiz."),
            Q("Ko‘z yoshining vazifasi nima?", "Ko‘zni namlab, yuvib turadi", ["Ko‘rishni susaytiradi", "Ko‘zni qizdiradi", "Ko‘zni quritadi"], d=3,
              x="Ko‘z yoshi ko‘z yuzasini namlaydi va chang-mikroblardan tozalaydi."),
            Q("Teridagi mayda teshikchalardan nima ajraladi?", "Ter", ["Qon", "So‘lak", "Ko‘z yoshi"], d=3,
              x="Ter ajralishi tanani sovitadi, shuning uchun terini toza tutish kerak."),
        ])

T.topic("nutrition", "🥕", L("Sog‘lom ovqatlanish va vitaminlar", "Healthy eating and vitamins", "Здоровое питание и витамины"),
        chapter=C4,
        theory="Ovqatda organizmga kerakli oziq moddalar bor:\n"
               "• Oqsillar — o‘sish uchun “qurilish materiali”: go‘sht, baliq, tuxum, sut, loviya, no‘xat.\n"
               "• Uglevodlar — energiya manbai: non, guruch, kartoshka, meva. Yog‘lar — energiya zaxirasi: sariyog‘, o‘simlik yog‘i, yong‘oq.\n"
               "• Vitaminlar: A — sabzi, qovoq (ko‘rish uchun); C — limon, na’matak, qalampir (kasalliklarga qarshi); D — Quyosh nurida terida hosil bo‘ladi, baliq yog‘ida bor (suyaklar uchun).\n"
               "Kalsiy (sut, qatiq, pishloq) suyak va tishlarni mustahkamlaydi. Vaqtida ovqatlaning; chips va gazli ichimliklarni kam iste’mol qiling.",
        items=[
            Q("Qaysi mahsulotda oqsil ko‘p?", "Tuxum", ["Shakar", "Olma", "Choy"], e="🥚",
              x="Tuxum, go‘sht, baliq va sut — oqsilga boy."),
            Q("Qaysi mahsulot organizmga ko‘p energiya beradi?", "Non", ["Suv", "Tuz", "Ko‘k choy"], e="🍞",
              x="Nondagi uglevodlar organizm uchun energiya manbai."),
            Q("Qaysi mahsulotda C vitamini ko‘p?", "Limon", ["Sariyog‘", "Guruch", "Shakar"], e="🍋",
              x="Limon, na’matak va qalampir C vitaminiga boy."),
            Q("Qaysi sabzavotda A vitamini ko‘p?", "Sabzi", ["Bodring", "Piyoz", "Turp"], e="🥕",
              x="Sabzi va qovoq A vitaminiga boy."),
            Q("Kalsiy qaysi mahsulotlarda ko‘p?", "Sut va pishloqda", ["Konfet va shokoladda", "Gazli ichimlikda", "Chipsda"],
              x="Sut mahsulotlaridagi kalsiy suyak va tishlarni mustahkamlaydi."),
            Q("Qaysi taom sog‘lom nonushta bo‘ladi?", "Bo‘tqa, sut va meva", ["Chips va gazli suv", "Faqat konfet", "Shirin gazak va kola"],
              x="Bo‘tqa energiya, sut kalsiy, meva vitamin beradi."),
            Q("Chanqaganda qaysi ichimlik eng foydali?", "Toza suv", ["Gazli shirin ichimlik", "Energetik ichimlik", "Juda shirin sharbat"],
              x="Toza suvda shakar yo‘q, u chanqoqni yaxshi qondiradi."),
            Q("Oqsillar organizmga nima uchun kerak?", "O‘sish uchun", ["Terini quritish uchun", "Uxlamaslik uchun", "Tishni yemirish uchun"],
              x="Oqsil — tana hujayralari uchun qurilish materiali."),
            TF("Vitaminlar faqat dorixonada bo‘ladi.", False, x="Vitaminlar meva, sabzavot, sut, go‘sht va boshqa mahsulotlarda bor."),
            TF("Nonushta qilmay maktabga borish foydali.", False, x="Nonushta dars uchun kerakli energiya beradi."),
            TF("Meva va sabzavotlarda vitaminlar ko‘p.", True, x="Shuning uchun ularni har kuni yeyish kerak."),
            ORDER(S, "Sut suyak va tishlarni mustahkamlaydi"),
            Q("A vitamini qaysi a’zo uchun ayniqsa foydali?", "Ko‘z", ["Quloq", "Tirnoq", "Soch"], d=2,
              x="A vitamini yaxshi ko‘rish uchun zarur."),
            Q("Suyak va tishlar uchun qaysi modda muhim?", "Kalsiy", ["Shakar", "Tuz", "Yog‘"], d=2,
              x="Kalsiy suyak va tishlarni mustahkam qiladi."),
            Q("D vitamini qachon terida hosil bo‘ladi?", "Quyosh nuri tushganda", ["Uxlaganda", "Suv ichganda", "Qorong‘ida"], d=2,
              x="Quyosh nuri ta’sirida terida D vitamini hosil bo‘ladi."),
            Q("Na’matak damlamasi nimaga boy?", "C vitaminiga", ["Yog‘ga", "Tuzga", "Shakarga"], d=2,
              x="Na’matak mevasi C vitaminiga juda boy."),
            Q("Chips va gazli ichimliklarni nima uchun kam iste’mol qilish kerak?", "Ularda tuz va shakar ko‘p", ["Ularda vitamin ko‘p", "Ular tishni mustahkamlaydi", "Ular o‘sishga yordam beradi"], d=2,
              x="Ortiqcha tuz va shakar yurak, tish va oshqozonga zarar."),
            Q("Qaysi mahsulot o‘simlik oqsiliga boy?", "Loviya", ["Qand", "Bodring", "Tarvuz"], d=2,
              x="Loviya, no‘xat, mosh — o‘simlik oqsiliga boy dukkaklilar."),
            Q("Yog‘lar organizmga nima uchun kerak?", "Energiya zaxirasi uchun", ["Ko‘z rangini o‘zgartirish uchun", "Suyakni eritish uchun", "Terini quritish uchun"], d=2,
              x="Yog‘lar organizmda energiya zaxirasi sifatida saqlanadi."),
            MATCH("Oziq moddani mahsulot bilan juftlang",
                  [("Oqsil", "go‘sht va tuxum"), ("Uglevod", "non va guruch"), ("Yog‘", "sariyog‘"), ("A vitamini", "sabzi"),
                   ("C vitamini", "limon"), ("Kalsiy", "sut va pishloq")], d=2,
                  x="Turli mahsulotlar turli oziq moddalarga boy."),
            Q("D vitamini yetishmasa, bolalarda qanday kasallik paydo bo‘ladi?", "Raxit", ["Gripp", "Angina", "Suvchechak"], d=3,
              x="Raxitda suyaklar yumshab, qiyshayishi mumkin."),
            Q("Sabzidagi A vitamini yog‘ bilan yaxshi o‘zlashadi. Qaysi salat foydaliroq?", "Sabzi va o‘simlik yog‘i", ["Sabzi va shakar", "Sabzi va tuz", "Sabzi va gazli suv"], d=3,
              x="A vitamini yog‘da eriydi, shuning uchun sabzi salatiga yog‘ qo‘shiladi."),
        ])

T.topic("safety", "🚦", L("Xavfsizlik qoidalari", "Safety rules", "Правила безопасности"),
        chapter=C4,
        theory="Xavfsizlik qoidalari hayotimizni asraydi.\n"
               "• Yo‘lda: yo‘lni faqat piyodalar o‘tish joyidan va svetoforning yashil chirog‘ida kesib o‘ting; avval chapga, yo‘l o‘rtasida o‘ngga qarang.\n"
               "• Suvda: kattalarsiz va notanish joyda cho‘milmang, ariq va kanallarda suzmang.\n"
               "• Olovda: gugurt va zajigalka bilan o‘ynamang. Yong‘in — 101, tez yordam — 103, gaz xizmati — 104.\n"
               "• Elektrda: ho‘l qo‘l bilan elektr asboblariga tegmang, rozetkaga narsa tiqmang, uzilgan simga yaqinlashmang.",
        items=[
            Q("Yo‘lni qayerdan kesib o‘tish kerak?", "Piyodalar o‘tish joyidan", ["Burilish joyidan", "Avtobus oldidan", "Istalgan joydan"],
              x="Piyodalar o‘tish joyida haydovchilar piyodalarni kutadi."),
            Q("Svetoforning qaysi chirog‘ida yo‘lni kesib o‘tish mumkin?", "Yashil", ["Qizil", "Sariq", "Chiroq o‘chganda"], e="🚦",
              x="Yashil chiroq — yurish mumkin, qizil — to‘xta."),
            Q("Svetoforning sariq chirog‘i nimani bildiradi?", "Diqqat, tayyorlan", ["Tez yugur", "Yo‘l bo‘sh", "O‘ynash mumkin"],
              x="Sariq chiroq chiroqlar almashayotganini bildiradi."),
            Q("Yong‘in bo‘lsa, qaysi raqamga qo‘ng‘iroq qilinadi?", "101", ["103", "104", "100"], e="🔥",
              x="101 — yong‘in xavfsizligi xizmati."),
            Q("Tez tibbiy yordam raqami qaysi?", "103", ["101", "104", "109"], e="🚑",
              x="Odam kasal bo‘lib qolsa yoki jarohatlansa, 103 ga qo‘ng‘iroq qilinadi."),
            Q("Qayerda cho‘milish mumkin?", "Maxsus joyda, kattalar bilan", ["Kanal va ariqda", "Notanish ko‘lda yolg‘iz", "Ko‘prik ustidan sakrab"],
              x="Maxsus jihozlangan joyda qutqaruvchilar kuzatib turadi."),
            Q("Nima uchun kanallarda cho‘milish xavfli?", "Suv oqimi kuchli", ["Suv juda shirin", "Suv juda iliq", "U yerda baliq ko‘p"],
              x="Kanal suvi tez oqadi va chuqur, qirg‘og‘i tik bo‘ladi."),
            Q("Ho‘l qo‘l bilan elektr asbobiga tegish nima uchun xavfli?", "Tok urishi mumkin", ["Qo‘l qurib qoladi", "Asbob tozalanadi", "Asbob tezroq ishlaydi"],
              x="Suv elektr tokini o‘tkazadi."),
            Q("Qaysi harakat xavfli?", "Rozetkaga mix tiqish", ["Chiroqni o‘chirish", "Qo‘lni yuvish", "Derazani ochish"],
              x="Rozetkaga metall narsa tiqilsa, tok uradi."),
            Q("Velosipedda yurganda boshni nima himoya qiladi?", "Dubulg‘a", ["Qalpoq", "Ko‘zoynak", "Sharf"], e="🚲",
              x="Dubulg‘a yiqilganda boshni zarbadan saqlaydi."),
            TF("Gugurt bilan o‘ynash xavfli.", True, x="Gugurtdan yong‘in chiqishi mumkin."),
            TF("Yo‘lda telefonga qarab ketish xavfli.", True, x="Telefonga qaragan odam mashinani ko‘rmay qolishi mumkin."),
            ORDER(S, "Yo‘lni yashil chiroqda kesib o‘ting"),
            Q("Yo‘lni kesib o‘tishdan oldin avval qaysi tomonga qarash kerak?", "Chapga", ["O‘ngga", "Orqaga", "Osmonga"], d=2,
              x="Bizda mashinalar yo‘lning o‘ng tomonidan yuradi, eng yaqin mashinalar chap tomondan keladi."),
            Q("Uyda gaz hidi kelsa, qaysi raqamga qo‘ng‘iroq qilinadi?", "104", ["101", "103", "109"], d=2,
              x="104 — gaz avariya xizmati."),
            Q("Uyda gaz hidi kelsa, avvalo nima qilish kerak?", "Derazani ochib, kattalarga aytish", ["Gugurt yoqib ko‘rish", "Chiroqni yoqish", "Eshikni berkitib o‘tirish"], d=2,
              x="Gaz hidi kelganda olov yoqish va elektr tugmalarini bosish xavfli."),
            Q("Xonani tutun bosganda qanday chiqish kerak?", "Engashib, burunni ho‘l mato bilan to‘sib", ["Tik turib yugurib", "Liftga chiqib", "Shkafga yashirinib"], d=2,
              x="Tutun yuqoriga ko‘tariladi, pastda havo tozaroq bo‘ladi."),
            Q("Yong‘in paytida nima qilish mumkin emas?", "Liftdan foydalanish", ["Zinadan tushish", "101 ga qo‘ng‘iroq qilish", "Kattalarga xabar berish"], d=2,
              x="Yong‘inda lift to‘xtab qolishi mumkin."),
            Q("Suvda cho‘kayotgan odamni ko‘rsangiz nima qilasiz?", "Baland ovozda kattalarni chaqiraman", ["O‘zim suvga sakrayman", "Ketib qolaman", "Rasmga olaman"], d=2,
              x="Bola o‘zi qutqarishga urinmasligi kerak, darhol kattalarni chaqiradi."),
            Q("Elektr uzatish simlari yaqinida nima qilish xavfli?", "Varrak uchirish", ["Kitob o‘qish", "Rasm chizish", "Suv ichish"], d=2,
              x="Varrak ipi simga tegsa, tok urishi mumkin."),
            TF("Momaqaldiroq paytida baland daraxt tagida turish xavfsiz.", False, d=2,
               x="Chaqmoq ko‘pincha baland daraxtlarga uriladi."),
            MATCH("Vaziyatni to‘g‘ri harakat bilan juftlang",
                  [("Yong‘in chiqdi", "101 ga qo‘ng‘iroq"), ("Odam hushidan ketdi", "103 ga qo‘ng‘iroq"), ("Gaz hidi keldi", "derazani ochish"),
                   ("Svetoforda qizil chiroq", "to‘xtab turish"), ("Uzilgan sim yotibdi", "yaqinlashmaslik"), ("Notanish ko‘l", "cho‘milmaslik")], d=2,
                  x="Xavfli vaziyatda to‘g‘ri harakat hayotni saqlaydi."),
            Q("Avtobusdan tushgach, yo‘lni qachon kesib o‘tish kerak?", "Avtobus ketgach", ["Darhol avtobus oldidan", "Darhol avtobus orqasidan", "Yugurib, istalgan payt"], d=3,
              x="Turgan avtobus yo‘lni to‘sib turadi, uning ortidan kelayotgan mashina ko‘rinmaydi."),
            Q("Kechqurun piyoda yurganda kiyimga nima taqish foydali?", "Nur qaytaruvchi belgi", ["Qora sharf", "Quloqchin", "Qalin shapka"], d=3,
              x="Nur qaytaruvchi belgi mashina chiroqlarida yaltirab, piyodani uzoqdan ko‘rsatadi."),
        ])

T.topic("protect", "🌳", L("Tabiatni muhofaza qilish", "Protecting nature", "Охрана природы"),
        chapter=C4,
        theory="Tabiatni muhofaza qilish — havo, suv, tuproq, o‘simlik va hayvonlarni asrash.\n"
               "• Qo‘riqxona — tabiat qat’iy muhofaza qilinadigan hudud. O‘zbekistonda Chotqol, Zomin, Hisor, Zarafshon qo‘riqxonalari bor.\n"
               "• Qizil kitobga kamyob va yo‘qolib borayotgan o‘simlik va hayvonlar kiritiladi.\n"
               "• Chiqindilarni saralash (qog‘oz, plastik, shisha alohida) ularni qayta ishlashga yordam beradi.\n"
               "Har kim tabiatga yordam bera oladi: daraxt ekish, suv va elektrni tejash, gullarni uzmaslik, qushlarga yem berish.",
        items=[
            Q("Tabiat qat’iy muhofaza qilinadigan, ov va daraxt kesish taqiqlangan hudud?", "Qo‘riqxona", ["Istirohat bog‘i", "Dala", "Bozor"],
              x="Qo‘riqxonada o‘simlik va hayvonlar insondan himoyalanadi."),
            Q("Qaysi odat suvni tejaydi?", "Tish yuvganda jo‘mrakni yopish", ["Jo‘mrakni ochiq qoldirish", "Hovlini shlang bilan yuvish", "Suvni ariqqa oqizib qo‘yish"],
              x="Tish yuvayotganda jo‘mrakni yopsak, ko‘p suv tejaladi."),
            Q("Elektrni tejash uchun nima qilamiz?", "Xonadan chiqqanda chiroqni o‘chiramiz", ["Chiroqni kun bo‘yi yoqamiz", "Televizorni o‘chirmaymiz", "Muzlatgichni ochiq qoldiramiz"],
              x="Keraksiz yonib turgan chiroq elektrni isrof qiladi."),
            Q("Do‘konga borganda plastik paket o‘rniga nima olgan ma’qul?", "Matodan tikilgan sumka", ["Yana ko‘proq paket", "Bir martalik idish", "Ko‘pikli quti"],
              x="Mato sumkadan ko‘p marta foydalanish mumkin."),
            Q("Nima uchun daraxtlarni kesmaslik kerak?", "Ular havoni tozalaydi", ["Ular soya bermaydi", "Ular shovqin qiladi", "Ular suvni ifloslaydi"],
              x="Daraxtlar havoni tozalaydi, tuproqni yemirilishdan saqlaydi."),
            Q("Qaysi harakat tabiatga zarar?", "Gulxanni o‘chirmay ketish", ["Daraxt ekish", "Qushlarga uy yasash", "Chiqindini yig‘ish"],
              x="O‘chirilmagan gulxandan o‘rmon va dasht yong‘ini chiqishi mumkin."),
            Q("Qayta ishlash uchun plastik butilkani qaysi qutiga tashlaymiz?", "Plastik uchun qutiga", ["Qog‘oz uchun qutiga", "Ariqqa", "Gulxanga"],
              x="Saralangan plastik zavodda qayta ishlanadi."),
            Q("Maktab hovlisiga qushlar uchun nima osish mumkin?", "Qushxona", ["Plastik paket", "Tuzoq", "Oyna parchasi"],
              x="Qushxona — qushlar uchun yasalgan sun’iy uya."),
            TF("Qo‘riqxonada daraxt kesish taqiqlanadi.", True, x="Qo‘riqxonada tabiat o‘z holicha saqlanadi."),
            TF("Bir kishi tabiatga hech qanday yordam bera olmaydi.", False, x="Har bir ekilgan daraxt, tejalgan suv tabiatga yordam."),
            TF("Hayvonlarga ozor berish yaxshi odat.", False, x="Hayvonlarga mehribon bo‘lish kerak."),
            ORDER(S, "Daraxt ekish tabiatga foyda keltiradi"),
            Q("Qaysi chiqindini qayta ishlab, yangi qog‘oz olish mumkin?", "Eski gazeta", ["Oziq-ovqat qoldig‘i", "Batareyka", "Singan oyna"], d=2,
              x="Makulatura — eski qog‘oz, undan yangi qog‘oz tayyorlanadi."),
            Q("Ishlatilgan batareykalarni qayerga tashlash kerak?", "Maxsus yig‘ish qutisiga", ["Ariqqa", "Oddiy axlatga", "Tuproqqa ko‘mib"], d=2,
              x="Batareyka ichidagi moddalar tuproq va suvni zaharlaydi."),
            Q("Bahorda gullagan lolalarni nima uchun uzmaslik kerak?", "Ular kamayib ketadi", ["Ular juda og‘ir", "Ular tikanli", "Ular qishda gullaydi"], d=2,
              x="Uzilgan lola urug‘ bermaydi, yovvoyi lolalar yildan-yilga kamayadi."),
            Q("Chiqindilarni turlarga ajratib yig‘ish nima deyiladi?", "Saralash", ["Yoqish", "Ko‘mish", "Tashlab yuborish"], d=2,
              x="Saralangan chiqindini qayta ishlash oson."),
            Q("Nima uchun chiqindini yoqish zararli?", "Havo zaharli tutunga to‘ladi", ["Chiqindi ko‘payadi", "Tuproq unumdor bo‘ladi", "Havo tozalanadi"], d=2,
              x="Plastik va boshqa chiqindilar yonganda zaharli tutun chiqadi."),
            TF("Shisha idishni qayta ishlab, yangi shisha olish mumkin.", True, d=2, x="Shisha eritilib, qayta ishlatiladi."),
            MATCH("Chiqindini saralash qutisi bilan juftlang",
                  [("Eski gazeta", "qog‘oz"), ("Suv butilkasi", "plastik"), ("Shisha banka", "shisha"), ("Konserva qutisi", "metall"),
                   ("Olma po‘chog‘i", "oziq-ovqat qoldig‘i")], d=2,
                  x="Har bir chiqindi o‘z qutisiga tashlanadi."),
            Q("Chotqol qo‘riqxonasi qaysi viloyatda?", "Toshkent viloyatida", ["Xorazm viloyatida", "Buxoro viloyatida", "Navoiy viloyatida"], d=3,
              x="Chotqol qo‘riqxonasi Toshkent viloyatining tog‘li qismida joylashgan."),
            Q("Zomin qo‘riqxonasi qaysi viloyatda?", "Jizzax viloyatida", ["Xorazm viloyatida", "Andijon viloyatida", "Qoraqalpog‘istonda"], d=3,
              x="Zomin qo‘riqxonasi Jizzax viloyatidagi Turkiston tizmasida joylashgan."),
            Q("Butunjahon atrof-muhitni muhofaza qilish kuni qachon nishonlanadi?", "5-iyunda", ["1-yanvarda", "8-martda", "1-sentabrda"], d=3,
              x="Har yili 5-iyunda butun dunyoda tabiatni asrashga chaqiruvchi tadbirlar o‘tkaziladi."),
            Q("Faqat G‘arbiy Tyan-Shan tog‘larida yashaydigan kamyob hayvon qaysi?", "Menzbir sug‘uri", ["Uy sichqoni", "Chumchuq", "Kaptar"], d=3,
              x="Menzbir sug‘uri O‘zbekiston Qizil kitobiga kiritilgan."),
        ])

T.test("test4", L("4-nazorat ishi", "Test 4", "Контрольная работа 4"),
       ["senses_hygiene", "nutrition", "safety", "protect"], chapter=C4)

T.test("final", L("Yillik takrorlash", "End-of-year review", "Итоговое повторение"),
       ["space", "globe_map", "continents", "directions", "zones", "rivers", "minerals", "matter",
        "habitats", "plant_repro", "digestion", "breathing_blood", "senses_hygiene", "nutrition", "safety", "protect"],
       chapter=C4, level=3)

T.write()
