"""Tabiiy fanlar (integratsiyalashgan kurs), 5-sinf: assets/data/school/science_g5.json + bank_science_g5.json.

Mavzular O‘zbekiston maktab dasturi ("Tabiiy fanlar", 5-sinf) yo‘nalishida: tabiatni o‘rganish usullari, modda va
uning holatlari, aralashmalar, fizik va kimyoviy hodisalar, kuch, energiya, yorug‘lik va tovush, magnit va elektr,
Yer va uning qobiqlari, Quyosh tizimi, hujayra, fotosintez, ekotizim va ekologiya.
Hamma qoida matnlari va savollar o‘zimizniki (darslikdan ko‘chirilmagan).
Qayta yaratish: python3 tool/content/school/science_g5.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from schoolkit import *  # noqa: E402,F403

T = Course("science", 5, L("Tabiiy fanlar", "Natural sciences", "Естественные науки"))

C1 = "1-chorak. Tabiatni o‘rganish va moddalar"
C2 = "2-chorak. Hodisalar, kuch va energiya"
C3 = "3-chorak. Magnit, elektr, Yer va koinot"
C4 = "4-chorak. Tirik organizmlar va ekologiya"

S = "So‘zlardan gap tuzing"

# ============================================================ 1-chorak
T.topic("methods", "🔍", L("Tabiatni o‘rganish usullari", "How we study nature", "Методы изучения природы"),
        chapter=C1,
        theory="Tabiat uch asosiy usulda o‘rganiladi:\n"
               "• Kuzatish — hodisani o‘zgartirmasdan diqqat bilan kuzatib borish (masalan, qushlarning uchib ketishini).\n"
               "• Tajriba — hodisani maxsus sharoitda o‘zimiz hosil qilib, tekshirish.\n"
               "• O‘lchash — kattalikni asbob yordamida aniqlash: uzunlik — chizg‘ich (m, sm), massa — tarozi (kg, g), harorat — termometr (°C), suyuqlik hajmi — menzurka (ml), vaqt — sekundomer (s).\n"
               "Natijalar birligi bilan jadvalga yoziladi va xulosa chiqariladi.",
        items=[
            Q("Massani qaysi asbob bilan o‘lchaymiz?", "Tarozi", ["Chizg‘ich", "Termometr", "Menzurka", "Sekundomer"], e="⚖️",
              x="Tarozi jismning massasini gramm va kilogrammlarda ko‘rsatadi."),
            Q("Haroratni qaysi asbob o‘lchaydi?", "Termometr", ["Tarozi", "Menzurka", "Chizg‘ich"],
              x="Termometr haroratni gradus Selsiyda ko‘rsatadi."),
            Q("Suyuqlik hajmini qaysi asbob bilan o‘lchaymiz?", "Menzurka", ["Tarozi", "Chizg‘ich", "Sekundomer"],
              x="Menzurka — millilitr bo‘laklari chizilgan idish."),
            Q("Yugurish vaqtini qaysi asbob bilan o‘lchaymiz?", "Sekundomer", ["Termometr", "Menzurka", "Tarozi"], e="⏱️",
              x="Sekundomer vaqtni sekundlarda aniq o‘lchaydi."),
            Q("Uzunlikni qaysi asbob bilan o‘lchaymiz?", "Chizg‘ich", ["Termometr", "Tarozi", "Sekundomer"], e="📏",
              x="Chizg‘ich, ruletka, santimetr lenta uzunlikni o‘lchaydi."),
            Q("Qushlarning kuzda uchib ketishini kuzatib borish qaysi usul?", "Kuzatish", ["Tajriba", "O‘lchash", "Chizish"],
              x="Biz hodisaga aralashmaymiz, faqat kuzatamiz."),
            Q("1 metrda necha santimetr bor?", "100", ["10", "1000", "60"], x="1 m = 100 sm."),
            Q("1 kilogrammda necha gramm bor?", "1000", ["100", "10", "60"], x="1 kg = 1000 g."),
            Q("1 minutda necha sekund bor?", "60", ["100", "10", "30"], x="1 minut = 60 sekund."),
            Q("Juda mayda narsalarni ko‘rish uchun qaysi asbob kerak?", "Mikroskop", ["Tarozi", "Termometr", "Sekundomer"], e="🔬",
              x="Mikroskop mayda narsalarni ko‘p marta kattalashtiradi."),
            TF("Termometr haroratni gradusda ko‘rsatadi.", True, x="Harorat birligi — gradus Selsiy (°C)."),
            TF("Menzurka bilan massani o‘lchaymiz.", False, x="Menzurka suyuqlik hajmini, tarozi esa massani o‘lchaydi."),
            TF("Lupa narsalarni kattalashtirib ko‘rsatadi.", True, x="Lupa — kattalashtiruvchi shisha."),
            MATCH("Asbobni u o‘lchaydigan kattalik bilan juftlang",
                  [("Chizg‘ich", "uzunlik"), ("Tarozi", "massa"), ("Termometr", "harorat"), ("Menzurka", "suyuqlik hajmi"),
                   ("Sekundomer", "vaqt"), ("Dinamometr", "kuch")]),
            ORDER(S, "Termometr havo haroratini o‘lchaydi"),
            Q("Urug‘larni turli haroratda undirib ko‘rish qaysi usul?", "Tajriba", ["Kuzatish", "O‘lchash", "Tasavvur qilish"], d=2,
              x="Sharoitni o‘zimiz yaratib, natijani tekshiramiz — bu tajriba."),
            Q("Tajriba kuzatishdan nimasi bilan farq qiladi?", "Sharoitni o‘zimiz yaratamiz",
              ["Asbob umuman kerak emas", "Faqat tabiatda o‘tkaziladi", "Natija yozilmaydi"], d=2,
              x="Tajribada hodisani maxsus sharoitda o‘zimiz hosil qilamiz."),
            Q("1 litrda necha millilitr bor?", "1000", ["100", "10", "500"], d=2, x="1 l = 1000 ml."),
            Q("Uzoqdagi yulduzlarni kuzatish uchun qaysi asbob kerak?", "Teleskop", ["Mikroskop", "Menzurka", "Tarozi"], d=2, e="🔭",
              x="Teleskop uzoqdagi osmon jismlarini yaqinlashtirib ko‘rsatadi."),
            Q("O‘lchash natijasini qanday yozgan ma’qul?", "Jadvalga, birligi bilan",
              ["Faqat eslab qolish", "Birligisiz raqam", "Hech yozmaslik"], d=2,
              x="Birligi yozilmagan raqam tushunarsiz bo‘ladi: 5 nima — metrmi, grammmi?"),
            Q("Tajriba vaqtida nima qilish mumkin EMAS?", "Moddalarni tatib ko‘rish",
              ["Ustoz ko‘rsatmasiga amal qilish", "Ish joyini toza tutish", "Asboblarni ehtiyot qilish"], d=2,
              x="Noma’lum moddalarni tatib yoki hidlab ko‘rish xavfli."),
            MATCH("Kattalikni o‘lchov birligi bilan juftlang",
                  [("Uzunlik", "metr"), ("Massa", "kilogramm"), ("Vaqt", "sekund"), ("Harorat", "gradus Selsiy"),
                   ("Hajm", "litr")], d=2),
            Q("Tadqiqot bosqichlarining to‘g‘ri tartibi qaysi?", "Savol → faraz → tajriba → xulosa",
              ["Xulosa → tajriba → savol → faraz", "Tajriba → savol → xulosa → faraz", "Faraz → xulosa → savol → tajriba"], d=3,
              x="Avval savol qo‘yiladi, faraz qilinadi, tajribada tekshiriladi va xulosa chiqariladi."),
            Q("Menzurkada suv 50 ml edi, tosh solingach 70 ml bo‘ldi. Toshning hajmi qancha?", "20 ml",
              ["70 ml", "50 ml", "120 ml"], d=3, x="Tosh hajmi = 70 − 50 = 20 ml."),
            Q("Tarozi 2 kg 300 g ni ko‘rsatdi. Bu necha gramm?", "2300 g", ["230 g", "23 000 g", "2003 g"], d=3,
              x="2 kg = 2000 g, 2000 + 300 = 2300 g."),
        ])

T.topic("matter", "⚗️", L("Jism va modda. Moddaning holatlari", "Objects and substances. States of matter", "Тела и вещества. Агрегатные состояния"),
        chapter=C1,
        theory="Jism — atrofimizdagi har qanday narsa: qalam, stakan, tomchi. Modda — jism nimadan tuzilgani: yog‘och, shisha, suv, temir.\n"
               "Bir moddadan turli jismlar yasash mumkin (shishadan stakan va deraza oynasi), bir xil jism turli moddalardan bo‘lishi mumkin (temir yoki yog‘och qoshiq).\n"
               "Modda uch holatda bo‘ladi:\n"
               "• qattiq — shakli va hajmi saqlanadi; suyuq — hajmi saqlanadi, shakli idishga moslashadi; gaz — butun idishni to‘ldiradi.\n"
               "Holat o‘zgarishlari: erish, qotish, bug‘lanish, kondensatsiya (bug‘ning suyuqlikka aylanishi).",
        items=[
            Q("Qaysi biri jism?", "Qalam", ["Yog‘och", "Temir", "Shisha"],
              x="Qalam — jism, u yog‘och va grafitdan yasalgan."),
            Q("Qaysi biri modda?", "Temir", ["Mix", "Qoshiq", "Kalit"], x="Temir — modda, mix, qoshiq va kalit esa jismlar."),
            Q("Stakan qaysi moddadan yasalishi mumkin?", "Shishadan", ["Suvdan", "Havodan", "Bug‘dan"],
              x="Stakan shisha, plastmassa yoki metalldan yasaladi."),
            Q("Qaysi modda odatdagi sharoitda suyuq?", "Suv", ["Temir", "Tosh", "Kislorod"],
              x="Xona haroratida suv suyuq holatda bo‘ladi."),
            Q("Qaysi modda odatdagi sharoitda gaz holatida?", "Kislorod", ["Suv", "Mis", "Yog‘och"],
              x="Kislorod — havo tarkibidagi gaz."),
            Q("Muzning suvga aylanishi nima deyiladi?", "Erish", ["Qotish", "Bug‘lanish", "Kondensatsiya"],
              x="Qattiq moddaning suyuqlikka aylanishi — erish."),
            Q("Suvning bug‘ga aylanishi nima deyiladi?", "Bug‘lanish", ["Erish", "Qotish", "Kondensatsiya"],
              x="Suyuqlikning gazga aylanishi — bug‘lanish."),
            Q("Tabiatda uch holatda ham uchraydigan modda qaysi?", "Suv", ["Temir", "Shisha", "Yog‘och"],
              x="Suv muz (qattiq), suv (suyuq) va bug‘ (gaz) holatida uchraydi."),
            TF("Bir moddadan turli jismlar yasash mumkin.", True, x="Masalan, yog‘ochdan stol, stul va qalam yasaladi."),
            TF("Suv faqat suyuq holatda bo‘ladi.", False, x="Suv qattiq (muz) va gaz (bug‘) holatida ham bo‘ladi."),
            TF("Qattiq jismlarning shakli ham, hajmi ham saqlanadi.", True, x="Masalan, tosh qaysi idishga solinsa ham shaklini saqlaydi."),
            MATCH("Jismni u yasalgan modda bilan juftlang",
                  [("Mix", "temir"), ("Stakan", "shisha"), ("Daftar", "qog‘oz"), ("Elektr simi", "mis"),
                   ("Muz parchasi", "suv"), ("Shar", "rezina")]),
            ORDER(S, "Muz isitilganda suvga aylanadi"),
            Q("Qattiq jism qanday xususiyatga ega?", "Shakli va hajmi saqlanadi",
              ["Idish shaklini oladi", "Butun idishni to‘ldiradi", "Oqib ketadi"], d=2,
              x="Qattiq jismda zarrachalar o‘z joyida mahkam turadi."),
            Q("Suyuqlik qanday xususiyatga ega?", "Idish shaklini oladi",
              ["Shakli o‘zgarmaydi", "Butun xonani to‘ldiradi", "Bo‘laklarga sinadi"], d=2,
              x="Suyuqlik oquvchan, u qaysi idishga quyilsa, o‘sha shaklni oladi."),
            Q("Gaz qanday xususiyatga ega?", "Butun idishni to‘ldiradi",
              ["Shakli saqlanadi", "Hajmi o‘zgarmaydi", "Qo‘lda ushlab bo‘ladi"], d=2,
              x="Gaz o‘ziga berilgan butun hajmni egallaydi."),
            Q("Suyuq moddaning qattiq holga o‘tishi nima deyiladi?", "Qotish", ["Erish", "Bug‘lanish", "Qaynash"], d=2,
              x="Masalan, suv muzlaganda qotadi."),
            Q("Qaysi guruhda faqat moddalar bor?", "Shakar, tuz, suv",
              ["Qoshiq, tuz, suv", "Stakan, mix, qalam", "Shakar, kitob, stol"], d=2,
              x="Shakar, tuz va suv — moddalar, qoshiq, kitob, stol — jismlar."),
            Q("Qaysi guruhda faqat jismlar bor?", "Kitob, qoshiq, to‘p",
              ["Kitob, temir, suv", "Qog‘oz, shisha, rezina", "Mis, oltin, kumush"], d=2,
              x="Kitob, qoshiq va to‘p — jismlar."),
            Q("Moddaning xossalariga nimalar kiradi?", "Rangi, hidi, qattiqligi",
              ["Narxi va egasi", "Sotilgan joyi", "Nomining uzunligi"], d=2,
              x="Rang, hid, qattiqlik, eruvchanlik — modda xossalari."),
            Q("Ko‘lmak quyoshli kunda nima uchun yo‘qolib qoladi?", "Suv bug‘lanadi",
              ["Suv muzlaydi", "Suv kondensatsiyalanadi", "Suv yonib ketadi"], d=2,
              x="Quyosh issiqligida suv bug‘ga aylanib, havoga ko‘tariladi."),
            Q("Sham yonganda mum eriydi. Sovigach mum bilan nima bo‘ladi?", "Qotadi",
              ["Bug‘lanadi", "Gazga aylanadi", "Yo‘qolib ketadi"], d=2,
              x="Erigan mum sovib, yana qattiq holga o‘tadi."),
            TF("Gaz o‘ziga berilgan butun hajmni egallaydi.", True, d=2, x="Shuning uchun atir hidi butun xonaga tarqaladi."),
            MATCH("Holat o‘zgarishini izohi bilan juftlang",
                  [("Erish", "qattiqdan suyuqqa o‘tish"), ("Qotish", "suyuqdan qattiqqa o‘tish"),
                   ("Bug‘lanish", "suyuqdan gazga o‘tish"), ("Kondensatsiya", "gazdan suyuqqa o‘tish"),
                   ("Qaynash", "butun hajmda pufakchalar bilan bug‘lanish")], d=3),
            Q("Sovuq oyna yuzasida suv tomchilari paydo bo‘ldi. Bu qanday hodisa?", "Kondensatsiya",
              ["Erish", "Qotish", "Yonish"], d=3, x="Havodagi suv bug‘i sovuq oynaga tegib, suyuqlikka aylandi."),
        ])

T.topic("particles", "⚛️", L("Moddalarning tuzilishi. Diffuziya", "Structure of matter. Diffusion", "Строение вещества. Диффузия"),
        chapter=C1,
        theory="Barcha moddalar ko‘zga ko‘rinmaydigan juda mayda zarrachalardan — molekulalardan tuzilgan.\n"
               "• Zarrachalar orasida bo‘shliq bor va ular to‘xtovsiz harakatlanadi. Harorat ko‘tarilsa, tezroq harakatlanadi.\n"
               "• Qattiq jismda zarrachalar zich joylashgan, suyuqlikda erkinroq, gazda esa bir-biridan uzoq.\n"
               "Diffuziya — bir modda zarrachalarining boshqa modda zarrachalari orasiga o‘z-o‘zidan kirib borishi.\n"
               "Masalan, atir hidi butun xonaga tarqaladi. Diffuziya gazlarda tez, suyuqliklarda sekinroq, qattiq jismlarda juda sekin boradi.",
        items=[
            Q("Moddalar nimadan tuzilgan?", "Mayda zarrachalardan", ["Faqat suvdan", "Bo‘shliqdan", "Faqat havodan"],
              x="Har qanday modda juda mayda zarrachalar — molekulalardan tuzilgan."),
            Q("Atir hidining butun xonaga tarqalishi qanday hodisa?", "Diffuziya", ["Erish", "Qotish", "Kondensatsiya"],
              x="Atir zarrachalari havo zarrachalari orasiga o‘z-o‘zidan kirib boradi."),
            Q("Shakar qaysi suvda tezroq eriydi?", "Issiq suvda", ["Sovuq suvda", "Muzli suvda", "Farqi yo‘q"],
              x="Issiq suvda zarrachalar tezroq harakatlanadi."),
            Q("Qaysi holatda zarrachalar eng zich joylashgan?", "Qattiq", ["Suyuq", "Gaz", "Bug‘"],
              x="Qattiq jismda zarrachalar bir-biriga juda yaqin turadi."),
            Q("Diffuziyaga misolni toping", "Oshxonadan ovqat hidi kelishi",
              ["Suvning muzlashi", "Qorning erishi", "Shishaning sinishi"],
              x="Ovqat hidi zarrachalari havoda o‘z-o‘zidan tarqaladi."),
            Q("Zarrachalar harakati qachon tezlashadi?", "Qizdirilganda", ["Sovitilganda", "Muzlatilganda", "Qorong‘ida"],
              x="Harorat oshsa, zarrachalar tezroq harakatlanadi."),
            TF("Zarrachalar doimo harakatda bo‘ladi.", True, x="Zarrachalar hech qachon to‘xtamaydi."),
            TF("Harorat ko‘tarilsa, zarrachalar sekinlashadi.", False, x="Aksincha, qizdirilganda zarrachalar tezlashadi."),
            TF("Havo ham mayda zarrachalardan iborat.", True, x="Havo — turli gazlar zarrachalaridan iborat."),
            TF("Qattiq jismda zarrachalar bir-biriga juda yaqin joylashgan.", True,
               x="Shuning uchun qattiq jismni siqish qiyin."),
            ORDER(S, "Barcha moddalar mayda zarrachalardan tuzilgan"),
            Q("Diffuziya qaysi holatda eng tez boradi?", "Gazlarda", ["Suyuqliklarda", "Qattiq jismlarda", "Muzda"], d=2,
              x="Gazda zarrachalar erkin va tez harakatlanadi."),
            Q("Diffuziya qaysi holatda eng sekin boradi?", "Qattiq jismlarda", ["Gazlarda", "Suyuqliklarda", "Havoda"], d=2,
              x="Qattiq jismda zarrachalar zich joylashgan va kam harakatlanadi."),
            Q("Qaysi holatda zarrachalar bir-biridan eng uzoqda?", "Gaz", ["Qattiq", "Suyuq", "Muz"], d=2,
              x="Gaz zarrachalari orasida katta bo‘shliq bor."),
            Q("Molekulalarni oddiy ko‘z bilan ko‘rish mumkinmi?", "Yo‘q, ular juda mayda",
              ["Ha, osongina", "Faqat kechasi", "Faqat lupa bilan"], d=2,
              x="Molekulalar shunchalik maydaki, ularni lupa bilan ham ko‘rib bo‘lmaydi."),
            Q("Choyga solingan shakar aralashtirilmasa ham choyni shirin qiladi. Sababi nima?", "Diffuziya",
              ["Muzlash", "Yonish", "Ishqalanish"], d=2,
              x="Shakar zarrachalari suv zarrachalari orasiga o‘z-o‘zidan tarqaladi."),
            Q("Suvga tomizilgan siyoh aralashtirilmasa ham suvni bo‘yaydi. Bu nima?", "Diffuziya",
              ["Qotish", "Kondensatsiya", "Zanglash"], d=2,
              x="Siyoh zarrachalari suv zarrachalari orasiga kirib boradi."),
            Q("Qaysi hodisa diffuziya EMAS?", "Toshning suvga cho‘kishi",
              ["Atir hidining tarqalishi", "Siyohning suvda tarqalishi", "Choyda shakarning tarqalishi"], d=2,
              x="Tosh cho‘kishi — og‘irlik kuchi ta’siri, diffuziya emas."),
            TF("Zarrachalar orasida bo‘shliq yo‘q.", False, d=2, x="Zarrachalar orasida bo‘shliq bor, shuning uchun gazni siqish mumkin."),
            MATCH("Tushunchani izohi bilan juftlang",
                  [("Molekula", "moddaning mayda zarrachasi"), ("Diffuziya", "zarrachalarning o‘z-o‘zidan aralashishi"),
                   ("Qattiq jism", "zarrachalar zich joylashgan"), ("Gaz", "zarrachalar bir-biridan uzoq"),
                   ("Harorat ortishi", "zarrachalar tezlashadi")], d=2),
            Q("Nima uchun gazni siqish oson?", "Zarrachalari orasida bo‘shliq katta",
              ["Zarrachalari yo‘q", "U juda og‘ir", "U qattiq"], d=3,
              x="Gaz zarrachalari bir-biridan uzoq, ularni yaqinlashtirish oson."),
            Q("Gul hidi qaysi havoda tezroq tarqaladi?", "Issiq havoda", ["Sovuq havoda", "Farqi yo‘q", "Faqat kechasi"], d=3,
              x="Issiqda zarrachalar tezroq harakatlanadi, diffuziya tezlashadi."),
            Q("Temir sharcha qizdirilganda nima bo‘ladi?", "Biroz kengayadi", ["Kichrayadi", "Darhol oqib ketadi", "Rangsiz bo‘ladi"], d=3,
              x="Qizdirilganda zarrachalar orasidagi masofa ortadi — jism kengayadi."),
            TF("Molekulalar yanada mayda zarrachalar — atomlardan tuzilgan.", True, d=3,
               x="Masalan, suv molekulasi vodorod va kislorod atomlaridan iborat."),
            TF("Diffuziya qattiq jismlarda ham boradi, lekin juda sekin.", True, d=3,
               x="Qattiq jismlarda zarrachalar kam harakatlanadi, shuning uchun juda sekin boradi."),
        ])

T.topic("mixtures", "☕", L("Toza moddalar va aralashmalar", "Pure substances and mixtures", "Чистые вещества и смеси"),
        chapter=C1,
        theory="Toza modda bir xil zarrachalardan iborat (distillangan suv, shakar). Aralashma — bir necha moddaning qo‘shilmasi (havo, loyqa suv, tuzli suv).\n"
               "Aralashmalarni ajratish usullari:\n"
               "• tindirish (cho‘ktirish) — og‘ir zarrachalar idish tagiga cho‘kadi;\n"
               "• filtrlash — suyuqlik filtrdan o‘tadi, qum filtrda qoladi;\n"
               "• bug‘latish — tuzli suvdan suv bug‘lanadi, tuz qoladi;\n"
               "• magnit bilan — temir qipiqlari magnitga tortiladi.",
        items=[
            Q("Qumli suvni qanday ajratish mumkin?", "Filtrlash", ["Magnit bilan", "Muzlatib", "Aralashtirib"],
              x="Suv filtrdan o‘tadi, qum esa filtrda qoladi."),
            Q("Tuzli suvdan tuzni qanday ajratib olamiz?", "Bug‘latish", ["Filtrlash", "Magnit bilan", "Elash"],
              x="Suv bug‘lanib ketadi, idishda tuz qoladi."),
            Q("Temir qipiqlarini qumdan qanday ajratamiz?", "Magnit bilan", ["Bug‘latib", "Filtrlab", "Suvda eritib"],
              x="Temir magnitga tortiladi, qum esa tortilmaydi."),
            Q("Loyqa suv tinsa, tuproq zarrachalari qayerda to‘planadi?", "Idish tagida",
              ["Suv yuzasida", "Havoda", "Idish qopqog‘ida"], x="Og‘ir zarrachalar idish tagiga cho‘kadi."),
            Q("Filtr sifatida nimadan foydalanish mumkin?", "Filtr qog‘ozi", ["Temir plastinka", "Shisha bo‘lagi", "Plastik qopqoq"],
              x="Filtr qog‘ozida suv o‘tadigan juda mayda teshikchalar bor."),
            Q("Guruchni mayda toshlardan qanday tozalaymiz?", "Qo‘lda terib", ["Bug‘latib", "Magnit bilan", "Eritib"],
              x="Toshlar ko‘zga ko‘rinadi, ularni terib olish mumkin."),
            Q("Tuproq aralashgan suv qanday ataladi?", "Loyqa suv", ["Distillangan suv", "Muz", "Bug‘"],
              x="Loyqa suv — suv va tuproq aralashmasi."),
            TF("Magnit temir qipiqlarini o‘ziga tortadi.", True, x="Temir magnitga tortiladigan modda."),
            TF("Tindirishda og‘ir zarrachalar idish tagiga cho‘kadi.", True, x="Bu usul loyqa suvni tozalashda qo‘llanadi."),
            TF("Filtrlash bilan qumni suvdan ajratish mumkin.", True, x="Qum zarrachalari filtrdan o‘ta olmaydi."),
            TF("Salat — bir nechta sabzavotdan tayyorlangan aralashma.", True, x="Salatdagi har bir sabzavotni ajratib ko‘rish mumkin."),
            Q("Qaysi biri aralashma?", "Havo", ["Distillangan suv", "Toza shakar", "Toza oltin"], d=2,
              x="Havo — azot, kislorod va boshqa gazlar aralashmasi."),
            Q("Undan yirik zarrachalarni ajratish uchun nima qilinadi?", "Elakdan o‘tkaziladi",
              ["Magnit tutiladi", "Bug‘latiladi", "Muzlatiladi"], d=2,
              x="Mayda un elakdan o‘tadi, yirik zarrachalar elakda qoladi."),
            Q("Qaysi biri toza modda?", "Distillangan suv", ["Dengiz suvi", "Havo", "Tuproq"], d=2,
              x="Distillangan suvda boshqa moddalar deyarli yo‘q."),
            Q("Choy damlanganda choy barglari suzgichda qoladi. Bu qaysi usulga o‘xshaydi?", "Filtrlash",
              ["Bug‘latish", "Magnit bilan ajratish", "Tindirish"], d=2,
              x="Suyuqlik suzgichdan o‘tadi, barglar esa ushlanib qoladi."),
            Q("Dengiz suvidan osh tuzi qanday olinadi?", "Suvni bug‘latib", ["Magnit bilan", "Elab", "Filtrlab"], d=2,
              x="Quyosh issiqligida suv bug‘lanadi, tuz qoladi."),
            Q("Qaysi aralashmada moddalarni ko‘z bilan ajratib ko‘rish mumkin?", "Qum va shag‘al",
              ["Tuzli suv", "Shakarli suv", "Havo"], d=2,
              x="Qum va shag‘al donachalari ko‘zga ko‘rinadi, eritmada esa ko‘rinmaydi."),
            Q("Qaysi biri aralashma EMAS?", "Toza shakar", ["Salat", "Loyqa suv", "Havo"], d=2,
              x="Toza shakar — bitta modda."),
            Q("Shakarli suvdan shakarni qanday ajratish mumkin?", "Bug‘latish", ["Filtrlash", "Magnit bilan", "Elash"], d=2,
              x="Erigan shakar filtrdan o‘tib ketadi, bug‘latilganda esa idishda qoladi."),
            TF("Havo — toza modda.", False, d=2, x="Havo — azot, kislorod va boshqa gazlar aralashmasi."),
            MATCH("Aralashmani ajratish usuli bilan juftlang",
                  [("Qumli suv", "filtrlash"), ("Tuzli suv", "bug‘latish"), ("Temir qipig‘i va qum", "magnit"),
                   ("Un va kepak", "elash"), ("Loyqa suv", "tindirish")], d=2),
            ORDER(S, "Tuzli suv bug‘latilsa tuz qoladi", d=2),
            Q("Qum va tuz aralashmasini ajratish tartibi qanday?", "Eritish → filtrlash → bug‘latish",
              ["Bug‘latish → eritish → filtrlash", "Filtrlash → bug‘latish → eritish", "Magnit → bug‘latish → eritish"], d=3,
              x="Tuz suvda eriydi, qum filtrda qoladi, so‘ng suv bug‘latilib tuz olinadi."),
            TF("Erigan tuzni filtrlash bilan ajratib bo‘lmaydi.", True, d=3,
               x="Erigan tuz zarrachalari filtrdan suv bilan birga o‘tib ketadi."),
            TF("Aralashmadagi har bir modda o‘z xossalarini saqlaydi.", True, d=3,
               x="Masalan, temir qipig‘i qum bilan aralashganda ham magnitga tortiladi."),
        ])

T.test("test1", L("1-nazorat ishi", "Test 1", "Контрольная работа 1"),
       ["methods", "matter", "particles", "mixtures"], chapter=C1)

# ============================================================ 2-chorak
T.topic("phenomena", "🔥", L("Fizik va kimyoviy hodisalar", "Physical and chemical changes", "Физические и химические явления"),
        chapter=C2,
        theory="Tabiatdagi har qanday o‘zgarish hodisa deyiladi.\n"
               "• Fizik hodisada yangi modda hosil bo‘lmaydi, faqat shakli yoki holati o‘zgaradi: muzning erishi, suvning qaynashi, shishaning sinishi.\n"
               "• Kimyoviy hodisada yangi modda hosil bo‘ladi: yonish, temirning zanglashi, sutning achishi.\n"
               "Kimyoviy hodisa belgilari: rang o‘zgaradi, gaz ajraladi, hid paydo bo‘ladi, issiqlik yoki yorug‘lik chiqadi, cho‘kma tushadi.\n"
               "Fizik hodisalar turlari: mexanik, issiqlik, yorug‘lik, tovush, elektr va magnit hodisalari.",
        items=[
            Q("Qaysi biri fizik hodisa?", "Muzning erishi", ["Qog‘ozning yonishi", "Temirning zanglashi", "Sutning achishi"],
              x="Muz erib suvga aylanadi, lekin yangi modda hosil bo‘lmaydi."),
            Q("Qaysi biri kimyoviy hodisa?", "Yog‘ochning yonishi", ["Shishaning sinishi", "Suvning qaynashi", "Qorning erishi"],
              x="Yonishda kul, tutun va gazlar — yangi moddalar hosil bo‘ladi."),
            Q("Kimyoviy hodisada nima hosil bo‘ladi?", "Yangi modda", ["Faqat yangi shakl", "Hech narsa", "Faqat boshqa holat"],
              x="Kimyoviy hodisaning asosiy belgisi — yangi modda paydo bo‘lishi."),
            Q("Kamalak qanday hodisa?", "Yorug‘lik hodisasi", ["Tovush hodisasi", "Elektr hodisasi", "Kimyoviy hodisa"], e="🌈",
              x="Quyosh nuri yomg‘ir tomchilarida ranglarga ajraladi."),
            Q("Plastilindan shar yasash qanday hodisa?", "Fizik", ["Kimyoviy", "Elektr", "Yorug‘lik"],
              x="Plastilinning faqat shakli o‘zgaradi."),
            TF("Temirning zanglashi — kimyoviy hodisa.", True, x="Zang — temirdan hosil bo‘lgan yangi modda."),
            TF("Suvning qaynashi — kimyoviy hodisa.", False, x="Qaynashda suv bug‘ga aylanadi, lekin yangi modda hosil bo‘lmaydi."),
            TF("Qog‘ozni yirtish — fizik hodisa.", True, x="Yirtilgan qog‘oz ham qog‘ozligicha qoladi."),
            TF("Yonishda issiqlik va yorug‘lik ajraladi.", True, e="🔥", x="Gulxan yonganda issiq va yorug‘ bo‘ladi."),
            TF("Fizik hodisada yangi modda hosil bo‘ladi.", False, x="Fizik hodisada modda o‘zgarmaydi, faqat shakli yoki holati o‘zgaradi."),
            TF("Qorning erishi — fizik hodisa.", True, x="Qor erib, suvga aylanadi — modda o‘sha-o‘sha suv."),
            Q("Kimyoviy hodisa belgisi qaysi?", "Yangi gaz hosil bo‘lishi",
              ["Shaklning o‘zgarishi", "Bo‘laklarga bo‘linish", "Joyining o‘zgarishi"], d=2,
              x="Yangi gaz, rang, hid paydo bo‘lishi — kimyoviy hodisa belgilari."),
            Q("Kesilgan olma havoda qorayadi. Bu qanday hodisa?", "Kimyoviy", ["Fizik", "Tovush", "Magnit"], d=2,
              x="Olma havo bilan ta’sirlashib, yangi modda hosil bo‘ladi va rangi o‘zgaradi."),
            Q("Soda ustiga sirka quyilganda pufakchalar chiqadi. Bu qanday hodisa?", "Kimyoviy",
              ["Fizik", "Mexanik", "Tovush"], d=2, x="Yangi modda — karbonat angidrid gazi hosil bo‘ladi."),
            Q("Qaysi o‘zgarish kimyoviy?", "Sutning achishi", ["Sutning qaynashi", "Sutning to‘kilishi", "Sutning muzlashi"], d=2,
              x="Achigan sutda yangi modda hosil bo‘ladi, ta’mi va hidi o‘zgaradi."),
            Q("Qaysi o‘zgarish fizik?", "Shishaning sinishi", ["Go‘shtning pishishi", "Olmaning chirishi", "Gazning yonishi"], d=2,
              x="Singan shisha ham shishaligicha qoladi."),
            Q("Chaqmoq qanday hodisa?", "Elektr hodisasi", ["Kimyoviy hodisa", "Magnit hodisasi", "Mexanik hodisa"], d=2,
              x="Chaqmoq — bulutlar orasidagi kuchli elektr uchquni."),
            Q("Temir buyumlarni zanglashdan qanday saqlaymiz?", "Bo‘yab qo‘yamiz",
              ["Suvda saqlaymiz", "Tuzli suvga botiramiz", "Nam joyda qoldiramiz"], d=2,
              x="Bo‘yoq temirni suv va havodan to‘sadi."),
            Q("Nonning qizarib, kuyib qolishi qanday hodisa?", "Kimyoviy", ["Fizik", "Magnit", "Tovush"], d=2,
              x="Kuyganda rang va hid o‘zgaradi — yangi moddalar hosil bo‘ladi."),
            Q("Qaysi hodisa kimyoviy EMAS?", "Qorning erishi", ["Gugurtning yonishi", "Mixning zanglashi", "Ovqatning aynishi"], d=2,
              x="Qorning erishi — fizik hodisa."),
            TF("Barcha kimyoviy hodisalarda yangi modda hosil bo‘ladi.", True, d=2, x="Bu kimyoviy hodisaning asosiy belgisi."),
            MATCH("Hodisani fizik hodisa turi bilan juftlang",
                  [("Chaqmoq chaqishi", "elektr hodisasi"), ("Momaqaldiroq gumburlashi", "tovush hodisasi"),
                   ("Kamalak", "yorug‘lik hodisasi"), ("Muzning erishi", "issiqlik hodisasi"),
                   ("To‘pning dumalashi", "mexanik hodisa"), ("Kompas milining burilishi", "magnit hodisasi")], d=2),
            ORDER(S, "Yonishda yangi moddalar hosil bo‘ladi", d=2),
            Q("Sham yonganda qanday hodisalar sodir bo‘ladi?", "Ham fizik, ham kimyoviy",
              ["Faqat fizik", "Faqat kimyoviy", "Hech qanday"], d=3,
              x="Mumning erishi — fizik, pilikning yonishi — kimyoviy hodisa."),
            Q("Temir zanglashi uchun nima kerak?", "Namlik va havo", ["Faqat quyosh nuri", "Faqat sovuq", "Qorong‘ilik"], d=3,
              x="Quruq havoda yoki havosiz suvda temir juda sekin zanglaydi."),
        ])

T.topic("forces", "⚽", L("Kuch va uning turlari", "Forces", "Сила и её виды"),
        chapter=C2,
        theory="Kuch — jismlarning bir-biriga ta’siri. Kuch jismni harakatga keltiradi, to‘xtatadi, yo‘nalishini yoki shaklini o‘zgartiradi.\n"
               "Kuch nyutonlarda (N) o‘lchanadi, o‘lchash asbobi — dinamometr.\n"
               "• Og‘irlik kuchi — Yerning jismlarni o‘ziga tortishi, shu sababli narsalar pastga tushadi.\n"
               "• Ishqalanish kuchi — sirtlar bir-biriga tegib harakatlanganda paydo bo‘ladi va harakatga qarshilik qiladi.\n"
               "• Elastiklik kuchi — cho‘zilgan yoki siqilgan jism (prujina, rezina) avvalgi shakliga qaytishga intiladi.",
        items=[
            Q("Kuch qanday birlikda o‘lchanadi?", "Nyuton", ["Metr", "Kilogramm", "Sekund"], x="Kuch birligi — nyuton (N)."),
            Q("Kuchni qaysi asbob o‘lchaydi?", "Dinamometr", ["Termometr", "Menzurka", "Chizg‘ich"],
              x="Dinamometr kuchni nyutonlarda ko‘rsatadi."),
            Q("Qo‘ldan tushgan olma nima uchun pastga tushadi?", "Og‘irlik kuchi tufayli",
              ["Ishqalanish tufayli", "Shamol tufayli", "Magnit tufayli"], e="🍎",
              x="Yer barcha jismlarni o‘ziga tortadi."),
            Q("Cho‘zilgan rezina qo‘yib yuborilsa nima bo‘ladi?", "Avvalgi shakliga qaytadi",
              ["Uzayib ketaveradi", "Eriydi", "Qotib qoladi"], x="Rezinada elastiklik kuchi paydo bo‘ladi."),
            Q("Futbolchi to‘pni tepdi. Kuch to‘pga qanday ta’sir qildi?", "Harakatga keltirdi",
              ["Eritdi", "Rangini o‘zgartirdi", "Og‘irlashtirdi"], e="⚽", x="Kuch tinch turgan to‘pni harakatga keltirdi."),
            Q("Arava tortilsa, u nima qiladi?", "Harakatga keladi", ["Eriydi", "Yonadi", "Rangi o‘zgaradi"],
              x="Tortish kuchi aravani harakatga keltiradi."),
            Q("Chana tepalikdan o‘z-o‘zidan nima uchun sirpanib tushadi?", "Og‘irlik kuchi tortadi",
              ["Elastiklik kuchi itaradi", "Magnit tortadi", "Havo yo‘qoladi"], x="Og‘irlik kuchi chanani pastga tortadi."),
            Q("Qaysi biri kuch turi?", "Ishqalanish kuchi", ["Harorat", "Uzunlik", "Vaqt"],
              x="Ishqalanish, og‘irlik, elastiklik — kuch turlari."),
            TF("Kuch jismning shaklini o‘zgartira oladi.", True, x="Masalan, plastilinni qo‘l bilan siqsak, shakli o‘zgaradi."),
            TF("Yer barcha jismlarni o‘ziga tortadi.", True, x="Bu kuch og‘irlik kuchi deyiladi."),
            TF("Muz ustida ishqalanish kichik bo‘ladi.", True, x="Shuning uchun muzda sirpanib ketish oson."),
            Q("Muz ustida yurish nima uchun qiyin?", "Ishqalanish kam", ["Ishqalanish ko‘p", "Og‘irlik kuchi yo‘q", "Muz magnitlangan"], d=2,
              x="Silliq muzda oyoq kiyim yaxshi ilashmaydi."),
            Q("Qishda muzlagan yo‘lga nima uchun qum sepiladi?", "Ishqalanishni oshirish uchun",
              ["Yo‘lni isitish uchun", "Muzni oqartirish uchun", "Ishqalanishni kamaytirish uchun"], d=2,
              x="Qum yo‘lni g‘adir-budur qiladi, sirpanish kamayadi."),
            Q("Velosiped zanjiri nima uchun moylanadi?", "Ishqalanishni kamaytirish uchun",
              ["Ishqalanishni oshirish uchun", "Chiroyli bo‘lishi uchun", "Og‘irlashtirish uchun"], d=2,
              x="Moy qismlarning oson harakatlanishiga yordam beradi."),
            Q("Prujinani siqqanda paydo bo‘ladigan kuch?", "Elastiklik kuchi",
              ["Ishqalanish kuchi", "Og‘irlik kuchi", "Magnit kuchi"], d=2,
              x="Siqilgan prujina avvalgi shakliga qaytishga intiladi."),
            Q("Qaysi sirtda ishqalanish eng katta?", "Qumli yo‘lda", ["Muz ustida", "Silliq oynada", "Moylangan temirda"], d=2,
              x="G‘adir-budur sirtda ishqalanish katta bo‘ladi."),
            Q("Kuch nimaning natijasi?", "Jismlarning o‘zaro ta’sirining", ["Jism rangining", "Jism hidining", "Jism nomining"], d=2,
              x="Kuch doimo bir jismning boshqasiga ta’siri natijasida paydo bo‘ladi."),
            Q("Mashinaning tormozi qaysi kuch hisobiga ishlaydi?", "Ishqalanish kuchi",
              ["Og‘irlik kuchi", "Elastiklik kuchi", "Magnit kuchi"], d=2,
              x="Tormoz qismlari g‘ildirakka ishqalanib, uni to‘xtatadi."),
            Q("Qaysi biri ishqalanishni kamaytiradi?", "Moylash", ["Qum sepish", "Sirtni g‘adir-budur qilish", "Rezina tagcharm"], d=2,
              x="Moy sirtlar orasida sirpanchiq qatlam hosil qiladi."),
            Q("Qaysi misolda kuch jismning harakat yo‘nalishini o‘zgartirdi?", "To‘p devorga urilib qaytdi",
              ["Kitob stolda yotibdi", "Rasm devorda osilgan", "Tosh yerda turibdi"], d=2,
              x="Devorning ta’siri to‘p yo‘nalishini teskarisiga o‘zgartirdi."),
            TF("Ishqalanish har doim zararli.", False, d=2,
               x="Ishqalanish bo‘lmasa, yura olmasdik, mashina ham tormoz bera olmasdi."),
            MATCH("Misolni kuch turi bilan juftlang",
                  [("Olma pastga tushdi", "og‘irlik kuchi"), ("Chana qorda sekinlab to‘xtadi", "ishqalanish kuchi"),
                   ("Batut bolani yuqoriga otdi", "elastiklik kuchi"), ("Mix magnitga yopishdi", "magnit kuchi"),
                   ("Bola to‘pni tepdi", "muskul kuchi")], d=2),
            ORDER(S, "Kuch jismning tezligini o‘zgartiradi", d=2),
            Q("Qaysi holatda ishqalanish foydali?", "Poyabzal tagi yerga ilashganda",
              ["Mashina qismlari yeyilganda", "Chana og‘ir sirpanganda", "Eshik g‘ichirlaganda"], d=3,
              x="Ishqalanish tufayli oyog‘imiz sirpanmaydi va yura olamiz."),
            Q("Og‘irlik kuchi qaysi tomonga yo‘nalgan?", "Pastga, Yer markaziga", ["Yuqoriga", "Chapga", "O‘ngga"], d=3,
              x="Yer barcha jismlarni o‘z markazi tomon tortadi."),
            TF("Prujina qancha ko‘p cho‘zilsa, elastiklik kuchi shuncha katta bo‘ladi.", True, d=3,
               x="Dinamometr ham shu xossaga asoslangan."),
        ])

T.topic("energy", "⚡", L("Energiya va issiqlik", "Energy and heat", "Энергия и теплота"),
        chapter=C2,
        theory="Energiya — ish bajarish qobiliyati. Turlari: harakat (mexanik), issiqlik, yorug‘lik, elektr, tovush, kimyoviy (oziq-ovqat va yoqilg‘ida).\n"
               "Energiya yo‘qolmaydi, bir turdan boshqasiga aylanadi: lampochkada elektr energiya yorug‘lik va issiqlikka aylanadi.\n"
               "• Qayta tiklanadigan manbalar: Quyosh, shamol, oqar suv. • Tiklanmaydigan manbalar: ko‘mir, neft, tabiiy gaz.\n"
               "Metallar issiqlikni yaxshi o‘tkazadi; yog‘och, plastmassa, jun va havo yomon o‘tkazadi.\n"
               "Shuning uchun qozon dastasi yog‘och yoki plastmassadan yasaladi.",
        items=[
            Q("Yerdagi energiyaning asosiy manbai nima?", "Quyosh", ["Oy", "Ko‘mir", "Yulduzlar"],
              x="Quyosh Yerga yorug‘lik va issiqlik beradi, o‘simliklar shu energiya bilan o‘sadi."),
            Q("Qaysi biri qayta tiklanadigan energiya manbai?", "Shamol", ["Ko‘mir", "Neft", "Tabiiy gaz"],
              x="Shamol tugamaydi, u doimo qayta paydo bo‘ladi."),
            Q("Qaysi biri tiklanmaydigan energiya manbai?", "Neft", ["Quyosh", "Shamol", "Oqar suv"],
              x="Neft zaxiralari tugashi mumkin."),
            Q("Quyosh paneli Quyosh nurini qanday energiyaga aylantiradi?", "Elektr", ["Tovush", "Kimyoviy", "Magnit"],
              x="Quyosh panellari uylarni elektr bilan ta’minlaydi."),
            Q("Qaysi modda issiqlikni yaxshi o‘tkazadi?", "Mis", ["Yog‘och", "Plastmassa", "Jun"],
              x="Metallar issiqlikni yaxshi o‘tkazadi."),
            Q("Shamol generatori nima ishlab chiqaradi?", "Elektr energiya", ["Toza suv", "Yoqilg‘i", "Kislorod"],
              x="Shamol parraklarni aylantiradi, generator elektr ishlab chiqaradi."),
            Q("Issiq choyga temir qoshiq solinsa, qoshiq dastasi qanday bo‘ladi?", "Isib qoladi",
              ["Sovib qoladi", "Muzlaydi", "O‘zgarmaydi"], x="Temir issiqlikni yaxshi o‘tkazadi."),
            Q("Energiyani tejash uchun nima qilamiz?", "Keraksiz chiroqni o‘chiramiz",
              ["Chiroqni kun bo‘yi yoqib qo‘yamiz", "Televizorni ochiq qoldiramiz", "Muzlatgich eshigini ochiq qo‘yamiz"],
              x="Tejalgan elektr — tejalgan tabiiy boylik."),
            TF("Metallar issiqlikni yaxshi o‘tkazadi.", True, x="Shuning uchun qozon va choynaklar metalldan yasaladi."),
            TF("Ko‘mir — qayta tiklanadigan energiya manbai.", False,
               x="Ko‘mir millionlab yillar davomida hosil bo‘lgan, u tugab qolishi mumkin."),
            TF("Yugurayotgan bolada harakat energiyasi bor.", True, x="Harakatlanayotgan har bir jismda harakat energiyasi bor."),
            Q("Lampochkada elektr energiya nimaga aylanadi?", "Yorug‘lik va issiqlikka",
              ["Tovush va suvga", "Faqat sovuqqa", "Magnitga"], d=2, e="💡",
              x="Yongan lampochka yorug‘lik beradi va qiziydi."),
            Q("Suv elektr stansiyasi qaysi energiyadan foydalanadi?", "Oqar suv energiyasidan",
              ["Ko‘mir energiyasidan", "Neft energiyasidan", "Oy nuridan"], d=2,
              x="Oqayotgan suv turbinani aylantiradi."),
            Q("Oziq-ovqatda qanday energiya saqlanadi?", "Kimyoviy", ["Elektr", "Magnit", "Tovush"], d=2,
              x="Ovqatdagi kimyoviy energiya tanamizga kuch beradi."),
            Q("Qozon dastasi nima uchun yog‘ochdan yasaladi?", "Yog‘och issiqlikni yomon o‘tkazadi",
              ["Yog‘och og‘ir", "Yog‘och yaltiraydi", "Yog‘och issiqlikni yaxshi o‘tkazadi"], d=2,
              x="Yog‘och dasta qizimaydi va qo‘lni kuydirmaydi."),
            Q("Qishda jun kiyim nima uchun issiq tutadi?", "Jun issiqlikni yomon o‘tkazadi",
              ["Jun o‘zi issiqlik chiqaradi", "Jun Quyoshdan quvvat oladi", "Jun elektr o‘tkazadi"], d=2,
              x="Jun va uning orasidagi havo tana issiqligini tashqariga chiqarmaydi."),
            Q("Quyosh va shamol energiyasi nima uchun foydali?", "Tugamaydi va havoni ifloslamaydi",
              ["Tutun chiqaradi", "Faqat kechasi ishlaydi", "Tez tugab qoladi"], d=2,
              x="Ular qayta tiklanadigan va toza energiya manbalari."),
            Q("Xonada issiq havo qayerda to‘planadi?", "Shiftga yaqin joyda", ["Pol yaqinida", "Deraza tagida", "Stol ostida"], d=2,
              x="Issiq havo yengil, u yuqoriga ko‘tariladi."),
            Q("Qaysi modda issiqlikni yomon o‘tkazadi?", "Plastmassa", ["Temir", "Alyuminiy", "Mis"], d=2,
              x="Plastmassa, yog‘och, jun — issiqlikni yomon o‘tkazadi."),
            Q("Benzinli avtomobil qaysi energiya hisobiga yuradi?", "Yoqilg‘ining kimyoviy energiyasi",
              ["Oy nuri", "Tovush energiyasi", "Magnit energiyasi"], d=2,
              x="Benzin yonganda kimyoviy energiya harakat energiyasiga aylanadi."),
            ORDER(S, "Lampochka elektr energiyani yorug‘likka aylantiradi", d=2),
            Q("Quyosh issiqligi Yerga qanday yetib keladi?", "Nurlanish orqali", ["Havo oqimi orqali", "Suv orqali", "Simlar orqali"], d=3,
              x="Quyosh bilan Yer orasida havo yo‘q, issiqlik nurlar orqali keladi."),
            Q("Termos devorlari orasidagi bo‘shliq nima uchun kerak?", "Issiqlik tashqariga chiqmasligi uchun",
              ["Termos yengil bo‘lishi uchun", "Chiroyli ko‘rinishi uchun", "Choy tez sovishi uchun"], d=3,
              x="Havosiz bo‘shliq issiqlikni deyarli o‘tkazmaydi."),
            TF("Energiya yo‘qolmaydi, bir turdan boshqasiga aylanadi.", True, d=3,
               x="Masalan, ventilyatorda elektr energiya harakat energiyasiga aylanadi."),
            MATCH("Qurilmani energiya aylanishi bilan juftlang",
                  [("Lampochka", "elektr → yorug‘lik"), ("Ventilyator", "elektr → harakat"),
                   ("Quyosh paneli", "yorug‘lik → elektr"), ("Batareya", "kimyoviy → elektr"),
                   ("Elektr choynak", "elektr → issiqlik")], d=3),
        ])

T.topic("light_sound", "💡", L("Yorug‘lik va tovush", "Light and sound", "Свет и звук"),
        chapter=C2,
        theory="Yorug‘lik manbalari: tabiiy (Quyosh, yulduzlar, olov) va sun’iy (lampochka, fonar). Oy manba emas — u Quyosh nurini qaytaradi.\n"
               "• Yorug‘lik to‘g‘ri chiziq bo‘ylab tarqaladi. Noshaffof jism yorug‘likni to‘sganda soya hosil bo‘ladi.\n"
               "• Ko‘zgu va silliq sirtlar yorug‘likni qaytaradi.\n"
               "Tovush jismlarning tebranishidan hosil bo‘ladi. U havoda, suvda va qattiq jismlarda tarqaladi, lekin bo‘shliqda (vakuumda) tarqalmaydi.\n"
               "Tovushning to‘siqqa urilib qaytishi — aks-sado.",
        items=[
            Q("Qaysi biri tabiiy yorug‘lik manbai?", "Quyosh", ["Lampochka", "Fonar", "Televizor"],
              x="Quyoshni inson yaratmagan — u tabiiy manba."),
            Q("Qaysi biri sun’iy yorug‘lik manbai?", "Lampochka", ["Quyosh", "Yulduz", "Chaqmoq"],
              x="Lampochkani inson yaratgan."),
            Q("Yorug‘lik qanday tarqaladi?", "To‘g‘ri chiziq bo‘ylab", ["Aylana bo‘ylab", "Zigzag bo‘ylab", "Faqat pastga"],
              x="Shuning uchun yorug‘lik to‘siq ortiga o‘tmaydi va soya hosil bo‘ladi."),
            Q("Qaysi jism shaffof?", "Deraza oynasi", ["Yog‘och taxta", "Temir plastinka", "G‘isht"],
              x="Toza shisha yorug‘likni to‘liq o‘tkazadi."),
            Q("Yorug‘likni eng yaxshi qaytaradigan narsa?", "Ko‘zgu", ["Qora mato", "Yog‘och", "Tuproq"],
              x="Ko‘zgu silliq va yaltiroq, u yorug‘likni yaxshi qaytaradi."),
            Q("Tovush qanday hosil bo‘ladi?", "Jismlar tebranganda", ["Jismlar muzlaganda", "Jismlar bo‘yalganda", "Jismlar qorayganda"],
              e="🔊", x="Tebranayotgan jism atrofidagi havoni tebratadi."),
            Q("Tog‘da baqirganda ovozimiz qaytib eshitiladi. Bu nima?", "Aks-sado", ["Chaqmoq", "Kamalak", "Soya"],
              x="Tovush qoyaga urilib, orqaga qaytdi."),
            Q("Gitara tori chertilganda nima uchun ovoz chiqadi?", "Tor tebranadi",
              ["Tor qiziydi", "Tor yorug‘lik chiqaradi", "Tor uzayadi"], x="Tebranayotgan tor tovush hosil qiladi."),
            Q("Qattiq shovqin nimaga zarar?", "Eshitish qobiliyatiga", ["Sochga", "Tirnoqqa", "Ko‘z rangiga"],
              x="Qattiq shovqin quloqni charchatadi va eshitishni susaytiradi."),
            TF("Tovush suvda ham tarqaladi.", True, x="Baliqlar va delfinlar suvdagi tovushlarni eshitadi."),
            TF("Deraza oynasi yorug‘likni o‘tkazadi.", True, x="Shuning uchun xonaga kunduzi yorug‘lik kiradi."),
            Q("Soya qachon hosil bo‘ladi?", "Noshaffof jism yorug‘likni to‘sganda",
              ["Yorug‘lik ko‘payganda", "Shaffof shisha oldida", "Chiroq o‘chganda"], d=2,
              x="Yorug‘lik to‘g‘ri tarqaladi va jism ortiga o‘ta olmaydi."),
            Q("Tushda soya qanday bo‘ladi?", "Eng qisqa", ["Eng uzun", "Juda uzun", "Kechqurungidan uzunroq"], d=2,
              x="Tushda Quyosh eng baland turadi, soya eng qisqa bo‘ladi."),
            Q("Tovush qayerda tarqalmaydi?", "Bo‘shliqda (vakuumda)", ["Havoda", "Suvda", "Temirda"], d=2,
              x="Tovushni tarqatish uchun modda zarrachalari kerak."),
            Q("Qaysi jism yarim shaffof?", "Xira shisha", ["Toza deraza oynasi", "Temir eshik", "G‘isht devor"], d=2,
              x="Xira shisha yorug‘likni o‘tkazadi, lekin narsalar aniq ko‘rinmaydi."),
            TF("Oy — yorug‘lik manbai.", False, d=2, x="Oy o‘zidan nur chiqarmaydi, Quyosh nurini qaytaradi."),
            TF("Kosmosda tovush eshitilmaydi.", True, d=2, x="Kosmosda havo yo‘q, tovush esa bo‘shliqda tarqalmaydi."),
            MATCH("Tushunchani izohi bilan juftlang",
                  [("Soya", "yorug‘lik tushmagan joy"), ("Aks-sado", "qaytgan tovush"), ("Ko‘zgu", "yorug‘likni qaytaradi"),
                   ("Tebranish", "tovush manbai"), ("Vakuum", "havosiz bo‘shliq"), ("Kamalak", "yorug‘likning ranglarga ajralishi")], d=2),
            ORDER(S, "Tovush jismlarning tebranishidan hosil bo‘ladi", d=2),
            Q("Momaqaldiroqda nima uchun avval chaqmoq ko‘rinadi, keyin gumburlash eshitiladi?", "Yorug‘lik tovushdan tezroq",
              ["Tovush yorug‘likdan tezroq", "Chaqmoq yaqinroqda chaqadi", "Quloq ko‘zdan sekin ishlaydi"], d=3,
              x="Yorug‘lik juda tez tarqaladi, tovush esa undan ancha sekin."),
            Q("Oq yorug‘lik prizmadan o‘tganda nima hosil bo‘ladi?", "Kamalak ranglari", ["Qora soya", "Tovush", "Issiq bug‘"], d=3,
              x="Oq yorug‘lik turli ranglar aralashmasidan iborat."),
            Q("Qaysi hayvon aks-sado yordamida qorong‘ida mo‘ljal oladi?", "Ko‘rshapalak", ["Tovuq", "Sigir", "Toshbaqa"], d=3,
              x="Ko‘rshapalak tovush chiqaradi va qaytgan aks-sadoni eshitib yo‘l topadi."),
            TF("Tovush qattiq jismlarda havodagiga qaraganda tezroq tarqaladi.", True, d=3,
               x="Qattiq jismda zarrachalar zich joylashgani uchun tebranish tez uzatiladi."),
            Q("Yozda qora kiyim nima uchun ko‘proq qiziydi?", "Qora rang yorug‘likni yutadi",
              ["Qora rang yorug‘likni qaytaradi", "Qora mato og‘ir", "Qora rang sovuq"], d=3,
              x="Oq rang yorug‘likni qaytaradi, qora esa yutib, qiziydi."),
            Q("Chiroq jismga yaqinlashtirilsa, devordagi soya qanday o‘zgaradi?", "Kattalashadi",
              ["Kichrayadi", "Yo‘qoladi", "Rangi o‘zgaradi"], d=3,
              x="Chiroq yaqin bo‘lsa, jism yorug‘likning ko‘proq qismini to‘sadi."),
        ])

T.test("test2", L("2-nazorat ishi", "Test 2", "Контрольная работа 2"),
       ["phenomena", "forces", "energy", "light_sound"], chapter=C2)

# ============================================================ 3-chorak
T.topic("magnet_electric", "🔋", L("Magnit va elektr", "Magnets and electricity", "Магнит и электричество"),
        chapter=C3,
        theory="Magnit temir, po‘lat va nikelni o‘ziga tortadi; yog‘och, qog‘oz, shisha, plastmassa, mis tortilmaydi.\n"
               "Magnitning ikki qutbi bor: shimoliy (N) va janubiy (S). Har xil qutblar tortishadi, bir xil qutblar itarishadi. Yer ham katta magnit, shuning uchun kompas ishlaydi.\n"
               "Elektr zanjiri: tok manbai (batareya), simlar, iste’molchi (lampochka) va kalit. Zanjir yopiq bo‘lsa, tok o‘tadi.\n"
               "• O‘tkazgichlar tokni o‘tkazadi: mis, alyuminiy, temir. • Izolyatorlar o‘tkazmaydi: rezina, plastmassa, shisha, quruq yog‘och.\n"
               "Xavfsizlik: rozetkaga narsa tiqmang, ho‘l qo‘l bilan elektr asboblarga tegmang.",
        items=[
            Q("Magnit qaysi jismni o‘ziga tortadi?", "Temir mix", ["Yog‘och qalam", "Qog‘oz", "Shisha stakan"],
              x="Temir magnitga tortiladi."),
            Q("Magnitning nechta qutbi bor?", "2 ta", ["1 ta", "3 ta", "4 ta"], x="Shimoliy (N) va janubiy (S) qutb."),
            Q("Magnitning shimoliy va janubiy qutblari yaqinlashtirilsa nima bo‘ladi?", "Tortishadi",
              ["Itarishadi", "Hech narsa bo‘lmaydi", "Eriydi"], x="Har xil qutblar bir-birini tortadi."),
            Q("Elektr zanjirida tok manbai qaysi?", "Batareya", ["Lampochka", "Kalit", "Sim"], e="🔋",
              x="Batareya zanjirga elektr energiya beradi."),
            Q("Zanjirni ulash va uzish uchun nima kerak?", "Kalit", ["Lampochka", "Batareya", "Rezina"],
              x="Kalit yordamida chiroqni yoqamiz va o‘chiramiz."),
            Q("Qaysi modda elektr tokini yaxshi o‘tkazadi?", "Mis", ["Rezina", "Plastmassa", "Shisha"],
              x="Shuning uchun elektr simlari misdan yasaladi."),
            Q("Qaysi modda izolyator?", "Rezina", ["Mis", "Alyuminiy", "Temir"], x="Rezina elektr tokini o‘tkazmaydi."),
            Q("Uzilib tushgan elektr simini ko‘rsangiz nima qilasiz?", "Yaqinlashmay, kattalarga aytaman",
              ["Qo‘lim bilan olaman", "Tayoq bilan o‘ynayman", "Ustidan sakrab o‘taman"],
              x="Uzilgan sim juda xavfli, unga yaqinlashmaslik kerak."),
            Q("Magnit bilan qumdan nimani ajratib olish mumkin?", "Temir qipig‘ini", ["Tuzni", "Shakarni", "Suvni"],
              x="Faqat temir qipig‘i magnitga tortiladi."),
            TF("Magnitning bir xil qutblari bir-birini itaradi.", True, x="N va N yoki S va S qutblar itarishadi."),
            TF("Ho‘l qo‘l bilan rozetkaga tegish xavfli.", True, x="Nam teri tokni yaxshiroq o‘tkazadi, tok urishi mumkin."),
            Q("Kompas mili nima uchun doim bir yo‘nalishni ko‘rsatadi?", "Yer katta magnit",
              ["Kompas batareyada ishlaydi", "Shamol buradi", "Quyosh tortadi"], d=2,
              x="Kompas mili — kichik magnit, u Yer magnitiga qarab buriladi."),
            Q("Elektr simlari nima uchun plastmassa bilan qoplanadi?", "Tok urmasligi uchun",
              ["Chiroyli bo‘lishi uchun", "Tok tezroq o‘tishi uchun", "Og‘ir bo‘lishi uchun"], d=2,
              x="Plastmassa — izolyator, u bizni tokdan himoya qiladi."),
            Q("Kalit ochilsa (zanjir uzilsa), lampochka bilan nima bo‘ladi?", "O‘chadi",
              ["Yorqinroq yonadi", "Rangi o‘zgaradi", "Kattalashadi"], d=2,
              x="Uzilgan zanjirda tok o‘tmaydi."),
            Q("Qaysi juftlikning ikkalasi ham magnitga tortiladi?", "Temir mix va skrepka",
              ["Mis sim va qog‘oz", "Plastmassa va shisha", "Yog‘och va rezina"], d=2,
              x="Mix va skrepka temirdan (po‘latdan) yasalgan."),
            Q("Tabiatdagi qaysi hodisa elektr bilan bog‘liq?", "Chaqmoq", ["Kamalak", "Shudring", "Tuman"], d=2,
              x="Chaqmoq — ulkan elektr uchquni."),
            TF("Magnit mis simni o‘ziga tortadi.", False, d=2, x="Mis magnitga tortilmaydi."),
            TF("Lampochka yonishi uchun zanjir yopiq bo‘lishi kerak.", True, d=2,
               x="Tok faqat uzilmagan, yopiq zanjirda oqadi."),
            TF("Quruq yog‘och elektr tokini yaxshi o‘tkazadi.", False, d=2, x="Quruq yog‘och — izolyator."),
            MATCH("Zanjir qismini vazifasi bilan juftlang",
                  [("Batareya", "tok manbai"), ("Lampochka", "yorug‘lik beradi"), ("Kalit", "zanjirni ulaydi va uzadi"),
                   ("Sim", "tokni o‘tkazadi"), ("Sim qoplamasi", "tokdan himoya qiladi")], d=2),
            ORDER(S, "Har xil qutblar bir-birini tortadi", d=2),
            Q("Magnit qayerida eng kuchli tortadi?", "Qutblarida", ["O‘rtasida", "Hamma joyida bir xil", "Hech qayerida"], d=3,
              x="Temir qipiqlari magnit uchlariga ko‘proq yopishadi."),
            Q("Qaysi qurilma elektr energiyani harakatga aylantiradi?", "Elektr dvigatel", ["Lampochka", "Batareya", "Termometr"], d=3,
              x="Elektr dvigatel ventilyator va mikserlarni aylantiradi."),
            Q("Sochga ishqalangan plastmassa taroq mayda qog‘ozlarga yaqinlashtirilsa nima bo‘ladi?", "Qog‘ozlar taroqqa tortiladi",
              ["Qog‘ozlar yonadi", "Taroq eriydi", "Hech narsa bo‘lmaydi"], d=3,
              x="Taroq ishqalanishdan elektrlanadi va yengil narsalarni tortadi."),
        ])

T.topic("earth", "🌋", L("Yer tuzilishi va qobiqlari", "Earth's structure and spheres", "Строение Земли и её оболочки"),
        chapter=C3,
        theory="Yerning ichki tuzilishi uch qatlamdan iborat:\n"
               "• yer po‘sti — eng yupqa, ustki qattiq qatlam; • mantiya — o‘rta qatlam; • yadro — markazdagi eng issiq qism.\n"
               "Yerning tashqi qobiqlari:\n"
               "• atmosfera — havo qobig‘i; • gidrosfera — suv qobig‘i (okean, dengiz, daryo, ko‘l, muzlik);\n"
               "• litosfera — tosh qobig‘i; • biosfera — hayot qobig‘i, ya’ni tirik organizmlar tarqalgan qism.\n"
               "Yer yuzasining katta qismi suv bilan qoplangan, bu suvning ko‘p qismi sho‘r.",
        items=[
            Q("Yerning eng ustki qattiq qatlami nima deyiladi?", "Yer po‘sti", ["Mantiya", "Yadro", "Atmosfera"],
              x="Biz yer po‘sti ustida yashaymiz."),
            Q("Yerning markazidagi qismi nima deyiladi?", "Yadro", ["Yer po‘sti", "Mantiya", "Litosfera"],
              x="Yadro — Yerning eng ichki, eng issiq qismi."),
            Q("Yerning havo qobig‘i nima deyiladi?", "Atmosfera", ["Gidrosfera", "Litosfera", "Biosfera"],
              x="Atmosfera — Yerni o‘rab turgan havo qatlami."),
            Q("Yerning suv qobig‘i nima deyiladi?", "Gidrosfera", ["Atmosfera", "Litosfera", "Biosfera"],
              x="Okean, dengiz, daryo, ko‘l va muzliklar — gidrosfera."),
            Q("Yerning tosh qobig‘i nima deyiladi?", "Litosfera", ["Gidrosfera", "Atmosfera", "Biosfera"],
              x="Tog‘lar, toshlar, tuproq ostidagi qatlamlar — litosfera."),
            Q("Tirik organizmlar tarqalgan qobiq nima deyiladi?", "Biosfera", ["Litosfera", "Atmosfera", "Gidrosfera"],
              x="Biosfera — hayot qobig‘i."),
            Q("Yer qanday shaklda?", "Sharsimon", ["Yassi", "Kub shaklida", "Uchburchak"], x="Yer shar shakliga ega."),
            Q("Yer po‘stining silkinishi nima deyiladi?", "Zilzila", ["Kamalak", "Shamol", "Tuman"],
              x="Zilzilada yer po‘sti tebranadi."),
            Q("Yer yuzasining katta qismini nima egallaydi?", "Suv", ["Cho‘l", "Tog‘lar", "O‘rmonlar"],
              x="Okean va dengizlar Yer yuzasining katta qismini egallaydi."),
            TF("Tog‘lar va toshlar litosferaga kiradi.", True, x="Litosfera — Yerning tosh qobig‘i."),
            MATCH("Tushunchani izohi bilan juftlang",
                  [("Atmosfera", "havo qobig‘i"), ("Gidrosfera", "suv qobig‘i"), ("Litosfera", "tosh qobig‘i"),
                   ("Biosfera", "hayot qobig‘i"), ("Yadro", "Yerning markazi"), ("Yer po‘sti", "eng yupqa ustki qatlam")]),
            Q("Yer po‘sti va yadro orasidagi qatlam qaysi?", "Mantiya", ["Atmosfera", "Gidrosfera", "Biosfera"], d=2,
              x="Mantiya — yer po‘sti ostidagi o‘rta qatlam."),
            Q("Eng katta okean qaysi?", "Tinch okeani", ["Atlantika okeani", "Hind okeani", "Shimoliy Muz okeani"], d=2,
              x="Tinch okeani — Yerdagi eng katta okean."),
            Q("Vulqondan otilib chiqadigan qaynoq suyuq tog‘ jinsi nima deyiladi?", "Lava", ["Muz", "Qum", "Tuman"], d=2, e="🌋",
              x="Yer ostidagi magma yuzaga chiqqach, lava deyiladi."),
            Q("Qaysi biri gidrosferaga kirmaydi?", "Tog‘ jinslari", ["Okeanlar", "Daryolar", "Muzliklar"], d=2,
              x="Tog‘ jinslari — litosferaning qismi."),
            Q("Litosferaga nima kiradi?", "Tog‘lar va toshlar", ["Bulutlar", "Daryo suvi", "Havo"], d=2,
              x="Litosfera — Yerning qattiq, tosh qobig‘i."),
            Q("Yer po‘sti boshqa qatlamlarga nisbatan qanday?", "Eng yupqa", ["Eng qalin", "Yadrodan qalin", "Mantiyadan qalin"], d=2,
              x="Yer po‘sti Yer ichki qatlamlari orasida eng yupqasi."),
            TF("Yadro — Yerning eng issiq qismi.", True, d=2, x="Yer markaziga yaqinlashgan sari harorat oshib boradi."),
            TF("Yerdagi suvning ko‘p qismi chuchuk.", False, d=2,
               x="Yerdagi suvning katta qismi okean va dengizlardagi sho‘r suv."),
            TF("Atmosfera Yerni Quyoshning zararli nurlaridan himoya qiladi.", True, d=2,
               x="Havo qobig‘i hayotni zararli nurlar va sovuqdan asraydi."),
            TF("Tirik organizmlar havoda, suvda va tuproqda ham yashaydi.", True, d=2,
               x="Shuning uchun biosfera boshqa qobiqlarning bir qismini ham qamrab oladi."),
            ORDER(S, "Yerning havo qobig‘i atmosfera deyiladi", d=2),
            Q("Havodagi qaysi qatlam Quyoshning zararli ultrabinafsha nurlarini ushlab qoladi?", "Ozon qatlami",
              ["Bulutlar qatlami", "Chang qatlami", "Tuman qatlami"], d=3,
              x="Ozon qatlami tiriklarni zararli nurlardan himoya qiladi."),
            Q("Chuchuk suvning katta qismi qayerda?", "Muzliklarda", ["Dengizlarda", "Okeanlarda", "Bulutlarda"], d=3,
              x="Chuchuk suvning ko‘p qismi qutblardagi va tog‘lardagi muzliklarda."),
            TF("Yerning tashqi yadrosi suyuq, ichki yadrosi qattiq.", True, d=3,
               x="Ichki yadro juda katta bosim ostida qattiq holatda turadi."),
        ])

T.topic("solar", "🌞", L("Quyosh tizimi", "The Solar System", "Солнечная система"),
        chapter=C3,
        theory="Quyosh tizimi markazida Quyosh — ulkan issiq yulduz turadi. Uning atrofida 8 ta sayyora aylanadi.\n"
               "Quyoshdan boshlab tartibi: Merkuriy, Venera, Yer, Mars, Yupiter, Saturn, Uran, Neptun.\n"
               "• Merkuriy — Quyoshga eng yaqin va eng kichik sayyora. • Yupiter — eng katta sayyora.\n"
               "• Mars — “qizil sayyora”. • Saturn — yorqin halqalari bilan mashhur.\n"
               "Yer — hayot borligi ma’lum bo‘lgan yagona sayyora. Oy — Yerning tabiiy yo‘ldoshi.",
        items=[
            Q("Quyosh tizimining markazida nima joylashgan?", "Quyosh", ["Yer", "Oy", "Yupiter"],
              x="Barcha sayyoralar Quyosh atrofida aylanadi."),
            Q("Quyosh tizimida nechta sayyora bor?", "8 ta", ["7 ta", "9 ta", "12 ta"],
              x="Merkuriy, Venera, Yer, Mars, Yupiter, Saturn, Uran, Neptun."),
            Q("Eng katta sayyora qaysi?", "Yupiter", ["Yer", "Mars", "Merkuriy"], x="Yupiter — Quyosh tizimidagi eng katta sayyora."),
            Q("Quyoshga eng yaqin sayyora qaysi?", "Merkuriy", ["Venera", "Yer", "Neptun"], x="Merkuriy — birinchi sayyora."),
            Q("Qaysi sayyora “qizil sayyora” deb ataladi?", "Mars", ["Venera", "Yupiter", "Neptun"],
              x="Mars tuprog‘i qizg‘ish rangda."),
            Q("Yorqin halqalari bilan mashhur sayyora qaysi?", "Saturn", ["Mars", "Merkuriy", "Venera"],
              x="Saturn halqalari muz va tosh bo‘laklaridan iborat."),
            Q("Yer Quyoshdan nechanchi sayyora?", "3-sayyora", ["1-sayyora", "2-sayyora", "4-sayyora"],
              x="Merkuriy, Venera, keyin Yer."),
            Q("Yerning tabiiy yo‘ldoshi nima?", "Oy", ["Mars", "Quyosh", "Venera"], e="🌙", x="Oy Yer atrofida aylanadi."),
            TF("Quyosh — yulduz.", True, x="Quyosh — bizga eng yaqin yulduz."),
            TF("Hayot borligi ma’lum bo‘lgan yagona sayyora — Yer.", True, x="Boshqa sayyoralarda hozircha hayot topilmagan."),
            TF("Yupiter — Quyoshga eng yaqin sayyora.", False, x="Quyoshga eng yaqini — Merkuriy, Yupiter esa beshinchi."),
            TF("Oy Yer atrofida aylanadi.", True, x="Oy — Yerning yo‘ldoshi."),
            Q("Quyoshdan eng uzoq sayyora qaysi?", "Neptun", ["Uran", "Saturn", "Mars"], d=2,
              x="Neptun — sakkizinchi, oxirgi sayyora."),
            Q("Quyoshdan uzoqlashish tartibida Yerdan keyin qaysi sayyora keladi?", "Mars", ["Venera", "Yupiter", "Merkuriy"], d=2,
              x="Yer — 3-, Mars — 4-sayyora."),
            Q("Yupiter va Uran orasida qaysi sayyora joylashgan?", "Saturn", ["Mars", "Neptun", "Venera"], d=2,
              x="Yupiter, Saturn, Uran — ketma-ket."),
            Q("Venera va Mars orasida qaysi sayyora joylashgan?", "Yer", ["Merkuriy", "Yupiter", "Saturn"], d=2,
              x="Venera — 2-, Yer — 3-, Mars — 4-sayyora."),
            Q("Yulduzning sayyoradan farqi nima?", "Yulduz o‘zi nur sochadi",
              ["Sayyora o‘zi nur sochadi", "Yulduzlar Yer atrofida aylanadi", "Farqi yo‘q"], d=2,
              x="Sayyoralar yulduz nurini qaytarib ko‘rinadi."),
            Q("Dumli osmon jismi nima deyiladi?", "Kometa", ["Sayyora", "Yo‘ldosh", "Yulduz"], d=2,
              x="Kometa Quyoshga yaqinlashganda uzun yorug‘ dum hosil bo‘ladi."),
            MATCH("Sayyorani belgisi bilan juftlang",
                  [("Merkuriy", "Quyoshga eng yaqin"), ("Yer", "hayot bor"), ("Mars", "qizil sayyora"), ("Yupiter", "eng katta"),
                   ("Saturn", "yorqin halqalari bor"), ("Neptun", "Quyoshdan eng uzoq")], d=2),
            ORDER("Sayyoralarni Quyoshdan boshlab tartiblang", "Merkuriy Venera Yer Mars", d=2,
                  x="Merkuriy, Venera, Yer, Mars — Quyoshga yaqin sayyoralar."),
            ORDER("Sayyoralarni Quyoshdan boshlab tartiblang", "Yupiter Saturn Uran Neptun", d=3,
                  x="Yupiter, Saturn, Uran, Neptun — ulkan sayyoralar."),
            Q("Mars va Yupiter orasida nima joylashgan?", "Asteroidlar belbog‘i", ["Oy", "Quyosh", "Saturn halqasi"], d=3,
              x="U yerda son-sanoqsiz tosh bo‘laklari — asteroidlar aylanadi."),
            Q("Pluton hozir qanday osmon jismi hisoblanadi?", "Mitti sayyora", ["Katta sayyora", "Yulduz", "Kometa"], d=3,
              x="Olimlar Plutonni mitti sayyoralar qatoriga kiritgan."),
            Q("Qaysi sayyoralar ulkan sayyoralar deyiladi?", "Yupiter, Saturn, Uran, Neptun",
              ["Merkuriy, Venera, Yer, Mars", "Yer, Oy, Mars, Venera", "Merkuriy, Mars, Uran, Yer"], d=3,
              x="Bu to‘rt sayyora Yerdan ko‘p marta katta."),
            Q("Quyosh nuri Yerga taxminan qancha vaqtda yetib keladi?", "8 minutda", ["1 sekundda", "1 kunda", "1 yilda"], d=3,
              x="Yorug‘lik juda tez bo‘lsa ham, Quyoshgacha masofa juda katta."),
            Q("Eng issiq sayyora qaysi?", "Venera", ["Merkuriy", "Mars", "Neptun"], d=3,
              x="Veneraning qalin atmosferasi issiqlikni ushlab turadi, shuning uchun u Merkuriydan ham issiq."),
        ])

T.test("test3", L("3-nazorat ishi", "Test 3", "Контрольная работа 3"),
       ["magnet_electric", "earth", "solar"], chapter=C3)

# ============================================================ 4-chorak
T.topic("cell", "🔬", L("Hujayra va mikroskop", "Cells and the microscope", "Клетка и микроскоп"),
        chapter=C4,
        theory="Barcha tirik organizmlar hujayralardan tuzilgan. Hujayrani mikroskop yordamida ko‘ramiz.\n"
               "Hujayraning asosiy qismlari: membrana (qobiq), sitoplazma va yadro. Yadro hujayra hayotini boshqaradi.\n"
               "O‘simlik hujayrasida bulardan tashqari qattiq hujayra devori, yashil xloroplastlar va hujayra shirasi to‘la vakuola bor.\n"
               "Hayvon hujayrasida hujayra devori va xloroplast bo‘lmaydi.\n"
               "Mikroskop qismlari: okulyar, obyektiv, tubus, buyum stolchasi, vintlar va oyna (yoki chiroq).",
        items=[
            Q("Tirik organizmlar nimadan tuzilgan?", "Hujayralardan", ["Toshlardan", "Tomchilardan", "Qumdan"],
              x="Hujayra — tiriklikning eng kichik birligi."),
            Q("Hujayrani ko‘rish uchun qaysi asbob kerak?", "Mikroskop", ["Teleskop", "Termometr", "Tarozi"], e="🔬",
              x="Ko‘pchilik hujayralar juda mayda, ular faqat mikroskopda ko‘rinadi."),
            Q("Hujayra hayotini qaysi qism boshqaradi?", "Yadro", ["Vakuola", "Hujayra devori", "Sitoplazma"],
              x="Yadro hujayraning “boshqaruv markazi”."),
            Q("Qaysi biri mikroskop qismi EMAS?", "Menzurka", ["Okulyar", "Obyektiv", "Tubus"],
              x="Menzurka — suyuqlik hajmini o‘lchaydigan idish."),
            Q("Hujayrani tashqaridan o‘rab turuvchi yupqa parda nima?", "Membrana", ["Yadro", "Sitoplazma", "Vakuola"],
              x="Membrana hujayra ichini tashqi muhitdan ajratib turadi."),
            Q("Kichik narsalarni biroz kattalashtirib ko‘rsatuvchi oddiy asbob?", "Lupa", ["Teleskop", "Termometr", "Dinamometr"],
              x="Lupa bir necha marta, mikroskop esa yuzlab marta kattalashtiradi."),
            TF("O‘simlik hujayrasida qattiq hujayra devori bor.", True, x="Hujayra devori o‘simlikka mustahkamlik beradi."),
            TF("Hamma tirik organizmlar hujayralardan tuzilgan.", True, x="Bakteriyadan tortib odamgacha — hamma hujayralardan iborat."),
            TF("Hujayralarni oddiy ko‘z bilan osongina ko‘rish mumkin.", False,
               x="Ko‘pchilik hujayralar juda kichik, ularni mikroskopsiz ko‘rib bo‘lmaydi."),
            ORDER(S, "Barcha tirik organizmlar hujayralardan tuzilgan"),
            Q("O‘simlik hujayrasiga yashil rang beradigan qism?", "Xloroplastlar", ["Yadro", "Vakuola", "Membrana"], d=2,
              x="Xloroplastlarda yashil modda — xlorofill bor."),
            Q("Qaysi qism faqat o‘simlik hujayrasida bor?", "Xloroplast", ["Yadro", "Sitoplazma", "Membrana"], d=2,
              x="Hayvon hujayrasida xloroplast bo‘lmaydi."),
            Q("Mikroskopning ko‘z qo‘yib qaraladigan qismi?", "Okulyar", ["Obyektiv", "Buyum stolchasi", "Vint"], d=2,
              x="Okulyar — ko‘zga yaqin turadigan linza."),
            Q("Kuzatiladigan preparat mikroskopning qayeriga qo‘yiladi?", "Buyum stolchasiga", ["Okulyarga", "Tubus ichiga", "Vint ustiga"], d=2,
              x="Preparat buyum stolchasidagi teshik ustiga qo‘yiladi."),
            Q("Hujayra ichini to‘ldirib turuvchi quyuq suyuqlik?", "Sitoplazma", ["Yadro", "Xloroplast", "Hujayra devori"], d=2,
              x="Sitoplazmada hujayraning boshqa qismlari joylashgan."),
            Q("Qaysi organizm bitta hujayradan iborat?", "Amyoba", ["Mushuk", "Olma daraxti", "Baliq"], d=2,
              x="Amyoba — bir hujayrali organizm."),
            Q("Maktabda mikroskopda ko‘pincha qaysi hujayralar kuzatiladi?", "Piyoz po‘sti hujayralari",
              ["Tosh zarralari", "Temir qipig‘i", "Qum donachasi"], d=2,
              x="Piyoz po‘sti yupqa bo‘lgani uchun hujayralari yaxshi ko‘rinadi."),
            Q("Mikroskopni qanday ko‘tarish kerak?", "Ikki qo‘llab, ehtiyotkorlik bilan",
              ["Bir barmoq bilan", "Okulyaridan ushlab", "Silkitib"], d=2,
              x="Mikroskop — nozik asbob, uni tushirib yuborish mumkin emas."),
            Q("O‘simlik va hayvon hujayrasida qaysi qism ikkalasida ham bor?", "Yadro",
              ["Xloroplast", "Hujayra devori", "Katta vakuola"], d=2,
              x="Yadro, sitoplazma va membrana ikkala hujayrada ham bor."),
            TF("Hayvon hujayrasida xloroplast bo‘lmaydi.", True, d=2, x="Shuning uchun hayvonlar o‘zi oziq tayyorlay olmaydi."),
            MATCH("Hujayra qismini vazifasi bilan juftlang",
                  [("Yadro", "hujayrani boshqaradi"), ("Membrana", "hujayrani o‘rab turadi"), ("Sitoplazma", "hujayra ichini to‘ldiradi"),
                   ("Xloroplast", "fotosintez qiladi"), ("Vakuola", "hujayra shirasini saqlaydi"),
                   ("Hujayra devori", "o‘simlik hujayrasiga mustahkamlik beradi")], d=2),
            Q("Okulyar 10 marta, obyektiv 20 marta kattalashtiradi. Mikroskop necha marta kattalashtiradi?", "200 marta",
              ["30 marta", "10 marta", "20 marta"], d=3, x="Umumiy kattalashtirish = 10 × 20 = 200 marta."),
            Q("Hujayrani birinchi bo‘lib kim kuzatgan va nomlagan?", "Robert Guk",
              ["Isaak Nyuton", "Charlz Darvin", "Galileo Galiley"], d=3,
              x="Robert Guk po‘kak bo‘lagini o‘zi yasagan mikroskopda kuzatib, “hujayra” deb nomlagan."),
            Q("Hujayra shirasi to‘plangan qism?", "Vakuola", ["Yadro", "Membrana", "Okulyar"], d=3,
              x="O‘simlik hujayrasida katta vakuola bo‘ladi."),
            TF("Organizm hujayralarning bo‘linishi tufayli o‘sadi.", True, d=3,
               x="Hujayralar bo‘linib ko‘payadi, organizm kattalashadi."),
        ])

T.topic("living", "🌿", L("Tirik organizmlar. Fotosintez", "Living organisms. Photosynthesis", "Живые организмы. Фотосинтез"),
        chapter=C4,
        theory="Tirik organizmlarning belgilari: nafas olish, oziqlanish, o‘sish va rivojlanish, ko‘payish, harakat, ta’sirlanish, keraksiz moddalarni chiqarish (ayirish).\n"
               "Tirik organizmlar bir hujayrali (amyoba, bakteriya) va ko‘p hujayrali (o‘simlik, hayvon) bo‘ladi.\n"
               "Fotosintez — yashil o‘simliklar barglarida yorug‘lik ta’sirida karbonat angidrid va suvdan oziq modda (shakar, kraxmal) va kislorod hosil bo‘lishi.\n"
               "Fotosintez xloroplastlardagi yashil modda — xlorofill yordamida boradi. Hosil bo‘lgan kislorod havoga chiqadi.\n"
               "O‘simliklar ham kecha-kunduz nafas oladi: kislorod yutib, karbonat angidrid chiqaradi.",
        items=[
            Q("Qaysi biri tirik organizm belgisi?", "Ko‘payish", ["Erish", "Zanglash", "Sinish"],
              x="Ko‘payish faqat tirik organizmlarga xos."),
            Q("Fotosintez o‘simlikning qaysi qismida asosan boradi?", "Bargida", ["Ildizida", "Urug‘ida", "Gulida"],
              x="Yashil barglarda xloroplastlar ko‘p."),
            Q("Fotosintezda havoga qaysi gaz chiqariladi?", "Kislorod", ["Karbonat angidrid", "Azot", "Vodorod"],
              x="O‘simliklar chiqargan kislorod bilan biz nafas olamiz."),
            Q("Qaysi organizmlar o‘zi uchun oziq tayyorlay oladi?", "Yashil o‘simliklar", ["Hayvonlar", "Zamburug‘lar", "Odamlar"],
              x="Yashil o‘simliklar fotosintez orqali oziq hosil qiladi."),
            Q("Tirik organizmni notirik jismdan qanday farqlaymiz?", "U nafas oladi va ko‘payadi",
              ["U og‘ir bo‘ladi", "U rangli bo‘ladi", "U qattiq bo‘ladi"],
              x="Nafas olish, oziqlanish, o‘sish, ko‘payish — tiriklik belgilari."),
            Q("Fotosintezda hosil bo‘lgan kislorod kimga kerak?", "Nafas oluvchi barcha tiriklarga",
              ["Faqat toshlarga", "Hech kimga", "Faqat bulutlarga"], x="Odamlar, hayvonlar va o‘simliklar kislorod bilan nafas oladi."),
            Q("Qaysi biri tirik organizm EMAS?", "Tosh", ["Bakteriya", "Qo‘ziqorin", "Chumoli"],
              x="Tosh nafas olmaydi, o‘smaydi va ko‘paymaydi."),
            TF("Fotosintez faqat yorug‘likda boradi.", True, x="Yorug‘lik — fotosintez uchun energiya manbai."),
            TF("O‘simliklar nafas olmaydi.", False, x="O‘simliklar ham nafas oladi: kislorod yutib, karbonat angidrid chiqaradi."),
            TF("Hayvonlar ham, o‘simliklar ham o‘sadi.", True, x="O‘sish — barcha tiriklarga xos belgi."),
            TF("Qo‘ziqorin — tirik organizm.", True, x="Qo‘ziqorin o‘sadi, oziqlanadi va sporalar orqali ko‘payadi."),
            Q("Fotosintez uchun nima kerak?", "Yorug‘lik, suv, karbonat angidrid",
              ["Qorong‘ilik va muz", "Faqat tuproq", "Kislorod va qum"], d=2,
              x="Barg yorug‘likda suv va karbonat angidriddan oziq tayyorlaydi."),
            Q("Fotosintezda o‘simlik havodan qaysi gazni yutadi?", "Karbonat angidrid", ["Kislorod", "Azot", "Vodorod"], d=2,
              x="Karbonat angidrid barg ichiga kirib, oziq hosil qilishga sarflanadi."),
            Q("Barglarga yashil rang beradigan modda?", "Xlorofill", ["Kraxmal", "Shakar", "Tuz"], d=2,
              x="Xlorofill xloroplastlarda joylashgan."),
            Q("Fotosintezda qanday oziq modda hosil bo‘ladi?", "Shakar va kraxmal", ["Tuz", "Temir", "Qum"], d=2,
              x="Shakar keyinchalik kraxmalga aylanib, zaxira sifatida saqlanadi."),
            Q("Qaysi biri bir hujayrali organizm?", "Bakteriya", ["Qo‘ziqorin", "Chumoli", "Terak"], d=2,
              x="Bakteriya bitta hujayradan iborat va juda mayda."),
            Q("O‘simlik qorong‘i xonada uzoq tursa nima bo‘ladi?", "Oziq tayyorlay olmay so‘liydi",
              ["Tezroq o‘sadi", "Ko‘proq kislorod chiqaradi", "Gullab ketadi"], d=2,
              x="Yorug‘liksiz fotosintez bormaydi."),
            Q("O‘rmonlar nima uchun “sayyora o‘pkasi” deyiladi?", "Ular ko‘p kislorod chiqaradi",
              ["Ular havoni isitadi", "Ular karbonat angidrid chiqaradi", "Ular shamol hosil qiladi"], d=2,
              x="Daraxtlar fotosintezda karbonat angidridni yutib, kislorod chiqaradi."),
            TF("Hayvonlar o‘zi uchun fotosintez orqali oziq tayyorlaydi.", False, d=2,
               x="Hayvonlar tayyor oziq bilan oziqlanadi, fotosintezni yashil o‘simliklar qiladi."),
            MATCH("Tiriklik belgisini misoli bilan juftlang",
                  [("Oziqlanish", "quyon sabzi yeydi"), ("O‘sish", "nihol daraxtga aylanadi"), ("Ko‘payish", "mushuk bolaladi"),
                   ("Nafas olish", "baliq jabrasi bilan kislorod oladi"), ("Ta’sirlanish", "issiqqa tekkan qo‘l tortib olinadi"),
                   ("Harakat", "qush uchib ketdi")], d=2),
            ORDER(S, "Yashil barglar yorug‘likda kislorod chiqaradi", d=2),
            Q("Barglardagi kraxmalni qaysi modda yordamida aniqlash mumkin?", "Yod", ["Tuz", "Shakar", "Suv"], d=3,
              x="Yod kraxmal bilan ko‘k-binafsha rangga bo‘yaladi."),
            Q("Keraksiz moddalarni tanadan chiqarish nima deyiladi?", "Ayirish", ["Oziqlanish", "Ko‘payish", "O‘sish"], d=3,
              x="Ayirish — tiriklik belgilaridan biri."),
            Q("Kapalak qurtdan g‘umbakka, so‘ng kapalakka aylanadi. Bu qaysi belgi?", "Rivojlanish",
              ["Nafas olish", "Ayirish", "Oziqlanish"], d=3,
              x="Organizmning shakli va tuzilishi o‘zgarib borishi — rivojlanish."),
            Q("Karbonat angidrid barg ichiga qayerdan kiradi?", "Barg og‘izchalari orqali",
              ["Ildiz tuklari orqali", "Gul barglari orqali", "Urug‘ orqali"], d=3,
              x="Barg sirtida gaz almashadigan juda mayda teshikchalar — og‘izchalar bor."),
            TF("Zamburug‘lar fotosintez qilmaydi.", True, d=3,
               x="Zamburug‘larda xlorofill yo‘q, ular tayyor organik moddalar bilan oziqlanadi."),
        ])

T.topic("ecosystem", "🦉", L("Ekotizim va oziq zanjiri", "Ecosystems and food chains", "Экосистема и пищевые цепи"),
        chapter=C4,
        theory="Ekotizim — bir joyda yashovchi tirik organizmlar va ularni o‘rab turgan notirik tabiat (suv, havo, tuproq, yorug‘lik) birligi: o‘rmon, ko‘l, cho‘l.\n"
               "Ekotizimda organizmlarning uch guruhi bor:\n"
               "• ishlab chiqaruvchilar — yashil o‘simliklar, ular Quyosh energiyasi yordamida oziq hosil qiladi;\n"
               "• iste’molchilar — hayvonlar, ular tayyor oziq bilan oziqlanadi;\n"
               "• parchalovchilar — bakteriyalar va zamburug‘lar, ular qoldiqlarni chiritib, tuproqqa qaytaradi.\n"
               "Oziq zanjiri: o‘t → chigirtka → baqa → ilon. Zanjir doimo ishlab chiqaruvchidan boshlanadi.",
        items=[
            Q("Oziq zanjirida ishlab chiqaruvchilar kimlar?", "Yashil o‘simliklar", ["Yirtqichlar", "O‘txo‘rlar", "Zamburug‘lar"],
              x="Yashil o‘simliklar oziqni o‘zi hosil qiladi."),
            Q("Qoldiqlarni chiritadigan organizmlar kimlar?", "Bakteriyalar va zamburug‘lar", ["Qushlar", "Baliqlar", "Daraxtlar"],
              x="Ular parchalovchilar deyiladi."),
            Q("Hayvonlar ekotizimda qaysi guruhga kiradi?", "Iste’molchilar",
              ["Ishlab chiqaruvchilar", "Parchalovchilar", "Notirik tabiat"], x="Hayvonlar tayyor oziq iste’mol qiladi."),
            Q("Oziq zanjiri nimadan boshlanadi?", "Yashil o‘simlikdan", ["Yirtqichdan", "Zamburug‘dan", "Hasharotdan"],
              x="Oziq zanjirining birinchi halqasi — ishlab chiqaruvchi."),
            Q("Oziq zanjirini to‘ldiring: ... → quyon → bo‘ri", "O‘t", ["Tulki", "Burgut", "Qo‘ziqorin"],
              x="Quyon o‘t bilan oziqlanadi."),
            Q("Tulki oziq zanjirida qaysi guruhga kiradi?", "Iste’molchi", ["Ishlab chiqaruvchi", "Parchalovchi", "Notirik tabiat"],
              x="Tulki boshqa hayvonlarni yeydi — u iste’molchi."),
            Q("Ekotizimning notirik qismiga nima kiradi?", "Suv va tuproq", ["Daraxtlar", "Qushlar", "Zamburug‘lar"],
              x="Suv, havo, tuproq, yorug‘lik — notirik tabiat."),
            Q("Cho‘l ekotizimida yashovchi hayvon?", "Jayron", ["Pingvin", "Oq ayiq", "Kit"],
              x="Jayron issiq cho‘l va dashtlarda yashaydi."),
            TF("Ekotizim faqat hayvonlardan iborat.", False,
               x="Ekotizimga o‘simliklar, hayvonlar, zamburug‘lar, bakteriyalar hamda suv, havo, tuproq kiradi."),
            TF("O‘rmon — ekotizimga misol.", True, x="O‘rmonda daraxtlar, hayvonlar, zamburug‘lar tuproq, suv va havo bilan birga yashaydi."),
            ORDER(S, "Oziq zanjiri yashil o‘simlikdan boshlanadi"),
            Q("Oziq zanjirini to‘ldiring: o‘t → chigirtka → baqa → ...", "Ilon", ["Bug‘doy", "Sigir", "Qo‘ziqorin"], d=2,
              x="Ilon baqani ovlaydi."),
            Q("Qaysi biri tabiiy ekotizim?", "O‘rmon", ["Akvarium", "Bog‘", "Paxta dalasi"], d=2,
              x="O‘rmonni inson yaratmagan, bog‘, dala va akvarium esa sun’iy."),
            Q("Qaysi biri sun’iy ekotizim?", "Akvarium", ["O‘rmon", "Ko‘l", "Cho‘l"], d=2,
              x="Akvariumni inson yaratadi va parvarish qiladi."),
            Q("Ko‘lda baliqlar yo‘qolib ketsa, baliqxo‘r qushlar bilan nima bo‘ladi?", "Ozuqasiz qoladi",
              ["Ko‘payib ketadi", "Hech narsa bo‘lmaydi", "O‘txo‘rga aylanadi"], d=2,
              x="Ekotizimda hamma bir-biri bilan bog‘langan."),
            Q("Oziq zanjirida o‘txo‘r hayvon qaysi o‘rinda turadi?", "O‘simlikdan keyin",
              ["Zanjir boshida", "Yirtqichdan keyin", "Eng oxirida"], d=2,
              x="O‘txo‘r o‘simlikni yeydi, uni esa yirtqich yeydi."),
            Q("Qo‘ziqorin ekotizimda qanday vazifa bajaradi?", "Qoldiqlarni parchalaydi",
              ["Kislorod ishlab chiqaradi", "Hayvonlarni ovlaydi", "Yorug‘lik chiqaradi"], d=2,
              x="Zamburug‘lar parchalovchilar guruhiga kiradi."),
            Q("Ko‘l ekotizimida ishlab chiqaruvchi kim?", "Suv o‘tlari", ["Baliq", "Baqa", "O‘rdak"], d=2,
              x="Suv o‘tlari yashil, ular fotosintez qiladi."),
            TF("Parchalovchilar tuproqni unumdor qiladi.", True, d=2,
               x="Ular qoldiqlarni chiritib, mineral moddalarni tuproqqa qaytaradi."),
            TF("Ekotizimdagi energiyaning asosiy manbai — Quyosh.", True, d=2,
               x="O‘simliklar Quyosh energiyasini oziqqa aylantiradi, undan hamma foydalanadi."),
            MATCH("Tushunchani izohi bilan juftlang",
                  [("Ishlab chiqaruvchi", "oziqni o‘zi hosil qiladi"), ("Iste’molchi", "tayyor oziq yeydi"),
                   ("Parchalovchi", "qoldiqlarni chiritadi"), ("Ekotizim", "tiriklar va muhit birligi"),
                   ("Oziq zanjiri", "kim kimni yeyishi tartibi")], d=2),
            Q("To‘g‘ri oziq zanjirini toping", "Barg → qurt → chumchuq → qirg‘iy",
              ["Qirg‘iy → barg → chumchuq → qurt", "Chumchuq → qurt → qirg‘iy → barg", "Qurt → barg → qirg‘iy → chumchuq"], d=3,
              x="Qurt barg yeydi, chumchuq qurtni, qirg‘iy esa chumchuqni ovlaydi."),
            Q("Bir-biri bilan bog‘langan ko‘p oziq zanjirlari nima deyiladi?", "Oziq to‘ri",
              ["Oziq qopi", "Qo‘riqxona", "Hayvonot bog‘i"], d=3,
              x="Bir hayvon bir necha xil oziq yeydi, shuning uchun zanjirlar to‘r hosil qiladi."),
            Q("O‘rmondagi bo‘rilar butunlay yo‘qolsa, dastlab nima bo‘lishi mumkin?", "O‘txo‘rlar ko‘payib ketadi",
              ["Quyosh so‘nadi", "Suv ko‘payadi", "Tuproq toshga aylanadi"], d=3,
              x="O‘txo‘rlarni ovlaydigan yirtqich qolmaydi, ular ko‘payib, o‘simliklarni ko‘p yeydi."),
            TF("Parchalovchilar bo‘lmasa, yer qurigan barg va qoldiqlar bilan to‘lib ketardi.", True, d=3,
               x="Parchalovchilar tabiatni tozalab turadi."),
        ])

T.topic("ecology", "♻️", L("Ekologik muammolar va tabiatni asrash", "Environmental problems and protecting nature", "Экологические проблемы и охрана природы"),
        chapter=C4,
        theory="Inson faoliyati tabiatga ta’sir qiladi. Asosiy ekologik muammolar:\n"
               "• havo va suvning ifloslanishi, chiqindilarning ko‘payishi, o‘rmonlarning kesilishi, tuproqning sho‘rlanishi.\n"
               "• Orol dengizi fojiasi: Amudaryo va Sirdaryo suvi sug‘orishga ko‘p olingani sababli dengiz sayozlanib, katta qismi qurib qoldi, o‘rnida Orolqum cho‘li paydo bo‘ldi.\n"
               "Tabiatni asrash yo‘llari: daraxt ekish, suv va elektrni tejash, chiqindini saralab, qayta ishlash, quyosh va shamol energiyasidan foydalanish.\n"
               "Kamyob turlar Qizil kitobga kiritiladi, qo‘riqxona va milliy bog‘larda muhofaza qilinadi.",
        items=[
            Q("Orol dengiziga qaysi daryolar quyilgan?", "Amudaryo va Sirdaryo", ["Chirchiq va Zarafshon", "Volga va Ural", "Nil va Dunay"],
              x="Orol dengizi Amudaryo va Sirdaryo suvi bilan to‘lib turgan."),
            Q("Plastik chiqindini nima qilish kerak?", "Saralab, qayta ishlashga berish",
              ["Daryoga tashlash", "Yoqib yuborish", "Yerga ko‘mish"], x="Qayta ishlangan plastikdan yangi buyumlar yasaladi."),
            Q("Havoni nima ifloslantiradi?", "Zavod va mashinalar tutuni", ["Daraxtlar", "Yomg‘ir", "Shamol"],
              x="Tutun tarkibida zararli gazlar va chang bor."),
            Q("Qaysi odat tabiatni asraydi?", "Chiroqni o‘chirib chiqish",
              ["Chiqindini ko‘chaga tashlash", "Daraxt shoxlarini sindirish", "Gullarni uzish"],
              x="Elektrni tejash — tabiiy boyliklarni tejash."),
            Q("Qizil kitobga qanday turlar kiritiladi?", "Kamyob va yo‘qolib borayotgan",
              ["Eng ko‘p uchraydigan", "Faqat uy hayvonlari", "Faqat begona o‘tlar"],
              x="Qizil kitob kamyob turlarni asrash uchun tuziladi."),
            Q("Qaysi hayvon O‘zbekiston Qizil kitobiga kiritilgan?", "Jayron", ["Chumchuq", "Qarg‘a", "Kaptar"],
              x="Jayron — kamyob cho‘l hayvoni."),
            Q("Qo‘riqxonada nima taqiqlanadi?", "Ov qilish va daraxt kesish",
              ["Tabiatni o‘rganish", "Hayvonlarni kuzatish", "Qushlarni sanash"],
              x="Qo‘riqxonada tabiat o‘z holicha saqlanadi."),
            Q("Qaysi transport havoni eng kam ifloslaydi?", "Velosiped", ["Yuk mashinasi", "Avtobus", "Mototsikl"],
              x="Velosiped yoqilg‘i yoqmaydi va tutun chiqarmaydi."),
            TF("Plastik tabiatda juda uzoq vaqt parchalanmaydi.", True, x="Plastik yuzlab yillar davomida tabiatda qolishi mumkin."),
            TF("O‘rmonlarni kesish tabiatga foyda keltiradi.", False, x="O‘rmonlar kesilsa, havo ifloslanadi, hayvonlar uysiz qoladi."),
            TF("Orol dengizi hozir avvalgidan ancha kichik.", True, x="Dengizning katta qismi qurib qolgan."),
            TF("Bir tup daraxt ekish ham tabiatga katta yordam.", True, x="Har bir daraxt havoni tozalaydi va soya beradi."),
            ORDER(S, "Chiqindilarni saralab qayta ishlash kerak"),
            Q("Orol dengizi qurishining asosiy sababi nima?", "Daryo suvi sug‘orishga ko‘p olingani",
              ["Kuchli yomg‘irlar", "Zilzila", "Qor ko‘p yog‘gani"], d=2,
              x="Daryolar suvi dalalarga ko‘p olinib, dengizga kam yetib bordi."),
            Q("Orol dengizining qurigan tubida qanday cho‘l paydo bo‘ldi?", "Orolqum", ["Qizilqum", "Qoraqum", "Sahroi Kabir"], d=2,
              x="Qurigan dengiz tubi Orolqum cho‘liga aylandi."),
            Q("Qurigan Orol tubida qumni ushlab turish uchun qaysi o‘simlik ekilmoqda?", "Saksovul",
              ["Sholi", "Bug‘doy", "Tarvuz"], d=2, x="Saksovul sho‘r va quruq yerda o‘sa oladi."),
            Q("Suvni tejaydigan sug‘orish usuli qaysi?", "Tomchilatib sug‘orish",
              ["Egatlarni suvga bostirish", "Jo‘mrakni ochiq qoldirish", "Ko‘chani shlang bilan yuvish"], d=2,
              x="Tomchilatib sug‘orishda suv to‘g‘ridan-to‘g‘ri ildizga boradi."),
            Q("Qaysi chiqindilarni qayta ishlash mumkin?", "Qog‘oz, shisha, plastik", ["Hech qaysisini", "Faqat tosh", "Faqat chang"], d=2,
              x="Eski qog‘ozdan yangi qog‘oz, shishadan yangi shisha idish olinadi."),
            Q("“Qayta ishlash” nima degani?", "Eski buyumdan yangi mahsulot olish",
              ["Chiqindini yoqish", "Chiqindini ko‘mish", "Chiqindini daryoga tashlash"], d=2,
              x="Qayta ishlash tabiiy xomashyoni tejaydi."),
            Q("Ekologiya fani nimani o‘rganadi?", "Tiriklar va muhit aloqasini", ["Faqat yulduzlarni", "Faqat raqamlarni", "Faqat tillarni"], d=2,
              x="Ekologiya tirik organizmlarning bir-biri va muhit bilan bog‘liqligini o‘rganadi."),
            TF("Quyosh va shamol energiyasi havoni tutun bilan ifloslantirmaydi.", True, d=2,
               x="Ular yoqilg‘i yoqmasdan elektr ishlab chiqaradi."),
            MATCH("Muammoni yechimi bilan juftlang",
                  [("Havo ifloslanishi", "daraxt ekish"), ("Chiqindilar ko‘payishi", "qayta ishlash"),
                   ("Suv tanqisligi", "tomchilatib sug‘orish"), ("Kamyob hayvonlar yo‘qolishi", "qo‘riqxonalar tashkil etish"),
                   ("Ko‘mir va neftning tugashi", "quyosh va shamol energiyasi")], d=2),
            Q("Orol dengizi qurishi oqibatida nima kuzatildi?", "Tuzli chang bo‘ronlari",
              ["Baliqlar ko‘paydi", "Havo namlandi", "Yangi o‘rmonlar paydo bo‘ldi"], d=3,
              x="Shamol qurigan dengiz tubidan tuz va changni uchirib ketadi."),
            Q("Tuproq sho‘rlanishining sabablaridan biri qaysi?", "Haddan tashqari sug‘orish",
              ["Daraxt ekish", "Almashlab ekish", "Tuproqni yumshatish"], d=3,
              x="Ortiqcha suv yer ostidagi tuzlarni yuzaga olib chiqadi."),
        ])

T.test("test4", L("4-nazorat ishi", "Test 4", "Контрольная работа 4"),
       ["cell", "living", "ecosystem", "ecology"], chapter=C4)

T.test("final", L("Yillik takrorlash", "End-of-year review", "Итоговое повторение"),
       ["methods", "matter", "particles", "mixtures", "phenomena", "forces", "energy", "light_sound",
        "magnet_electric", "earth", "solar", "cell", "living", "ecosystem", "ecology"],
       chapter=C4, level=3)

T.write()
