"""Tabiiy fan, 3-sinf: assets/data/school/science_g3.json + bank_science_g3.json.

Mavzular O‘zbekiston maktab dasturi ("Tabiiy fan", 3-sinf) yo‘nalishida: tirik va notirik tabiat, o‘simliklar,
hayvonlar, inson tanasi va salomatlik, suv, havo, tuproq, Quyosh–Yer–Oy, O‘zbekiston tabiati.
Hamma qoida matnlari va savollar o‘zimizniki (darslikdan ko‘chirilmagan).
Qayta yaratish: python3 tool/content/school/science_g3.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from schoolkit import *  # noqa: E402,F403

T = Course("science", 3, L("Tabiiy fan", "Science", "Естествознание"))

C1 = "1-chorak. Tabiat va o‘simliklar"
C2 = "2-chorak. Hayvonlar olami"
C3 = "3-chorak. Inson va salomatlik"
C4 = "4-chorak. Suv, havo, Yer va Vatanimiz tabiati"

S = "So‘zlardan gap tuzing"

# ============================================================ 1-chorak
T.topic("nature", "🌳", L("Tirik va notirik tabiat", "Living and non-living nature", "Живая и неживая природа"),
        chapter=C1,
        theory="Tabiat — inson yaratmagan hamma narsa: o‘simliklar, hayvonlar, tosh, suv, havo, Quyosh.\n"
               "• Tirik tabiat: o‘simliklar, hayvonlar, zamburug‘lar va inson. Ular nafas oladi, oziqlanadi, o‘sadi va ko‘payadi.\n"
               "• Notirik tabiat: tosh, qum, suv, havo, Quyosh, Oy. Ular o‘smaydi va ko‘paymaydi.\n"
               "Inson yasagan narsalar (stol, mashina, uy) — buyumlar, ular tabiatga kirmaydi.\n"
               "Tirik tabiat notirik tabiatsiz yashay olmaydi: o‘simlikka suv, havo va yorug‘lik kerak.",
        items=[
            Q("Qaysi biri tirik tabiatga kiradi?", "Qush", ["Tosh", "Bulut", "Qum", "Muz"], e="🐦",
              x="Qush nafas oladi, oziqlanadi, o‘sadi va ko‘payadi — u tirik."),
            Q("Qaysi biri notirik tabiatga kiradi?", "Tosh", ["Mushuk", "Olma daraxti", "Qo‘ziqorin", "Chumoli"],
              x="Tosh o‘smaydi, nafas olmaydi va ko‘paymaydi."),
            Q("Qaysi biri inson yasagan buyum?", "Stul", ["Daraxt", "Daryo", "Tog‘", "Quyosh"],
              x="Stulni inson yasagan, u tabiatning bir qismi emas."),
            Q("Qaysi biri tabiatga kirmaydi?", "Mashina", ["Bulut", "Daryo", "Qor", "Chigirtka"],
              x="Mashinani inson yasagan — u buyum."),
            Q("Tirik organizmlarning belgisi qaysi?", "O‘sadi", ["Eriydi", "Sinadi", "Oqadi", "Yaltiraydi"],
              x="Tirik organizmlar o‘sadi, oziqlanadi, nafas oladi va ko‘payadi."),
            Q("Hamma tirik organizmlar nima qiladi?", "Oziqlanadi", ["Uchadi", "Suzadi", "Yuguradi", "Gapiradi"],
              x="Uchish yoki suzish hammaga xos emas, oziqlanish esa barcha tiriklarga xos."),
            Q("Qaysi biri ko‘payadi?", "Qo‘y", ["Qoya", "Qor", "Bulut", "Kamalak"],
              x="Qo‘y — tirik organizm, u bolalaydi, ya’ni ko‘payadi."),
            Q("Bulut qaysi tabiatga kiradi?", "Notirik tabiatga", ["Tirik tabiatga", "Inson yasagan buyumlarga", "Hayvonlarga"],
              x="Bulut — suv tomchilari, u tirik emas."),
            TF("Quyosh notirik tabiatga kiradi.", True, x="Quyosh nafas olmaydi, o‘smaydi va ko‘paymaydi."),
            TF("Tosh o‘sadi va ko‘payadi.", False, x="Tosh — notirik jism, u o‘smaydi ham, ko‘paymaydi ham."),
            TF("O‘simliklar ham nafas oladi.", True, x="Barcha tirik organizmlar, jumladan o‘simliklar ham nafas oladi."),
            TF("Havo notirik tabiatga kiradi.", True, x="Havo o‘smaydi va ko‘paymaydi — u notirik tabiat."),
            TF("Baliq notirik tabiatga kiradi.", False, x="Baliq nafas oladi, oziqlanadi va ko‘payadi — u tirik."),
            TF("Inson ham tirik tabiatning bir qismi.", True, x="Inson ham nafas oladi, oziqlanadi, o‘sadi."),
            MATCH("Har birini o‘z guruhi bilan juftlang",
                  [("Olma daraxti", "o‘simlik"), ("Mushuk", "hayvon"), ("Qo‘ziqorin", "zamburug‘"),
                   ("Tosh", "notirik jism"), ("Stol", "inson yasagan buyum")],
                  x="Olma daraxti — o‘simlik, mushuk — hayvon, qo‘ziqorin — zamburug‘, tosh — notirik, stol — buyum."),
            Q("Qo‘ziqorin tirikmi?", "Ha, u zamburug‘", ["Yo‘q, u tosh", "Yo‘q, u buyum", "Yo‘q, u suv"], d=2,
              x="Qo‘ziqorin — zamburug‘, u o‘sadi va ko‘payadi."),
            Q("Qaysi guruhda faqat tirik narsalar bor?", "Chumoli, terak, quyon",
              ["Tosh, suv, qum", "Quyon, tosh, bulut", "Qor, muz, bug‘", "Terak, qum, havo"], d=2,
              x="Chumoli, terak va quyon — tirik organizmlar."),
            Q("Qaysi guruhda faqat notirik narsalar bor?", "Qum, suv, havo",
              ["Qush, qum, suv", "Baliq, tosh, loy", "Gul, havo, muz", "Ari, bulut, qor"], d=2,
              x="Qum, suv va havo o‘smaydi, ko‘paymaydi."),
            Q("Qaysi so‘z ortiqcha: terak, lola, tosh, yalpiz?", "Tosh", ["Terak", "Lola", "Yalpiz"], d=2,
              x="Tosh — notirik, qolganlari — o‘simliklar."),
            Q("Qaysi so‘z ortiqcha: suv, qum, havo, chumchuq?", "Chumchuq", ["Suv", "Qum", "Havo"], d=2,
              x="Chumchuq — tirik qush, qolganlari notirik tabiat."),
            Q("Tirik organizmlar notiriklardan nimasi bilan farq qiladi?", "Ko‘payishi bilan",
              ["Rangi bilan", "Og‘irligi bilan", "Shakli bilan", "Kattaligi bilan"], d=2,
              x="Rang, og‘irlik, shakl notiriklarda ham bor, ko‘payish esa faqat tiriklarga xos."),
            Q("Quyosh tirik tabiatga nima beradi?", "Yorug‘lik va issiqlik", ["Suv va tuz", "Tuproq va tosh", "Sovuq va qor"], d=2,
              x="Quyosh yorug‘ligi va issiqligisiz o‘simlik va hayvonlar yashay olmaydi."),
            TF("Tirik tabiat notirik tabiat bilan bog‘liq.", True, d=2,
               x="Masalan, hayvonlar suv ichadi, o‘simliklar Quyosh nurida o‘sadi."),
            TF("Tirik organizmlar vaqt o‘tib nobud bo‘ladi.", True, d=2,
               x="Har bir tirik organizm tug‘iladi, o‘sadi, ko‘payadi va oxiri nobud bo‘ladi."),
            ORDER(S, "Tirik organizmlar oziqlanadi va o‘sadi", d=2),
            Q("Tuxumdan jo‘ja chiqishi tiriklarning qaysi belgisiga misol?", "Ko‘payish",
              ["Oziqlanish", "Nafas olish", "Harakat"], d=3,
              x="Tovuq tuxum qo‘yadi, undan jo‘ja chiqadi — bu ko‘payish."),
            Q("Kichik nihol yillar o‘tib katta daraxtga aylandi. Bu qaysi belgi?", "O‘sish",
              ["Nafas olish", "Oziqlanish", "Nobud bo‘lish"], d=3,
              x="Nihol kattalashdi — bu o‘sish."),
        ])

T.topic("plant_parts", "🌱", L("O‘simlik qismlari", "Parts of a plant", "Части растения"),
        chapter=C1,
        theory="Gulli o‘simlik qismlari: ildiz, poya, barg, gul, meva va urug‘.\n"
               "• Ildiz o‘simlikni tuproqda ushlab turadi, tuproqdan suv va mineral moddalarni shimib oladi.\n"
               "• Poya barg va gullarni ko‘tarib turadi, suv va oziqni o‘tkazadi.\n"
               "• Barg Quyosh nurida o‘simlik uchun oziq tayyorlaydi.\n"
               "• Guldan meva hosil bo‘ladi, meva ichida urug‘ yetiladi. Urug‘dan yangi o‘simlik unib chiqadi.",
        items=[
            Q("O‘simlikni tuproqda nima ushlab turadi?", "Ildiz", ["Barg", "Gul", "Meva", "Poya"],
              x="Ildiz tuproqqa kirib, o‘simlikni mahkam ushlaydi."),
            Q("Tuproqdan suvni qaysi qism shimib oladi?", "Ildiz", ["Barg", "Gul", "Urug‘"],
              x="Ildiz tuproqdan suv va mineral moddalarni shimib oladi."),
            Q("Barg va gullarni qaysi qism ko‘tarib turadi?", "Poya", ["Ildiz", "Urug‘", "Meva"],
              x="Poya o‘simlikning tayanchi, u barg va gullarni ko‘tarib turadi."),
            Q("Quyosh nurida oziqni asosan qaysi qism tayyorlaydi?", "Barg", ["Ildiz", "Urug‘", "Gul", "Meva"],
              x="Yashil barglar Quyosh nurida o‘simlik uchun oziq tayyorlaydi."),
            Q("Meva qaysi qismdan hosil bo‘ladi?", "Guldan", ["Ildizdan", "Bargdan", "Poyadan"],
              x="Gul changlangach, uning o‘rnida meva hosil bo‘ladi."),
            Q("Urug‘ning vazifasi nima?", "Yangi o‘simlik berish", ["Suv shimish", "Oziq tayyorlash", "Gulni ko‘tarish"],
              x="Urug‘ ekilsa, undan yangi o‘simlik unib chiqadi."),
            Q("Gulli o‘simliklarda urug‘ qayerda yetiladi?", "Meva ichida", ["Barg ustida", "Ildiz ichida", "Poya uchida"],
              x="Masalan, olma urug‘lari olma mevasining ichida bo‘ladi."),
            Q("Sabzining qaysi qismini yeymiz?", "Ildizini", ["Bargini", "Gulini", "Urug‘ini"], e="🥕",
              x="Sabzi — ildizmeva, biz uning yo‘g‘on ildizini yeymiz."),
            Q("Olmaning qaysi qismini yeymiz?", "Mevasini", ["Ildizini", "Bargini", "Poyasini"], e="🍎",
              x="Olma — olma daraxtining mevasi."),
            Q("O‘simlikning qaysi qismi ko‘pincha yashil bo‘ladi?", "Barg", ["Ildiz", "Urug‘", "Gul"],
              x="Barglar yashil rangda bo‘ladi va Quyosh nurini tutadi."),
            TF("Ildiz odatda yer ostida bo‘ladi.", True, x="Ildiz tuproq ichida o‘sadi."),
            TF("Barg tuproqdan suv shimib oladi.", False, x="Tuproqdan suvni ildiz shimib oladi, barg esa oziq tayyorlaydi."),
            TF("Guldan meva va urug‘ hosil bo‘ladi.", True, x="Gul o‘rnida meva paydo bo‘ladi, uning ichida urug‘ yetiladi."),
            MATCH("O‘simlik qismini vazifasi bilan juftlang",
                  [("Ildiz", "suv shimib oladi"), ("Poya", "barglarni ko‘tarib turadi"), ("Barg", "oziq tayyorlaydi"),
                   ("Gul", "undan meva hosil bo‘ladi"), ("Meva", "urug‘ni saqlaydi"), ("Urug‘", "yangi o‘simlik beradi")]),
            ORDER(S, "Ildiz tuproqdan suv shimib oladi"),
            Q("Karamning qaysi qismini yeymiz?", "Bargini", ["Ildizini", "Gulini", "Mevasini"], d=2,
              x="Karam boshi bir-biriga zich o‘ralgan barglardan iborat."),
            Q("Lavlagining qaysi qismini yeymiz?", "Ildizini", ["Gulini", "Mevasini", "Urug‘ini"], d=2,
              x="Lavlagi ham sabzi kabi ildizmeva."),
            Q("Kungaboqarning qaysi qismidan yog‘ olinadi?", "Urug‘idan", ["Ildizidan", "Bargidan", "Poyasidan"], d=2, e="🌻",
              x="Kungaboqar pistasi — uning urug‘i, undan o‘simlik yog‘i olinadi."),
            Q("Bug‘doyning qaysi qismidan un tortiladi?", "Donidan", ["Poyasidan", "Ildizidan", "Bargidan"], d=2,
              x="Bug‘doy donlari tegirmonda tortilib, un olinadi."),
            Q("Daraxtning yo‘g‘on poyasi nima deyiladi?", "Tana", ["Ildiz", "Shox", "Barg"], d=2,
              x="Daraxtning bitta yo‘g‘on yog‘och poyasi tana deyiladi."),
            Q("Asalari va kapalaklarni qaysi qism o‘ziga jalb qiladi?", "Gul", ["Ildiz", "Poya", "Urug‘"], d=2,
              x="Gulning rangi, hidi va shirasi hasharotlarni jalb qiladi, ular gulni changlatadi."),
            TF("Gul o‘simlikni chiroyli qilishdan boshqa vazifa bajarmaydi.", False, d=2,
               x="Guldan meva va urug‘ hosil bo‘ladi — bu o‘simlikning ko‘payishi uchun zarur."),
            TF("Poya orqali suv ildizdan barglarga yetib boradi.", True, d=2,
               x="Poya ichida suv va oziq harakatlanadigan yo‘llar bor."),
            Q("G‘o‘zaning paxta tolasi qayerda yetiladi?", "Ko‘sakda", ["Ildizda", "Bargda", "Poyada"], d=3,
              x="Ko‘sak — g‘o‘zaning mevasi, ichida urug‘ va oq tola bo‘ladi."),
            Q("Gul changlangandan keyin uning o‘rnida nima hosil bo‘ladi?", "Meva", ["Ildiz", "Barg", "Tana"], d=3,
              x="Changlangan gul o‘rnida meva, meva ichida urug‘ yetiladi."),
        ])

T.topic("plant_growth", "☀️", L("O‘simlik o‘sishi uchun sharoitlar", "What plants need to grow", "Условия для роста растений"),
        chapter=C1,
        theory="O‘simlik yaxshi o‘sishi uchun beshta sharoit kerak:\n"
               "• yorug‘lik, suv, havo, issiqlik va unumdor tuproq.\n"
               "Yorug‘lik yetmasa barglar sarg‘ayadi, suv yetmasa o‘simlik so‘lib qoladi, qattiq sovuqda muzlaydi.\n"
               "Urug‘ unib chiqishi uchun namlik, havo va issiqlik zarur.\n"
               "Xona o‘simliklarini derazaga yaqin qo‘yamiz va vaqtida sug‘oramiz.",
        items=[
            Q("O‘simlik o‘sishi uchun nima kerak?", "Yorug‘lik", ["Qorong‘ilik", "Shovqin", "Chang"],
              x="Yorug‘liksiz o‘simlik oziq tayyorlay olmaydi."),
            Q("Sug‘orilmagan o‘simlik bilan nima bo‘ladi?", "So‘lib qoladi", ["Tez o‘sadi", "Gullaydi", "Yashnab ketadi"],
              x="Suv yetmasa, o‘simlik so‘lib qoladi."),
            Q("O‘simlik qaysi joyda eng yaxshi o‘sadi?", "Yorug‘, iliq va nam joyda",
              ["Qorong‘i va sovuq joyda", "Quruq qum ustida", "Muz ustida"],
              x="O‘simlikka yorug‘lik, issiqlik va suv kerak."),
            Q("Qaysi faslda o‘simliklar tez o‘sa boshlaydi?", "Bahorda", ["Qishda", "Kech kuzda", "Qor yog‘ganda"],
              x="Bahorda havo iliydi, kunlar uzayadi — o‘simliklar uyg‘onadi."),
            Q("Qaysi biri o‘simlik o‘sishi uchun zarur EMAS?", "Shovqin", ["Suv", "Havo", "Issiqlik", "Yorug‘lik"],
              x="O‘simlikka suv, havo, issiqlik, yorug‘lik va tuproq kerak, shovqin emas."),
            TF("O‘simlikka yorug‘lik kerak emas.", False, x="Yorug‘liksiz o‘simlik oziq tayyorlay olmaydi va sarg‘ayadi."),
            TF("O‘simliklar ham havo bilan nafas oladi.", True, x="O‘simliklar ham tirik, ular nafas oladi."),
            TF("Xona o‘simligini derazaga yaqin qo‘ygan ma’qul.", True, x="Deraza yonida yorug‘lik ko‘p, o‘simlik yaxshi o‘sadi."),
            TF("Issiqlik ham o‘simlik o‘sishi uchun zarur.", True, x="Sovuqda o‘simliklar o‘smaydi, qattiq sovuqda muzlab qoladi."),
            TF("O‘simliklar qorong‘ida ham yaxshi o‘sib, gullaydi.", False, x="Qorong‘ida o‘simlik oziq tayyorlay olmaydi."),
            ORDER(S, "O‘simliklarga suv va yorug‘lik kerak"),
            Q("Qorong‘i shkafda qolgan o‘simlikning barglari qanday bo‘lib qoladi?", "Sarg‘ayib qoladi",
              ["Yashilroq bo‘ladi", "Qizarib ketadi", "Kattalashadi"], d=2,
              x="Yorug‘lik yetmasa, barglar rangsizlanib, sarg‘ayadi."),
            Q("Urug‘ unib chiqishi uchun nima zarur?", "Namlik, havo, issiqlik",
              ["Faqat qum", "Sovuq va qorong‘ilik", "Faqat shamol", "Tuz va muz"], d=2,
              x="Nam, iliq va havo bor joyda urug‘ unib chiqadi."),
            Q("Qishda issiqsevar o‘simliklar qayerda o‘stiriladi?", "Issiqxonada",
              ["Muzlatgichda", "Qor ostida", "Qorong‘i yerto‘lada"], d=2,
              x="Issiqxonada qishda ham issiq va yorug‘ bo‘ladi."),
            Q("Tuproqning qaysi xususiyati o‘simlik uchun muhim?", "Unumdorligi", ["Rangi", "Hidi", "Og‘irligi"], d=2,
              x="Unumdor tuproqda o‘simlik uchun oziq moddalar ko‘p."),
            Q("Ildiz tuproqdan nimani oladi?", "Suv va mineral moddalar", ["Yorug‘lik", "Quyosh nuri", "Shamol"], d=2,
              x="Yorug‘likni barglar tutadi, ildiz esa suv va mineral moddalarni oladi."),
            Q("Dehqonlar yerni nima uchun o‘g‘itlaydi?", "Tuproq unumdor bo‘lishi uchun",
              ["Yerni qotirish uchun", "Suvni quritish uchun", "Rangini o‘zgartirish uchun"], d=2,
              x="O‘g‘it tuproqqa o‘simlik uchun kerakli oziq moddalarni qo‘shadi."),
            Q("Bitta nihol yorug‘da, ikkinchisi qorong‘ida o‘sdi. Qaysi biri sog‘lomroq?", "Yorug‘dagisi",
              ["Qorong‘idagisi", "Ikkalasi bir xil", "Ikkalasi ham qurib qoladi"], d=2,
              x="Yorug‘da o‘sgan nihol yashil va baquvvat bo‘ladi."),
            Q("Loviya urug‘ini nam paxtaga qo‘ysak, bir necha kunda nima bo‘ladi?", "Unib chiqadi",
              ["Eriydi", "Toshga aylanadi", "Muzlaydi"], d=2,
              x="Namlik, havo va issiqlik bor — urug‘ unib chiqadi."),
            MATCH("Nima yetishmasa, nima bo‘ladi? Juftlang",
                  [("Suv yetmasa", "so‘lib qoladi"), ("Yorug‘lik yetmasa", "barglari sarg‘ayadi"),
                   ("Qattiq sovuq bo‘lsa", "muzlab qoladi"), ("Tuproq unumsiz bo‘lsa", "sust o‘sadi"),
                   ("Hamma sharoit bo‘lsa", "yaxshi o‘sadi")], d=2),
            TF("O‘simlikni juda ko‘p sug‘orish ham zararli.", True, d=2,
               x="Suv haddan ko‘p bo‘lsa, ildizlarga havo yetmaydi va ular chiriydi."),
            TF("Urug‘ quruq qutida uzoq tursa ham unib chiqmaydi.", True, d=2,
               x="Urug‘ unishi uchun namlik kerak, quruq joyda u unmaydi."),
            Q("Tomchilatib sug‘orish nima uchun foydali?", "Suvni tejaydi",
              ["Tuproqni sovitadi", "O‘simlikni quritadi", "Barglarni yuvadi"], d=3,
              x="Suv to‘g‘ridan-to‘g‘ri ildizga tomchilab boradi va isrof bo‘lmaydi."),
            Q("Yantoq kabi cho‘l o‘simliklari kam suvga qanday moslashgan?", "Ildizi juda uzun",
              ["Barglari juda katta", "Ildizi bo‘lmaydi", "Faqat suvda o‘sadi"], d=3,
              x="Yantoqning ildizi yer ostidagi suvgacha chuqur kirib boradi."),
        ])

T.topic("plant_kinds", "🌲", L("O‘simliklarning xilma-xilligi", "Kinds of plants", "Разнообразие растений"),
        chapter=C1,
        theory="• Daraxtning bitta yo‘g‘on yog‘och poyasi — tanasi bor: olma, terak, chinor, archa.\n"
               "• Butada yerdan bir nechta ingichka yog‘och poya o‘sib chiqadi: na’matak, atirgul.\n"
               "• O‘t o‘simliklarning poyasi yumshoq va yashil: bug‘doy, lola, yalpiz, beda.\n"
               "Madaniy o‘simliklarni inson ekib, parvarish qiladi: g‘o‘za, bug‘doy, uzum, olma.\n"
               "Yovvoyi o‘simliklar o‘z-o‘zidan o‘sadi: yantoq, qoqio‘t, shuvoq, saksovul.",
        items=[
            Q("Qaysi biri daraxt?", "Terak", ["Na’matak", "Lola", "Yalpiz", "Beda"],
              x="Terakning bitta baland va yo‘g‘on tanasi bor."),
            Q("Qaysi biri buta?", "Na’matak", ["Chinor", "Bug‘doy", "Terak", "Lola"],
              x="Na’matakda yerdan bir nechta ingichka yog‘och poya o‘sib chiqadi."),
            Q("Qaysi biri o‘t o‘simlik?", "Lola", ["Olma", "Chinor", "Archa", "O‘rik"],
              x="Lolaning poyasi yumshoq va yashil."),
            Q("O‘t o‘simliklarning poyasi qanday?", "Yumshoq va yashil",
              ["Yo‘g‘on va yog‘och", "Qalin po‘stloqli", "Tosh kabi qattiq"],
              x="O‘t o‘simliklar poyasi yog‘ochlanmaydi, u yumshoq bo‘ladi."),
            Q("Qaysi biri madaniy o‘simlik?", "G‘o‘za", ["Yantoq", "Shuvoq", "Qoqio‘t", "Saksovul"],
              x="G‘o‘zani dehqonlar ekib, parvarish qiladi."),
            Q("Qaysi biri yovvoyi o‘simlik?", "Yantoq", ["Bug‘doy", "Uzum", "Sholi", "Karam"],
              x="Yantoqni hech kim ekmaydi, u cho‘lda o‘z-o‘zidan o‘sadi."),
            Q("Madaniy o‘simliklarni kim parvarish qiladi?", "Inson", ["Hech kim", "Shamol", "Hayvonlar"],
              x="Madaniy o‘simliklarni inson ekadi, sug‘oradi va hosilini yig‘adi."),
            Q("O‘zbekistonda ko‘p ekiladigan, tolasidan gazlama to‘qiladigan o‘simlik?", "G‘o‘za",
              ["Lola", "Yantoq", "Archa"], x="G‘o‘za tolasi — paxta, undan ip va gazlama olinadi."),
            TF("Archa qishda ham yashil turadi.", True, x="Archaning barglari — ignalar, ular qishda to‘kilmaydi."),
            TF("Olma daraxti kuzda barglarini to‘kadi.", True, x="Ko‘p daraxtlar kuzda barglarini to‘kadi."),
            TF("Yovvoyi o‘simliklarni inson ekib, sug‘oradi.", False, x="Yovvoyi o‘simliklar o‘z-o‘zidan o‘sadi."),
            ORDER(S, "Chinor katta va baland daraxt"),
            Q("Daraxtning butadan farqi nima?", "Bitta yo‘g‘on tanasi bor",
              ["Barglari yo‘q", "Poyasi yumshoq", "Ildizi bo‘lmaydi"], d=2,
              x="Daraxtda bitta tana, butada esa bir nechta ingichka poya bo‘ladi."),
            Q("Qaysi guruhda faqat daraxtlar bor?", "Olma, o‘rik, yong‘oq",
              ["Lola, olma, beda", "Na’matak, lola, yalpiz", "Bug‘doy, chinor, rayhon"], d=2,
              x="Olma, o‘rik va yong‘oqning bitta yo‘g‘on tanasi bor."),
            Q("Qaysi guruhda faqat o‘t o‘simliklar bor?", "Bug‘doy, lola, rayhon",
              ["Terak, lola, yalpiz", "Archa, chinor, tut", "Olma, beda, na’matak"], d=2,
              x="Bug‘doy, lola va rayhonning poyasi yumshoq."),
            Q("Guruch qaysi o‘simlikdan olinadi?", "Sholidan", ["Bug‘doydan", "Makkajo‘xoridan", "G‘o‘zadan"], d=2,
              x="Sholi — suvli dalalarda ekiladigan madaniy o‘simlik."),
            Q("Qaysi o‘simlikning barglari igna shaklida?", "Archa", ["Olma", "Chinor", "Tut"], d=2,
              x="Archa — ignabargli daraxt."),
            Q("Qovun qaysi ekinlar guruhiga kiradi?", "Poliz ekinlariga", ["Mevali daraxtlarga", "Butalarga", "Yovvoyi o‘tlarga"], d=2,
              x="Qovun, tarvuz, qovoq — poliz ekinlari."),
            Q("Bahorda adirlarda qip-qizil bo‘lib ochiladigan o‘t o‘simlik?", "Lola", ["Paxta", "Bug‘doy", "Karam"], d=2,
              x="Bahorda tog‘ va adirlarda lolalar ochiladi."),
            MATCH("Madaniy o‘simlikni undan olinadigan mahsulot bilan juftlang",
                  [("G‘o‘za", "paxta tolasi"), ("Bug‘doy", "un"), ("Sholi", "guruch"), ("Uzum", "mayiz"),
                   ("Kungaboqar", "o‘simlik yog‘i")], d=2),
            TF("Butaning bitta yo‘g‘on tanasi bo‘ladi.", False, d=2,
               x="Butada yerdan bir nechta ingichka poya o‘sib chiqadi."),
            TF("Bog‘dagi mevali daraxtlar — madaniy o‘simliklar.", True, d=2,
               x="Ularni bog‘bon ekadi va parvarish qiladi."),
            Q("Cho‘lda o‘sadigan, qumni mustahkamlaydigan yovvoyi o‘simlik?", "Saksovul",
              ["Pomidor", "Sholi", "Karam"], d=3,
              x="Saksovul ildizlari qumni ushlab turadi, shamol uni uchira olmaydi."),
            Q("Qaysi daraxtning bargi bilan ipak qurti oziqlanadi?", "Tut", ["Terak", "Archa", "Chinor"], d=3,
              x="Ipak qurti tut barglarini yeydi va pilla o‘raydi."),
        ])

T.test("test1", L("1-nazorat ishi", "Test 1", "Контрольная работа 1"),
       ["nature", "plant_parts", "plant_growth", "plant_kinds"], chapter=C1)

# ============================================================ 2-chorak
T.topic("animal_groups", "🐾", L("Hayvonlar guruhlari", "Animal groups", "Группы животных"),
        chapter=C2,
        theory="• Sutemizuvchilar bolasini sut bilan boqadi, ko‘pchiligining tanasi jun bilan qoplangan: sigir, it, quyon, delfin.\n"
               "• Qushlarning pati, qanoti va tumshug‘i bor, ular tuxum qo‘yadi: chumchuq, burgut, tovuq.\n"
               "• Baliqlar suvda yashaydi, tangachasi va suzgichlari bor, jabra bilan nafas oladi.\n"
               "• Hasharotlarning 6 ta oyog‘i bor: asalari, kapalak, chumoli.\n"
               "• Sudralib yuruvchilarning terisi quruq, tangachali: ilon, kaltakesak, toshbaqa.\n"
               "• Suvda hamda quruqlikda yashovchilarning terisi nam va silliq: baqa.",
        items=[
            Q("Bolasini sut bilan boqadigan hayvonlar qaysi guruhga kiradi?", "Sutemizuvchilar",
              ["Qushlar", "Baliqlar", "Hasharotlar"], x="Sigir, it, quyon bolasini sut bilan boqadi."),
            Q("Tanasi pat bilan qoplangan hayvonlar qaysi guruhga kiradi?", "Qushlar",
              ["Baliqlar", "Sutemizuvchilar", "Hasharotlar"], x="Patlar faqat qushlarda bo‘ladi."),
            Q("Jabra bilan nafas oladigan hayvonlar qaysi guruhga kiradi?", "Baliqlar",
              ["Qushlar", "Sutemizuvchilar", "Sudralib yuruvchilar"],
              x="Baliqlar suvdagi havoni jabra orqali oladi."),
            Q("Hasharotning nechta oyog‘i bor?", "6 ta", ["4 ta", "8 ta", "10 ta"],
              x="Barcha hasharotlarning 6 ta oyog‘i bor."),
            Q("Qaysi biri hasharot?", "Asalari", ["O‘rgimchak", "Chumchuq", "Baqa", "Ilon"], e="🐝",
              x="Asalarining 6 ta oyog‘i bor — u hasharot."),
            Q("Qaysi biri sudralib yuruvchi?", "Kaltakesak", ["Baqa", "Laqqa", "Chumoli", "Quyon"],
              x="Kaltakesakning terisi quruq va tangachali."),
            Q("Qaysi biri sutemizuvchi?", "Tuya", ["Tovuq", "Toshbaqa", "Zog‘ora baliq"], e="🐫",
              x="Tuya bo‘tasini sut bilan boqadi."),
            Q("Qushlar tanasini nima qoplab turadi?", "Pat", ["Jun", "Tangacha", "Shilliq teri"],
              x="Qushlar tanasi pat bilan qoplangan."),
            Q("Baliqlar suvda nima yordamida suzadi?", "Suzgichlar", ["Qanotlar", "Oyoqlar", "Tumshuq"],
              x="Baliq suzgichlari va dumi yordamida suzadi."),
            TF("Ilonning oyog‘i yo‘q, u sudralib harakatlanadi.", True,
               x="Ilon — sudralib yuruvchi, u tanasini egib harakatlanadi."),
            MATCH("Hayvonni guruhi bilan juftlang",
                  [("Sigir", "sutemizuvchi"), ("Burgut", "qush"), ("Laqqa", "baliq"), ("Kapalak", "hasharot"),
                   ("Ilon", "sudralib yuruvchi"), ("Baqa", "suvda hamda quruqlikda yashovchi")]),
            Q("Qaysi biri suvda hamda quruqlikda yashovchi?", "Baqa", ["Ilon", "Laqqa", "Kaltakesak", "Chumoli"], d=2,
              x="Baqa suvda ham, quruqlikda ham yashaydi, terisi nam va silliq."),
            Q("Qaysi biri qush?", "Laylak", ["Ko‘rshapalak", "Kapalak", "Ninachi"], d=2,
              x="Laylakning pati va tumshug‘i bor, u tuxum qo‘yadi."),
            Q("Baqa tuxumini qayerga qo‘yadi?", "Suvga", ["Daraxtga", "Qumga", "Qush iniga"], d=2,
              x="Baqa tuxumlarini suvga qo‘yadi, bolalari ham suvda o‘sadi."),
            Q("Qaysi hayvonning terisi nam va silliq?", "Baqa", ["Ilon", "Kaltakesak", "Toshbaqa"], d=2,
              x="Sudralib yuruvchilarning terisi quruq, baqaniki esa nam."),
            TF("O‘rgimchak — hasharot.", False, d=2, x="O‘rgimchakning 8 ta oyog‘i bor, hasharotlarniki esa 6 ta."),
            TF("Delfin — sutemizuvchi hayvon.", True, d=2,
               x="Delfin suvda yashasa ham, bolasini sut bilan boqadi va o‘pka bilan nafas oladi."),
            TF("Pingvin ucha olmasa ham qush hisoblanadi.", True, d=2,
               x="Pingvinning pati, qanoti, tumshug‘i bor va u tuxum qo‘yadi."),
            TF("Kit — baliq.", False, d=2, x="Kit o‘pka bilan nafas oladi va bolasini sut bilan boqadi — u sutemizuvchi."),
            MATCH("Guruhni belgisi bilan juftlang",
                  [("Qushlar", "pat va qanot"), ("Baliqlar", "tangacha va suzgich"), ("Hasharotlar", "6 ta oyoq"),
                   ("Sutemizuvchilar", "bolasini sut bilan boqadi"), ("Sudralib yuruvchilar", "quruq tangachali teri")], d=2),
            ORDER(S, "Qushlar tuxum qo‘yib jo‘ja ochadi", d=2),
            TF("Ko‘rshapalak — qush.", False, d=3,
               x="Ko‘rshapalak ucha oladi, lekin bolasini sut bilan boqadi — u sutemizuvchi."),
            Q("Toshbaqa qaysi guruhga kiradi?", "Sudralib yuruvchilar",
              ["Suvda hamda quruqlikda yashovchilar", "Baliqlar", "Hasharotlar"], d=3,
              x="Toshbaqaning terisi quruq, kosasi bor, u quruqlikka tuxum qo‘yadi — u sudralib yuruvchi."),
            Q("Hasharot tanasi nechta qismdan iborat?", "3 ta", ["2 ta", "5 ta", "6 ta"], d=3,
              x="Hasharot tanasi bosh, ko‘krak va qorindan iborat."),
            Q("Qaysi biri baliq?", "Cho‘rtan", ["Delfin", "Kit", "Baqa"], d=3,
              x="Cho‘rtan jabra bilan nafas oladi, delfin va kit esa sutemizuvchilar."),
        ])

T.topic("animal_food", "🦊", L("Hayvonlarning oziqlanishi", "How animals feed", "Питание животных"),
        chapter=C2,
        theory="Hayvonlar nima yeyishiga qarab uch guruhga bo‘linadi:\n"
               "• O‘txo‘rlar o‘simlik bilan oziqlanadi: quyon, sigir, qo‘y, jayron.\n"
               "• Yirtqichlar boshqa hayvonlarni ovlaydi: bo‘ri, sher, burgut.\n"
               "• Hammaxo‘rlar ham o‘simlik, ham hayvon bilan oziqlanadi: ayiq, qarg‘a.\n"
               "Oziq zanjiri: o‘simlik → o‘txo‘r → yirtqich. Masalan: o‘t → quyon → tulki.\n"
               "Oziq zanjiri doimo o‘simlikdan boshlanadi.",
        items=[
            Q("Quyon nima bilan oziqlanadi?", "O‘simlik bilan", ["Baliq bilan", "Go‘sht bilan", "Hasharot bilan"], e="🐰",
              x="Quyon — o‘txo‘r, u o‘t, barg va sabzavot yeydi."),
            Q("Qaysi hayvon yirtqich?", "Bo‘ri", ["Quyon", "Sigir", "Qo‘y", "Echki"], e="🐺",
              x="Bo‘ri boshqa hayvonlarni ovlaydi."),
            Q("Qaysi hayvon o‘txo‘r?", "Qo‘y", ["Bo‘ri", "Sher", "Burgut", "Tulki"],
              x="Qo‘y o‘t va pichan bilan oziqlanadi."),
            Q("Oziq zanjiri nimadan boshlanadi?", "O‘simlikdan", ["Yirtqichdan", "Toshdan", "Hasharotdan"],
              x="Har qanday oziq zanjiri o‘simlikdan boshlanadi."),
            Q("Burgut nima bilan oziqlanadi?", "Mayda hayvonlar bilan", ["O‘t bilan", "Barg bilan", "Don bilan"], e="🦅",
              x="Burgut — yirtqich qush, u kemiruvchilar va boshqa hayvonlarni ovlaydi."),
            Q("Qaysi hayvonlar o‘simliklarni yeydi?", "O‘txo‘rlar", ["Yirtqichlar", "Ilonlar", "Burgutlar"],
              x="O‘txo‘rlar faqat o‘simlik bilan oziqlanadi."),
            Q("Qaysi biri yirtqich qush?", "Burgut", ["Tovuq", "Kaptar", "Musicha"],
              x="Burgutning o‘tkir tumshug‘i va tirnoqlari bor."),
            TF("Sher — o‘txo‘r hayvon.", False, x="Sher — yirtqich, u boshqa hayvonlarni ovlaydi."),
            TF("Sigir o‘t va pichan bilan oziqlanadi.", True, x="Sigir — o‘txo‘r hayvon."),
            TF("Hammaxo‘r hayvonlar faqat go‘sht yeydi.", False,
               x="Hammaxo‘rlar ham o‘simlik, ham hayvon bilan oziqlanadi."),
            ORDER(S, "Quyon o‘t va sabzi yeydi"),
            Q("Qaysi hayvon hammaxo‘r?", "Ayiq", ["Sigir", "Quyon", "Jayron", "Ot"], d=2, e="🐻",
              x="Ayiq baliq, asal, meva va rezavorlarni ham yeydi."),
            Q("Oziq zanjirini to‘ldiring: o‘t → quyon → ...", "Tulki", ["Sigir", "Qo‘y", "Chumchuq"], d=2,
              x="Tulki quyonni ovlaydi."),
            Q("Oziq zanjirini to‘ldiring: ... → chigirtka → baqa", "O‘t", ["Ilon", "Burgut", "Tosh"], d=2,
              x="Chigirtka o‘t yeydi, baqa esa chigirtkani yeydi."),
            Q("Yirtqich hayvonlarning qanday belgisi bor?", "O‘tkir tishlari va tirnoqlari",
              ["Tuyoqlari", "Uzun qulog‘i", "Yumshoq tumshug‘i"], d=2,
              x="O‘tkir tish va tirnoqlar ov qilishga yordam beradi."),
            Q("Jayron nima bilan oziqlanadi?", "O‘simliklar bilan", ["Baliqlar bilan", "Qushlar bilan", "Hasharotlar bilan"], d=2,
              x="Jayron — o‘txo‘r, u cho‘l o‘tlarini yeydi."),
            Q("Qaysi qush uchib yurib chivin va pashshalarni tutadi?", "Qaldirg‘och", ["Tovuq", "Kaptar", "Tuyaqush"], d=2,
              x="Qaldirg‘och havoda uchayotgan hasharotlarni tutib yeydi."),
            Q("Qaysi biri ortiqcha: ho‘kiz, qo‘y, echki, bo‘ri?", "Bo‘ri", ["Ho‘kiz", "Qo‘y", "Echki"], d=2,
              x="Bo‘ri — yirtqich, qolganlari o‘txo‘r."),
            MATCH("Hayvonni uning ozig‘i bilan juftlang",
                  [("Sigir", "o‘t"), ("Mushuk", "sichqon"), ("Ipak qurti", "tut bargi"), ("Asalari", "gul shirasi"),
                   ("Laylak", "baqa"), ("Qaldirg‘och", "chivin")], d=2),
            TF("Oziq zanjiri doimo o‘simlikdan boshlanadi.", True, d=2,
               x="O‘simlik o‘zi oziq tayyorlaydi, hayvonlar esa tayyor oziq yeydi."),
            TF("O‘txo‘r hayvonlar yirtqichlar uchun ozuqa bo‘ladi.", True, d=2,
               x="Masalan, quyonni tulki, jayronni bo‘ri ovlaydi."),
            Q("To‘g‘ri oziq zanjirini toping", "Barg → qurt → chumchuq",
              ["Chumchuq → barg → qurt", "Qurt → chumchuq → barg", "Chumchuq → qurt → barg"], d=3,
              x="Qurt barg yeydi, chumchuq esa qurtni yeydi."),
            Q("Dalada sichqonlar ko‘payib ketsa, qaysi qush foyda keltiradi?", "Boyqush",
              ["Tovuq", "Kaptar", "Musicha"], d=3,
              x="Boyqush — yirtqich qush, u kechasi sichqonlarni ovlaydi."),
        ])

T.topic("animal_home", "🐄", L("Uy va yovvoyi hayvonlar", "Domestic and wild animals", "Домашние и дикие животные"),
        chapter=C2,
        theory="Uy hayvonlarini inson boqadi va parvarish qiladi, ular insonga foyda keltiradi:\n"
               "• sigir — sut, qo‘y — jun va go‘sht, tovuq — tuxum, asalari — asal, ipak qurti — pilla.\n"
               "• It uyni qo‘riqlaydi, ot va eshak yuk tashiydi, tuya — “cho‘l kemasi”.\n"
               "Yovvoyi hayvonlar tabiatda o‘zi oziq topib yashaydi: bo‘ri, tulki, ayiq, jayron, burgut.\n"
               "Uy hayvonlariga mehr bilan qarash, ularni vaqtida boqish va sug‘orish kerak.",
        items=[
            Q("Qaysi biri uy hayvoni?", "Sigir", ["Bo‘ri", "Tulki", "Ayiq", "Jayron"],
              x="Sigirni inson boqadi, u sut beradi."),
            Q("Qaysi biri yovvoyi hayvon?", "Tulki", ["Mushuk", "Qo‘y", "Echki", "Ot"],
              x="Tulki tabiatda o‘zi oziq topib yashaydi."),
            Q("Sigir insonga nima beradi?", "Sut", ["Asal", "Jun", "Tuxum"], e="🐄", x="Sigir sut va go‘sht beradi."),
            Q("Asalni qaysi hasharot beradi?", "Asalari", ["Chumoli", "Pashsha", "Kapalak"], e="🐝",
              x="Asalarilar gul shirasidan asal tayyorlaydi."),
            Q("Jun qaysi hayvondan olinadi?", "Qo‘ydan", ["Tovuqdan", "Baliqdan", "Asalaridan"], e="🐑",
              x="Qo‘y junidan ip yigiriladi, kiyim to‘qiladi."),
            Q("Tuxumni qaysi uy parrandasi beradi?", "Tovuq", ["Sigir", "Echki", "It"], e="🐔",
              x="Tovuq — uy parrandasi, u tuxum qo‘yadi."),
            Q("Qaysi hayvon “cho‘l kemasi” deb ataladi?", "Tuya", ["Ot", "Eshak", "Sigir"], e="🐫",
              x="Tuya cho‘lda og‘ir yuklarni uzoq masofaga tashiydi."),
            Q("Uyni qo‘riqlashda qaysi hayvon yordam beradi?", "It", ["Quyon", "Tovuq", "Qo‘y"],
              x="It — insonning sodiq do‘sti va qo‘riqchisi."),
            Q("Uy hayvonini qanday parvarish qilish kerak?", "Vaqtida boqib, sug‘orish",
              ["Och qoldirish", "Qo‘rqitish", "Qarovsiz tashlab qo‘yish"],
              x="Uy hayvonlariga mehr bilan qarash kerak."),
            Q("Qaysi hayvon yuk tashishda yordam beradi?", "Eshak", ["Mushuk", "Tovuq", "Asalari"],
              x="Eshak va ot qadimdan yuk tashishda yordam beradi."),
            TF("Yovvoyi hayvonlar ozuqani o‘zi topadi.", True, x="Yovvoyi hayvonlarni hech kim boqmaydi."),
            TF("Bo‘ri — uy hayvoni.", False, x="Bo‘ri — yovvoyi yirtqich hayvon."),
            TF("Uy hayvonlarini inson parvarish qiladi.", True, x="Inson ularni boqadi, sug‘oradi, joy qilib beradi."),
            MATCH("Uy hayvonini foydasi bilan juftlang",
                  [("Sigir", "sut"), ("Qo‘y", "jun"), ("Tovuq", "tuxum"), ("Asalari", "asal"), ("Ipak qurti", "pilla"),
                   ("It", "uyni qo‘riqlaydi")]),
            ORDER(S, "Sigir bizga sut beradi"),
            Q("Pilla qaysi hasharotdan olinadi?", "Ipak qurtidan", ["Asalaridan", "Chumolidan", "Ninachidan"], d=2,
              x="Ipak qurti pilla o‘raydi, pilladan ipak tola olinadi."),
            Q("Baland tog‘larda yashovchi yovvoyi hayvon?", "Qor qoploni", ["Sigir", "Tovuq", "Mushuk"], d=2,
              x="Qor qoploni tog‘ qoyalarida yashaydi."),
            Q("Qaysi guruhda faqat uy hayvonlari bor?", "Ot, echki, tovuq",
              ["Bo‘ri, ot, tovuq", "Tulki, ayiq, jayron", "Echki, burgut, qo‘y"], d=2,
              x="Ot, echki va tovuqni inson boqadi."),
            Q("Qaysi guruhda faqat yovvoyi hayvonlar bor?", "Bo‘ri, tulki, jayron",
              ["Sigir, tulki, qo‘y", "Mushuk, it, tovuq", "Ot, bo‘ri, eshak"], d=2,
              x="Bo‘ri, tulki va jayron tabiatda erkin yashaydi."),
            Q("Qaysi hayvon qishda inida uxlab chiqadi?", "Ayiq", ["Bo‘ri", "Tulki", "Quyon"], d=2,
              x="Ayiq kuzda ko‘p yeb semiradi va qish bo‘yi inida uxlaydi."),
            Q("Mushuk uyda qanday foyda keltiradi?", "Sichqon tutadi", ["Sut beradi", "Jun beradi", "Tuxum qo‘yadi"], d=2,
              x="Mushuk uy va omborlarda sichqonlarni tutadi."),
            TF("Tuya uzoq vaqt suv ichmasdan yura oladi.", True, d=2,
               x="Shuning uchun tuya cho‘lda yuk tashishga juda mos."),
            TF("Laylak va qaldirg‘och kuzda issiq o‘lkalarga uchib ketadi.", True, d=2,
               x="Ular bahorda yana qaytib keladi."),
            Q("Ko‘p yovvoyi hayvonlar qishga qanday tayyorlanadi?", "Juni qalinlashadi",
              ["Juni to‘kilib ketadi", "Suvga ko‘chib o‘tadi", "Uxlamay qo‘yadi"], d=3,
              x="Kuzga kelib quyon, tulki kabi hayvonlarning juni qalin va issiq bo‘ladi."),
        ])

T.test("test2", L("2-nazorat ishi", "Test 2", "Контрольная работа 2"),
       ["animal_groups", "animal_food", "animal_home"], chapter=C2)

# ============================================================ 3-chorak
T.topic("body_senses", "👀", L("Inson tanasi va sezgi a’zolari", "Human body and senses", "Тело человека и органы чувств"),
        chapter=C3,
        theory="Inson tanasi qismlari: bosh, bo‘yin, gavda, qo‘llar va oyoqlar.\n"
               "Atrofimizni 5 ta sezgi a’zosi orqali bilamiz:\n"
               "• ko‘z — ko‘ramiz, quloq — eshitamiz, burun — hid bilamiz;\n"
               "• til — ta’m bilamiz, teri — issiq-sovuqni, og‘riqni, silliq va g‘adir-budurni sezamiz.\n"
               "Sezgi a’zolarini asrang: kitobni yorug‘ joyda o‘qing, qattiq shovqindan saqlaning.",
        items=[
            Q("Qaysi a’zo bilan ko‘ramiz?", "Ko‘z", ["Quloq", "Burun", "Til"], e="👀", x="Ko‘z — ko‘rish a’zosi."),
            Q("Qaysi a’zo bilan eshitamiz?", "Quloq", ["Ko‘z", "Til", "Teri"], e="👂", x="Quloq — eshitish a’zosi."),
            Q("Gulning hidini qaysi a’zo sezadi?", "Burun", ["Ko‘z", "Quloq", "Teri"], e="👃", x="Burun — hid bilish a’zosi."),
            Q("Limonning nordonligini qaysi a’zo sezadi?", "Til", ["Burun", "Quloq", "Ko‘z"], e="🍋",
              x="Til — ta’m bilish a’zosi."),
            Q("Issiq va sovuqni qaysi a’zo sezadi?", "Teri", ["Ko‘z", "Quloq", "Burun"],
              x="Teri issiq-sovuqni, og‘riqni va tegishni sezadi."),
            Q("Insonda nechta sezgi a’zosi bor?", "5 ta", ["3 ta", "4 ta", "7 ta"],
              x="Ko‘z, quloq, burun, til va teri — 5 ta sezgi a’zosi."),
            Q("Qo‘ng‘iroq ovozini qaysi a’zo bilan eshitamiz?", "Quloq", ["Til", "Burun", "Teri"], e="🔔",
              x="Tovushni quloq qabul qiladi."),
            Q("Ko‘zni asrash uchun nima qilish kerak?", "Yorug‘ joyda o‘qish",
              ["Uzoq vaqt telefonga qarash", "Ko‘zni iflos qo‘l bilan ishqalash", "Quyoshga tik qarash"],
              x="Qorong‘ida o‘qish va ekranga uzoq qarash ko‘zni charchatadi."),
            Q("Qattiq shovqin qaysi a’zoga zarar yetkazadi?", "Quloqqa", ["Tilga", "Burunga", "Tirnoqqa"],
              x="Qattiq shovqin eshitishni susaytiradi."),
            TF("Til yordamida shirin, achchiq, nordon va sho‘r ta’mni bilamiz.", True, x="Til — ta’m bilish a’zosi."),
            TF("Quloq yordamida ranglarni ajratamiz.", False, x="Ranglarni ko‘z bilan ajratamiz."),
            TF("Kitobni qorong‘ida o‘qish ko‘zga zarar.", True, x="Kitobni yorug‘ joyda o‘qish kerak."),
            MATCH("Sezgi a’zosini vazifasi bilan juftlang",
                  [("Ko‘z", "ko‘rish"), ("Quloq", "eshitish"), ("Burun", "hid bilish"), ("Til", "ta’m bilish"),
                   ("Teri", "tegishni sezish")]),
            ORDER(S, "Biz ko‘zimiz bilan ko‘ramiz"),
            Q("Qaysi biri sezgi a’zosi emas?", "Tizza", ["Ko‘z", "Burun", "Til"], d=2,
              x="Tizza — oyoqning bir qismi, u sezgi a’zosi emas."),
            Q("Tana qismlari qaysi qatorda to‘g‘ri berilgan?", "Bosh, bo‘yin, gavda, qo‘l, oyoq",
              ["Bosh, ildiz, barg, oyoq", "Qanot, dum, bosh, gavda", "Poya, gavda, qo‘l, gul"], d=2,
              x="Ildiz, barg, poya — o‘simlik qismlari, qanot — qushniki."),
            Q("Qaysi a’zolar juft?", "Ko‘z va quloq", ["Burun va til", "Til va bosh", "Burun va bo‘yin"], d=2,
              x="Insonda ikkita ko‘z va ikkita quloq bor."),
            Q("Tutun hidini sezib, xavf haqida bilamiz. Bunga qaysi a’zo yordam beradi?", "Burun",
              ["Til", "Quloq", "Teri"], d=2, x="Burun hidni sezadi va bizni ogohlantiradi."),
            Q("Quloqni asrash uchun nima qilmaslik kerak?", "Quloqqa o‘tkir narsa tiqish",
              ["Quloqni yuvish", "Sovuqda telpak kiyish", "Musiqani past ovozda tinglash"], d=2,
              x="O‘tkir narsa quloq pardasini shikastlashi mumkin."),
            TF("Teri tanamizni himoya qiladi.", True, d=2, x="Teri tanaga chang va mikroblar kirishiga to‘sqinlik qiladi."),
            Q("Ko‘zi ojiz odamlar maxsus kitoblarni qanday o‘qiydi?", "Barmoqlari bilan sezib",
              ["Hidlab", "Tatib ko‘rib", "Quloq bilan"], d=3,
              x="Ular bo‘rtma nuqtalardan iborat yozuvni barmoq terisi bilan sezib o‘qiydi."),
            Q("Burun hid bilishdan tashqari yana nima qiladi?", "Havoni tozalab, isitadi",
              ["Ovqatni chaynaydi", "Tovushni eshitadi", "Ranglarni ko‘radi"], d=3,
              x="Burun ichidagi tukchalar changni ushlab qoladi, havo esa isiydi."),
            TF("Ta’m bilishga burun ham yordam beradi.", True, d=3,
               x="Tumov bo‘lganda ovqat ta’mi yaxshi sezilmaydi, chunki hid sezilmaydi."),
        ])

T.topic("body_organs", "💪", L("Skelet, muskullar, yurak va o‘pka", "Skeleton, muscles, heart and lungs", "Скелет, мышцы, сердце и лёгкие"),
        chapter=C3,
        theory="• Skelet — suyaklar yig‘indisi. U tanaga tayanch bo‘ladi va ichki a’zolarni himoya qiladi: bosh suyagi miyani, qovurg‘alar yurak va o‘pkani asraydi.\n"
               "• Muskullar suyaklarga birikkan, ular qisqarib tanani harakatga keltiradi.\n"
               "• Yurak — kuchli muskul, u qonni butun tanaga haydaydi.\n"
               "• O‘pka orqali nafas olamiz: havodagi kislorod qonga o‘tadi, karbonat angidrid nafas bilan chiqadi.\n"
               "• Miya butun tanani boshqaradi, oshqozon ovqatni hazm qiladi.",
        items=[
            Q("Tanaga tayanch bo‘ladigan suyaklar yig‘indisi nima deyiladi?", "Skelet", ["Muskul", "Teri", "Qon"],
              x="Skelet — tanamizning suyak tayanchi."),
            Q("Qonni butun tanaga qaysi a’zo haydaydi?", "Yurak", ["O‘pka", "Oshqozon", "Miya"], e="❤️",
              x="Yurak nasos kabi qonni tomirlar bo‘ylab haydaydi."),
            Q("Qaysi a’zo orqali nafas olamiz?", "O‘pka", ["Yurak", "Oshqozon", "Jigar"],
              x="Nafas olganda havo o‘pkaga kiradi."),
            Q("Butun tanani qaysi a’zo boshqaradi?", "Miya", ["Yurak", "O‘pka", "Oshqozon"], e="🧠",
              x="Miya fikrlash, harakat va sezgilarni boshqaradi."),
            Q("Ovqatni hazm qiladigan a’zo qaysi?", "Oshqozon", ["O‘pka", "Yurak", "Miya"],
              x="Oshqozonda ovqat maydalanib, hazm bo‘ladi."),
            Q("Tanani nima harakatga keltiradi?", "Muskullar", ["Sochlar", "Tirnoqlar", "Tishlar"], e="💪",
              x="Muskullar qisqarib, suyaklarni harakatga keltiradi."),
            Q("Yugurganda yurak qanday uradi?", "Tezroq", ["Sekinroq", "To‘xtab qoladi", "Umuman urmaydi"],
              x="Harakat qilganda tanaga ko‘proq qon kerak, yurak tezroq uradi."),
            TF("Muskullar mashq qilinsa, kuchliroq bo‘ladi.", True, x="Sport va harakat muskullarni baquvvat qiladi."),
            TF("Yurak faqat biz yugurganimizda ishlaydi.", False,
               x="Yurak kecha-yu kunduz, uxlaganimizda ham to‘xtovsiz ishlaydi."),
            TF("Toza havoda sayr qilish o‘pka uchun foydali.", True, x="Toza havo o‘pkaga yaxshi."),
            MATCH("A’zoni vazifasi bilan juftlang",
                  [("Yurak", "qonni haydaydi"), ("O‘pka", "nafas olish"), ("Miya", "tanani boshqaradi"),
                   ("Oshqozon", "ovqatni hazm qiladi"), ("Muskullar", "harakatlantiradi"), ("Skelet", "tayanch bo‘ladi")]),
            Q("Miyani qaysi suyak himoya qiladi?", "Bosh suyagi", ["Qovurg‘alar", "Oyoq suyagi", "Qo‘l suyagi"], d=2,
              x="Miya mustahkam bosh suyagi ichida joylashgan."),
            Q("Yurak va o‘pkani qaysi suyaklar himoya qiladi?", "Qovurg‘alar",
              ["Bosh suyagi", "Barmoq suyaklari", "Tizza suyagi"], d=2,
              x="Qovurg‘alar ko‘krak qafasini hosil qiladi."),
            Q("Yurak qayerda joylashgan?", "Ko‘krak qafasida", ["Qorinda", "Boshda", "Oyoqda"], d=2,
              x="Yurak ko‘krak qafasida, ikki o‘pka orasida joylashgan."),
            Q("Bilak tomirini ushlab nimani sanash mumkin?", "Yurak urishini",
              ["Suyaklar sonini", "Tishlar sonini", "Sochlar sonini"], d=2,
              x="Tomir urishi (puls) yurak urishini ko‘rsatadi."),
            Q("Suyaklar mustahkam bo‘lishi uchun qaysi ovqat foydali?", "Sut va tvorog",
              ["Chips", "Gazli ichimlik", "Konfet"], d=2,
              x="Sut mahsulotlarida suyak uchun kerakli kalsiy ko‘p."),
            TF("Insonda ikkita o‘pka bor.", True, d=2, x="O‘ng va chap o‘pka ko‘krak qafasida joylashgan."),
            TF("Nafas olganimizda havodagi kislorod qonga o‘tadi.", True, d=2,
               x="Qon kislorodni butun tanaga tarqatadi."),
            TF("Chekish o‘pkaga zarar keltiradi.", True, d=2, x="Tutun o‘pkani ifloslaydi va kasallantiradi."),
            ORDER(S, "Yurak qonni butun tanaga haydaydi", d=2),
            Q("Nafas chiqarganimizda tanadan qaysi gaz chiqadi?", "Karbonat angidrid",
              ["Vodorod", "Tabiiy gaz", "Faqat azot"], d=3,
              x="Tanada hosil bo‘lgan karbonat angidrid nafas bilan tashqariga chiqadi."),
            Q("Orqadagi, tanani tik tutib turadigan suyaklar qatori nima deyiladi?", "Umurtqa pog‘onasi",
              ["Qovurg‘alar", "Bosh suyagi", "Tizza qopqog‘i"], d=3,
              x="Umurtqa pog‘onasi ko‘plab umurtqalardan tuzilgan."),
            Q("Qomatni to‘g‘ri tutish nima uchun kerak?", "Umurtqa pog‘onasi qiyshaymasligi uchun",
              ["Soch tez o‘sishi uchun", "Ko‘z rangi o‘zgarmasligi uchun", "Tish oqarishi uchun"], d=3,
              x="Egilib o‘tirish umurtqa pog‘onasini qiyshaytirishi mumkin."),
            Q("Yurakning kattaligi taxminan qanday?", "O‘z mushtingizdek", ["Tarvuzdek", "No‘xat donidek", "Kitobdek"], d=3,
              x="Har bir odamning yuragi taxminan o‘z mushtidek keladi."),
        ])

T.topic("health", "🍎", L("Sog‘lom turmush tarzi", "Healthy lifestyle", "Здоровый образ жизни"),
        chapter=C3,
        theory="Sog‘lom bo‘lish uchun:\n"
               "• Gigiyena: ovqatdan oldin va ko‘chadan kelgach qo‘lni sovunlab yuving, tishlarni ertalab va kechqurun tozalang.\n"
               "• To‘g‘ri ovqatlanish: meva, sabzavot, sut mahsulotlari, non va go‘shtni me’yorida yeng, shirinlikni kamaytiring.\n"
               "• Kun tartibi: vaqtida turish, badantarbiya, dars, dam olish va yetarli uyqu.\n"
               "• Harakat: toza havoda o‘ynang, sport bilan shug‘ullaning.",
        items=[
            Q("Qo‘lni qachon yuvish kerak?", "Ovqatdan oldin", ["Faqat bayramda", "Haftada bir marta", "Hech qachon"],
              x="Iflos qo‘ldagi mikroblar ovqat bilan tanaga tushishi mumkin."),
            Q("Tishlarni kuniga necha marta tozalash kerak?", "2 marta",
              ["Haftada 1 marta", "Oyda 1 marta", "Umuman kerak emas"],
              x="Tishlar ertalab va kechqurun tozalanadi."),
            Q("Qaysi biri eng foydali ovqat?", "Meva va sabzavot", ["Chips", "Gazli ichimlik", "Konfet"],
              x="Meva va sabzavotlarda vitaminlar ko‘p."),
            Q("Vitaminlar asosan qayerda ko‘p?", "Meva va sabzavotlarda", ["Konfetlarda", "Gazli ichimliklarda", "Chipslarda"],
              x="Vitaminlar tanani kasallikdan himoya qiladi."),
            Q("Mevalarni yeyishdan oldin nima qilish kerak?", "Yuvish", ["Quyoshda qoldirish", "Tuproqqa ko‘mish", "Muzlatish"],
              x="Yuvilmagan mevada chang va mikroblar bo‘ladi."),
            Q("Shaxsiy gigiyena buyumi qaysi?", "Tish cho‘tkasi", ["Qalam", "To‘p", "Kitob"],
              x="Tish cho‘tkasi, sochiq, taroq — shaxsiy gigiyena buyumlari."),
            Q("Qaysi odat sog‘liqqa foydali?", "Ko‘p harakat qilish",
              ["Kech yotish", "Nonushtasiz maktabga borish", "Kam suv ichish"],
              x="Harakat tanani chiniqtiradi."),
            Q("Qishda sog‘lom bo‘lish uchun nima qilish kerak?", "Issiq kiyinish",
              ["Yupqa kiyinish", "Qor yeyish", "Ho‘l oyoq kiyimda yurish"],
              x="Issiq kiyim tanani shamollashdan saqlaydi."),
            TF("Ko‘p shirinlik yeyish tishlarga zarar.", True, x="Shirinlik qoldiqlari tishlarni yemiradi."),
            TF("Ertalabki badantarbiya sog‘liq uchun foydali.", True, x="Badantarbiya tanani uyg‘otadi va chiniqtiradi."),
            TF("Bolalar kechasi kam uxlasa ham bo‘ladi.", False,
               x="O‘sayotgan bola yetarli uxlashi kerak, aks holda tez charchaydi."),
            TF("Nonushta qilmasdan maktabga borish yaxshi odat.", False, x="Nonushta kun davomida kuch beradi."),
            TF("Toza havoda o‘ynash sog‘liqni mustahkamlaydi.", True, x="Toza havo va harakat tanaga foydali."),
            MATCH("Gigiyena buyumini vazifasi bilan juftlang",
                  [("Tish cho‘tkasi", "tishni tozalash"), ("Sovun", "qo‘lni yuvish"), ("Sochiq", "artinish"),
                   ("Taroq", "sochni tarash"), ("Tirnoq olgich", "tirnoqni kesish")]),
            ORDER(S, "Ovqatdan oldin qo‘lni sovunlab yuvamiz"),
            Q("Kun tartibi nima uchun kerak?", "Vaqtni to‘g‘ri taqsimlash uchun",
              ["Ko‘proq televizor ko‘rish uchun", "Uxlamaslik uchun", "Darsni unutish uchun"], d=2,
              x="Kun tartibi bilan dars, dam olish va uyquga vaqt yetadi."),
            Q("Kompyuter va telefonda uzoq o‘tirish nimaga zarar?", "Ko‘z va qomatga", ["Sochga", "Tirnoqqa", "Ovozga"], d=2,
              x="Ekranga uzoq qarash ko‘zni, egilib o‘tirish qomatni buzadi."),
            Q("Sut mahsulotlari qaysi qatorda?", "Qatiq, pishloq, tvorog",
              ["Non, guruch, un", "Olma, nok, o‘rik", "Sabzi, piyoz, karam"], d=2,
              x="Qatiq, pishloq va tvorog sutdan tayyorlanadi."),
            Q("Mikroblar qayerda ko‘p bo‘ladi?", "Iflos qo‘llarda",
              ["Toza sochiqda", "Yuvilgan mevada", "Qaynatilgan suvda"], d=2,
              x="Qo‘lni sovunlab yuvsak, mikroblar ketadi."),
            Q("Qaysi suvni ichish xavfsiz?", "Qaynatilgan suvni", ["Ariq suvini", "Ko‘lmak suvini", "Hovuz suvini"], d=2,
              x="Qaynatilganda suvdagi mikroblar nobud bo‘ladi."),
            Q("Tobingiz qochsa, avvalo nima qilasiz?", "Kattalarga aytaman",
              ["Hech kimga aytmayman", "O‘zim dori ichaman", "Ko‘chaga chiqib ketaman"], d=2,
              x="Kattalar shifokorga olib boradi, dorini o‘zboshimchalik bilan ichish xavfli."),
            Q("Sport bilan shug‘ullanish nimaga yordam beradi?", "Tana chiniqib, kuchli bo‘lishiga",
              ["Tez charchashga", "Ko‘z xiralashishiga", "Tish og‘rishiga"], d=2,
              x="Sport muskullar, yurak va o‘pkani mustahkamlaydi."),
            TF("Tish cho‘tkasini boshqalar bilan almashib ishlatish mumkin.", False, d=2,
               x="Tish cho‘tkasi — shaxsiy buyum, u orqali mikroblar yuqishi mumkin."),
            Q("Qaysi kun tartibi to‘g‘ri?", "Turish, badantarbiya, nonushta, maktab",
              ["Maktab, turish, nonushta, badantarbiya", "Nonushta, turish, maktab, badantarbiya",
               "Badantarbiya, maktab, turish, nonushta"], d=3,
              x="Avval turamiz, badantarbiya qilamiz, nonushta qilib, maktabga boramiz."),
        ])

T.test("test3", L("3-nazorat ishi", "Test 3", "Контрольная работа 3"),
       ["body_senses", "body_organs", "health"], chapter=C3)

# ============================================================ 4-chorak
T.topic("water_weather", "💧", L("Suv va ob-havo", "Water and weather", "Вода и погода"),
        chapter=C4,
        theory="Suv uch holatda bo‘ladi: qattiq (muz, qor), suyuq (suv) va gaz (bug‘).\n"
               "• Suv 0 °C da muzlaydi, 100 °C da qaynaydi. Toza suv rangsiz, hidsiz va shaffof, u tuz va shakarni eritadi.\n"
               "Suvning aylanishi: Quyosh isitadi → suv bug‘lanadi → bug‘dan bulut hosil bo‘ladi → yomg‘ir yoki qor yog‘adi → suv daryo va dengizlarga qaytadi.\n"
               "Ob-havo — harorat, yog‘in, shamol va bulutlilik. Havo haroratini termometr bilan o‘lchaymiz.",
        items=[
            Q("Suv muzlasa nimaga aylanadi?", "Muzga", ["Bug‘ga", "Bulutga", "Qumga"], x="Sovuqda suv qotib, muzga aylanadi."),
            Q("Suv qaynasa nimaga aylanadi?", "Bug‘ga", ["Muzga", "Qorga", "Tuzga"], x="Qaynayotgan suv bug‘ga aylanadi."),
            Q("Muz isitilsa nima bo‘ladi?", "Eriydi", ["Qotadi", "Yonadi", "O‘sadi"], x="Issiqda muz erib, suvga aylanadi."),
            Q("Suvning qattiq holati qaysi?", "Muz", ["Bug‘", "Yomg‘ir", "Tuman"], x="Muz va qor — suvning qattiq holati."),
            Q("Suvning gaz holati nima deyiladi?", "Bug‘", ["Muz", "Qor", "Do‘l"], x="Bug‘ — suvning gaz holati."),
            Q("Havo haroratini qaysi asbob o‘lchaydi?", "Termometr", ["Tarozi", "Chizg‘ich", "Soat"], e="🌡️",
              x="Termometr haroratni darajalarda ko‘rsatadi."),
            Q("Suvni tejash uchun nima qilish kerak?", "Jo‘mrakni yopib qo‘yish",
              ["Jo‘mrakni ochiq qoldirish", "Mashinani har kuni yuvish", "Uzoq vaqt dush qabul qilish"],
              x="Toza suv — bebaho boylik, uni isrof qilmaslik kerak."),
            TF("Toza suv rangsiz va hidsiz bo‘ladi.", True, x="Toza suvning rangi ham, hidi ham yo‘q."),
            TF("Shakar suvda eriydi.", True, x="Shakar suvda erib, ko‘rinmay qoladi."),
            TF("Qum suvda eriydi.", False, x="Qum suvda erimaydi, u idish tagiga cho‘kadi."),
            TF("Suv idish shaklini oladi.", True, x="Suv suyuq, u qaysi idishga quyilsa, o‘sha shaklni oladi."),
            Q("Suv necha darajada muzlaydi?", "0 darajada", ["100 darajada", "10 darajada", "50 darajada"], d=2,
              x="Suv 0 °C da muzlaydi."),
            Q("Suv necha darajada qaynaydi?", "100 darajada", ["0 darajada", "20 darajada", "50 darajada"], d=2,
              x="Suv 100 °C da qaynaydi."),
            Q("Bulutlar nimadan hosil bo‘ladi?", "Suv bug‘idan", ["Tutundan", "Changdan", "Qumdan"], d=2,
              x="Yuqoriga ko‘tarilgan bug‘ soviydi va mayda tomchilarga aylanib, bulut hosil qiladi."),
            Q("Qaysi biri yog‘in emas?", "Shamol", ["Yomg‘ir", "Qor", "Do‘l"], d=2,
              x="Yomg‘ir, qor, do‘l — yog‘inlar, shamol esa havoning harakati."),
            Q("Ho‘l kiyim quyoshda nima uchun quriydi?", "Suv bug‘lanadi",
              ["Suv muzlaydi", "Suv tuzga aylanadi", "Suv toshga aylanadi"], d=2,
              x="Quyosh issiqligida kiyimdagi suv bug‘ga aylanib uchib ketadi."),
            Q("Termometr 25 daraja issiqni ko‘rsatsa, havo qanday?", "Issiq",
              ["Juda sovuq", "Qahraton sovuq", "Muz qotadigan darajada sovuq"], d=2,
              x="25 daraja issiq — bu iliq-issiq havo."),
            Q("Ob-havo haqida kim ma’lumot beradi?", "Sinoptik", ["Oshpaz", "Sartarosh", "Duradgor"], d=2,
              x="Sinoptiklar ob-havoni kuzatib, oldindan aytib beradi."),
            TF("Muz suvda cho‘kib ketadi.", False, d=2, x="Muz suvdan yengil, shuning uchun suv yuzasida suzib yuradi."),
            MATCH("Ob-havo hodisasini tavsifi bilan juftlang",
                  [("Yomg‘ir", "suv tomchilari yog‘adi"), ("Qor", "oq yumshoq parchalar yog‘adi"),
                   ("Do‘l", "muz donachalari yog‘adi"), ("Shamol", "havo harakati"),
                   ("Tuman", "yerga yaqin paydo bo‘lgan bulut"), ("Shudring", "ertalab o‘tlardagi tomchilar")], d=2),
            ORDER(S, "Quyosh suvni isitadi va u bug‘lanadi", d=2),
            Q("Suvning aylanishini nima harakatga keltiradi?", "Quyosh issiqligi",
              ["Oy nuri", "Shamol tegirmoni", "Inson"], d=3,
              x="Quyosh issiqligi suvni bug‘latadi — aylanish shundan boshlanadi."),
            Q("Qaysi harorat eng sovuq?", "10 daraja sovuq", ["5 daraja issiq", "0 daraja", "20 daraja issiq"], d=3,
              x="10 daraja sovuq — noldan past, u eng sovuq."),
            Q("Shamol yo‘nalishini qaysi asbob ko‘rsatadi?", "Flyuger", ["Termometr", "Tarozi", "Chizg‘ich"], d=3,
              x="Flyuger shamol esayotgan tomonga burilib turadi."),
            TF("Suv muzlaganda kengayadi.", True, d=3,
               x="Shuning uchun qishda suvli shisha idish muzlab yorilib ketishi mumkin."),
        ])

T.topic("air_soil", "🍃", L("Havo va tuproq", "Air and soil", "Воздух и почва"),
        chapter=C4,
        theory="Havo bizni har tomondan o‘rab turadi. U rangsiz, shaffof va hidsiz, joy egallaydi.\n"
               "• Havo isiganda kengayadi, soviganda torayadi. Issiq havo yuqoriga ko‘tariladi. Havoning harakati — shamol.\n"
               "• Havodagi kislorod nafas olish va yonish uchun kerak. Daraxtlar havoni tozalaydi.\n"
               "Tuproq — yerning ustki unumdor qatlami. Unda qum, loy, chirindi, suv, havo va mineral tuzlar bor.\n"
               "Chirindi o‘simlik va hayvon qoldiqlari chirishidan hosil bo‘ladi, u tuproqni unumdor qiladi.",
        items=[
            Q("Toza havo qanday rangda?", "Rangsiz", ["Ko‘k", "Oq", "Yashil"],
              x="Havo rangsiz va shaffof, shuning uchun biz uni ko‘rmaymiz."),
            Q("Havoning harakati nima deyiladi?", "Shamol", ["Yomg‘ir", "Tuman", "Qor"], x="Shamol — harakatlanayotgan havo."),
            Q("Havoni nima tozalaydi?", "Daraxtlar", ["Zavod tutuni", "Mashina gazi", "Chiqindi yoqish"],
              x="Daraxtlar changni ushlaydi va havoga kislorod chiqaradi."),
            Q("Havoni nima ifloslantiradi?", "Zavod tutuni", ["Daraxtlar", "Gullar", "Yomg‘ir"],
              x="Tutun va mashina gazlari havoni ifloslaydi."),
            Q("Tuproq nima?", "Yerning ustki unumdor qatlami",
              ["Tog‘ ichidagi tosh", "Daryo tubidagi suv", "Osmondagi bulut"],
              x="O‘simliklar tuproqda o‘sadi."),
            Q("Tuproqni asrash uchun nima qilish kerak?", "Daraxt ekish",
              ["Chiqindi ko‘mish", "Yerni ifloslash", "O‘tlarni yoqish"],
              x="Daraxt ildizlari tuproqni yuvilib ketishdan saqlaydi."),
            Q("Shar puflanganda ichi nima bilan to‘ladi?", "Havo bilan", ["Suv bilan", "Qum bilan", "Tuproq bilan"],
              x="Puflaganda sharga havo kiradi."),
            TF("Havo joy egallaydi.", True, x="Shar yoki pufakni puflaganimizda u havo bilan to‘lib kattalashadi."),
            TF("Toza havo hidsiz bo‘ladi.", True, x="Toza havoning hidi yo‘q."),
            TF("Tuproqda o‘simliklar o‘sadi.", True, x="Tuproq o‘simlikni suv va oziq bilan ta’minlaydi."),
            ORDER(S, "Daraxtlar havoni toza saqlaydi"),
            Q("Nafas olish uchun havodagi qaysi gaz kerak?", "Kislorod", ["Karbonat angidrid", "Azot", "Tutun"], d=2,
              x="Inson va hayvonlar havodagi kislorod bilan nafas oladi."),
            Q("Tuproqni nima unumdor qiladi?", "Chirindi", ["Tosh", "Shisha", "Plastik"], d=2,
              x="Chirindida o‘simlik uchun oziq moddalar ko‘p."),
            Q("Chirindi nimadan hosil bo‘ladi?", "O‘simlik va hayvon qoldiqlaridan", ["Toshlardan", "Qumdan", "Muzdan"], d=2,
              x="Barg, o‘t va boshqa qoldiqlar chirib, chirindiga aylanadi."),
            Q("Tuproqni yumshatib, unga havo kirishiga yordam beradigan jonivor?", "Yomg‘ir chuvalchangi",
              ["Chivin", "Kapalak", "Pashsha"], d=2,
              x="Chuvalchang tuproqda yo‘l ochib, uni yumshatadi."),
            Q("Havo ifloslanishini kamaytirish uchun nima qilish kerak?", "Velosipedda yurish",
              ["Chiqindi yoqish", "Daraxt kesish", "Mashinani bekorga yurgizib qo‘yish"], d=2,
              x="Velosiped tutun chiqarmaydi."),
            TF("Havo isiganda kengayadi.", True, d=2, x="Issiqda havo ko‘proq joy egallaydi."),
            TF("Issiq havo pastga tushadi.", False, d=2, x="Issiq havo yengil, shuning uchun yuqoriga ko‘tariladi."),
            TF("Tuproqda havo ham bor.", True, d=2, x="Tuproq bo‘lagini suvga solsak, havo pufakchalari chiqadi."),
            TF("Tuproq bir necha kunda hosil bo‘ladi.", False, d=2,
               x="Tuproq juda sekin — yuzlab yillar davomida hosil bo‘ladi."),
            MATCH("So‘zni ma’nosi bilan juftlang",
                  [("Shamol", "havoning harakati"), ("Kislorod", "nafas olish uchun gaz"),
                   ("Chirindi", "tuproqdagi unumdor modda"), ("Tuproq", "yerning unumdor qatlami"),
                   ("Chuvalchang", "tuproqni yumshatadi")], d=2),
            Q("Yonish uchun havodagi qaysi gaz kerak?", "Kislorod", ["Azot", "Suv bug‘i", "Karbonat angidrid"], d=3,
              x="Kislorod bo‘lmasa, olov o‘chadi."),
            Q("Havo tarkibida eng ko‘p qaysi gaz bor?", "Azot", ["Kislorod", "Karbonat angidrid", "Suv bug‘i"], d=3,
              x="Havoning eng katta qismi azot, kislorod esa undan kamroq."),
            Q("Qo‘sh romli deraza xonani nima uchun issiq saqlaydi?", "Oynalar orasidagi havo issiqlikni ushlaydi",
              ["Oyna issiqlik chiqaradi", "Romlar temirdan", "Deraza doim ochiq turadi"], d=3,
              x="Havo issiqlikni yomon o‘tkazadi."),
            Q("Qaysi tuproq unumdorroq?", "Qora, chirindiga boy tuproq", ["Toza qum", "Mayda toshloq", "Sho‘r tuproq"], d=3,
              x="Chirindi ko‘p bo‘lgan tuproq qora rangda va unumdor bo‘ladi."),
        ])

T.topic("earth_sky", "🌍", L("Quyosh, Yer, Oy va fasllar", "Sun, Earth, Moon and seasons", "Солнце, Земля, Луна и времена года"),
        chapter=C4,
        theory="Quyosh — ulkan issiq yulduz, u Yerga yorug‘lik va issiqlik beradi. Yer — shar shaklidagi sayyora.\n"
               "• Yer o‘z o‘qi atrofida 1 sutkada aylanadi — shundan kecha va kunduz almashadi.\n"
               "• Yer Quyosh atrofida 1 yilda aylanib chiqadi. Yilda 4 fasl bor: bahor, yoz, kuz, qish.\n"
               "• Oy — Yerning yo‘ldoshi, u o‘zidan nur chiqarmaydi, Quyosh nurini qaytaradi.\n"
               "Asosiy yo‘nalishlar: shimol, janub, sharq, g‘arb. Kompas mili shimolni ko‘rsatadi.",
        items=[
            Q("Yerga yorug‘lik va issiqlik nima beradi?", "Quyosh", ["Oy", "Bulut", "Shamol"], e="☀️",
              x="Quyosh — Yerga eng yaqin yulduz."),
            Q("Yer o‘z o‘qi atrofida qancha vaqtda aylanadi?", "1 sutkada", ["1 yilda", "1 oyda", "1 haftada"],
              x="Bir sutka — 24 soat."),
            Q("Yer Quyosh atrofida qancha vaqtda aylanib chiqadi?", "1 yilda", ["1 sutkada", "1 haftada", "1 soatda"],
              x="Yer Quyosh atrofini bir yilda aylanib chiqadi."),
            Q("Oy nima?", "Yerning yo‘ldoshi", ["Yulduz", "Bulut", "Quyoshning bir qismi"], e="🌙",
              x="Oy Yer atrofida aylanadi."),
            Q("Yilda nechta fasl bor?", "4 ta", ["2 ta", "3 ta", "12 ta"], x="Bahor, yoz, kuz va qish."),
            Q("Qaysi oy qish fasliga kiradi?", "Yanvar", ["Aprel", "Iyul", "Oktabr"],
              x="Qish oylari: dekabr, yanvar, fevral."),
            Q("Qaysi faslda kunlar eng uzun va issiq bo‘ladi?", "Yozda", ["Qishda", "Kuzda", "Bahorda"],
              x="Yozda Quyosh uzoq vaqt osmonda turadi."),
            Q("Fasllar ketma-ketligini to‘ldiring: qish → bahor → ...", "Yoz", ["Kuz", "Qish", "Bahor"],
              x="Qishdan keyin bahor, bahordan keyin yoz keladi."),
            Q("Quyosh qaysi tomondan chiqadi?", "Sharqdan", ["G‘arbdan", "Shimoldan", "Janubdan"],
              x="Quyosh ertalab sharqdan chiqadi."),
            Q("Quyosh qaysi tomonga botadi?", "G‘arbga", ["Sharqqa", "Shimolga", "Janubga"],
              x="Kechqurun Quyosh g‘arbga botadi."),
            Q("Yil necha oydan iborat?", "12 oydan", ["10 oydan", "7 oydan", "4 oydan"],
              x="Yilda 12 oy va 4 fasl bor."),
            TF("Quyosh — yulduz.", True, x="Quyosh — ulkan issiq yulduz."),
            TF("Yer shar shaklida.", True, x="Globus Yerning kichik modeli, u ham shar shaklida."),
            TF("Yer Quyosh atrofida aylanadigan sayyora.", True, x="Yer — Quyosh atrofida aylanuvchi sayyoralardan biri."),
            Q("Kecha va kunduz nima sababdan almashadi?", "Yer o‘z o‘qi atrofida aylanadi",
              ["Oy Quyoshni to‘sadi", "Bulutlar Quyoshni yopadi", "Quyosh o‘chib qoladi"], d=2,
              x="Yerning Quyoshga qaragan tomonida kunduz, qarama-qarshi tomonida kecha bo‘ladi."),
            Q("Yerning Quyoshga qaragan tomonida nima bo‘ladi?", "Kunduz", ["Kecha", "Qish", "Tun"], d=2,
              x="Quyosh nuri tushib turgan tomonda kunduz bo‘ladi."),
            Q("Qaysi oy kuz fasliga kiradi?", "Oktabr", ["Fevral", "May", "Avgust"], d=2,
              x="Kuz oylari: sentabr, oktabr, noyabr."),
            Q("Kompas mili qaysi tomonni ko‘rsatadi?", "Shimolni", ["Sharqni", "G‘arbni", "Osmonni"], d=2,
              x="Kompas mili doimo shimol tomonga buriladi."),
            TF("Oy o‘zidan yorug‘lik chiqaradi.", False, d=2, x="Oy Quyosh nurini qaytaradi, shuning uchun yorug‘ ko‘rinadi."),
            MATCH("So‘zni ma’nosi bilan juftlang",
                  [("Quyosh", "eng yaqin yulduz"), ("Oy", "Yerning yo‘ldoshi"), ("Kompas", "yo‘nalishni aniqlaydi"),
                   ("Sutka", "24 soat"), ("Yil", "12 oy"), ("Ufq", "osmon yer bilan tutashgandek chiziq")], d=2),
            ORDER(S, "Quyosh sharqdan chiqib g‘arbga botadi", d=2),
            Q("Shimolga qarab tursangiz, o‘ng qo‘lingiz qaysi tomonda bo‘ladi?", "Sharqda",
              ["G‘arbda", "Janubda", "Shimolda"], d=3, x="Shimolga qaraganda o‘ngda sharq, chapda g‘arb bo‘ladi."),
            Q("Tushda Quyosh O‘zbekistonda qaysi tomonda turadi?", "Janubda", ["Shimolda", "Sharqda", "G‘arbda"], d=3,
              x="Tush paytida Quyosh janubda, soyamiz esa shimolga tushadi."),
            TF("Qutb yulduzi osmonning shimol tomonida ko‘rinadi.", True, d=3,
               x="Qadimda sayohatchilar Qutb yulduziga qarab shimolni topishgan."),
        ])

T.topic("uzbekistan", "🏔️", L("O‘zbekiston tabiati va uni asrash", "Nature of Uzbekistan and its protection", "Природа Узбекистана и её охрана"),
        chapter=C4,
        theory="O‘zbekistonda tog‘lar, cho‘llar, vodiylar, daryolar va ko‘llar bor.\n"
               "• Eng katta daryolar — Amudaryo va Sirdaryo. Eng katta cho‘l — Qizilqum. Sharq va janubi-sharqda Tyan-Shan va Hisor tog‘lari joylashgan.\n"
               "• Qizil kitob — kamyob, yo‘qolib ketish xavfi ostidagi o‘simlik va hayvonlar ro‘yxati. Unga qor qoploni, jayron, Buxoro bug‘usi, Turkiston silovsini kiritilgan.\n"
               "• Qo‘riqxonalarda tabiat alohida muhofaza qilinadi.\n"
               "Tabiatni asrang: daraxt eking, suvni tejang, chiqindini axlat qutisiga tashlang, qushlarga yem bering.",
        items=[
            Q("O‘zbekistondagi eng katta daryolar qaysilar?", "Amudaryo va Sirdaryo",
              ["Volga va Nil", "Dunay va Amazonka", "Chirchiq va Ohangaron"],
              x="Amudaryo va Sirdaryo — O‘zbekistonning eng katta daryolari."),
            Q("Qizil kitobga qanday hayvonlar kiritiladi?", "Kamyob, yo‘qolib borayotgan",
              ["Uy hayvonlari", "Eng ko‘p uchraydigan", "Faqat baliqlar"],
              x="Qizil kitob kamyob turlarni asrashga yordam beradi."),
            Q("Qaysi hayvon O‘zbekiston Qizil kitobiga kiritilgan?", "Qor qoploni", ["Sigir", "Chumchuq", "Tovuq", "Qo‘y"],
              x="Qor qoploni — kamyob tog‘ yirtqichi."),
            Q("Buxoro bug‘usi qaysi kitobga kiritilgan?", "Qizil kitobga", ["Alifbega", "Lug‘atga", "Oshpazlik kitobiga"],
              x="Buxoro bug‘usi — kamyob hayvon, u Qizil kitobda."),
            Q("Tabiatni asrash uchun nima qilamiz?", "Daraxt ekamiz",
              ["Gullarni uzamiz", "Chiqindini yerga tashlaymiz", "Qush uyasini buzamiz"],
              x="Daraxtlar havoni tozalaydi, tuproqni saqlaydi."),
            Q("Chiqindini qayerga tashlash kerak?", "Axlat qutisiga", ["Ariqqa", "Yo‘l chetiga", "Daryoga"],
              x="Chiqindi tabiatni ifloslamasligi kerak."),
            Q("Qishda qushlarga qanday yordam beramiz?", "Yemlik osib, don sepamiz",
              ["Uyalarini buzamiz", "Ularni quvlaymiz", "Ularni qo‘rqitamiz"],
              x="Qishda qushlarga oziq topish qiyin, yemlik ularga yordam beradi."),
            TF("Qo‘riqxonada ov qilish mumkin.", False, x="Qo‘riqxonada hayvon va o‘simliklar qo‘riqlanadi, ov qilish taqiqlanadi."),
            TF("Qor qoploni tog‘larda yashaydi.", True, x="Qor qoploni baland tog‘ qoyalarida yashaydi."),
            TF("Amudaryo — O‘zbekistondagi daryo.", True, x="Amudaryo O‘zbekistonning eng katta daryolaridan biri."),
            TF("Tog‘ va cho‘llardagi kamyob hayvonlarni asrash kerak.", True, x="Ular yo‘qolib ketmasligi uchun muhofaza qilinadi."),
            TF("Buloq va ariqlarni ifloslantirish mumkin.", False, x="Suv manbalarini toza saqlash kerak."),
            ORDER(S, "Biz tabiatni asrashimiz kerak"),
            Q("O‘zbekistondagi eng katta cho‘l qaysi?", "Qizilqum", ["Sahroi Kabir", "Gobi", "Mirzacho‘l"], d=2,
              x="Qizilqum — O‘zbekistondagi eng katta cho‘l."),
            Q("Cho‘lda yashovchi, Qizil kitobga kiritilgan chaqqon hayvon?", "Jayron", ["Echki", "Mushuk", "Quyon"], d=2,
              x="Jayron — cho‘l va dashtlarda yashovchi kamyob hayvon."),
            Q("Orol dengizi bilan nima bo‘ldi?", "Qurib, kichrayib ketdi",
              ["Kattalashib ketdi", "Muzlab qoldi", "Chuchuk ko‘lga aylandi"], d=2,
              x="Orol dengizi ko‘p yillar davomida sayozlanib, kichrayib ketdi."),
            Q("Qaysi tog‘lar O‘zbekistonda joylashgan?", "Tyan-Shan va Hisor",
              ["Alp va Pireney", "And va Kordilyera", "Ural va Kavkaz"], d=2,
              x="Tyan-Shan va Hisor tog‘lari O‘zbekistonning sharqi va janubi-sharqida."),
            Q("Qo‘riqxona nima?", "Tabiat muhofaza qilinadigan hudud", ["Hayvonot bog‘i", "Bozor", "Istirohat bog‘i"], d=2,
              x="Qo‘riqxonada tabiat o‘z holicha saqlanadi."),
            Q("Qumni ushlab turish uchun cho‘lga qaysi o‘simlik ekiladi?", "Saksovul", ["Sholi", "Karam", "Kartoshka"], d=2,
              x="Saksovul qumli cho‘lda yaxshi o‘sadi va qumni mustahkamlaydi."),
            MATCH("Hayvonni yashash joyi bilan juftlang",
                  [("Qor qoploni", "baland tog‘lar"), ("Jayron", "cho‘l"), ("Laqqa", "daryo"),
                   ("Buxoro bug‘usi", "to‘qay o‘rmoni"), ("Kit", "okean"), ("Oq ayiq", "muzli shimol")], d=2),
            Q("Qaysi daryo Toshkent viloyatidan oqib o‘tadi?", "Chirchiq", ["Amazonka", "Nil", "Volga"], d=3,
              x="Chirchiq daryosi Toshkent viloyatidan oqib o‘tadi."),
            Q("Qizil kitob nega “qizil” deb nomlangan?", "Qizil rang xavfdan ogohlantiradi",
              ["Unda faqat qizil gullar bor", "Uni qizil siyohda yozishgan", "Unda faqat qizil hayvonlar bor"], d=3,
              x="Qizil rang — “ehtiyot bo‘ling, xavf bor!” degan belgi."),
            Q("Turkiston silovsini qanday hayvon?", "Yovvoyi mushuksimon yirtqich", ["Uy hayvoni", "Qush", "Baliq"], d=3,
              x="Silovsin — yovvoyi mushuklar oilasiga kiruvchi kamyob yirtqich."),
            Q("O‘zbekistonning qaysi qismida tog‘lar ko‘p?", "Sharqi va janubi-sharqida",
              ["G‘arbida", "Shimoli-g‘arbida", "Markazidagi cho‘llarda"], d=3,
              x="G‘arbda tekisliklar va cho‘llar, sharq va janubi-sharqda esa tog‘lar."),
        ])

T.test("test4", L("4-nazorat ishi", "Test 4", "Контрольная работа 4"),
       ["water_weather", "air_soil", "earth_sky", "uzbekistan"], chapter=C4)

T.test("final", L("Yillik takrorlash", "End-of-year review", "Итоговое повторение"),
       ["nature", "plant_parts", "plant_growth", "plant_kinds", "animal_groups", "animal_food", "animal_home",
        "body_senses", "body_organs", "health", "water_weather", "air_soil", "earth_sky", "uzbekistan"],
       chapter=C4, level=3)

T.write()
