# Uch tilli lug'at manbasi. `python3 tool/content/lexicon_src.py` -> assets/data/lexicon.json
# Har bir tushuncha: id, emoji, uz, en, ru, kategoriya, teglar, (rang).
# Emoji'lar Android 9 (Emoji 11.0) da ko'rinadiganlaridan tanlangan.
import json, os

def E(id, e, uz, en, ru, cat, tags=(), color=None, age=4):
    d = {"id": id, "emoji": e, "uz": uz, "en": en, "ru": ru, "category": cat, "tags": list(tags), "ageMin": age}
    if color: d["color"] = color
    return d

L = [
# ---------------- mevalar
E("apple","🍎","olma","apple","яблоко","fruit",["sweet","round","tree"],"red"),
E("green_apple","🍏","yashil olma","green apple","зелёное яблоко","fruit",["round","tree"],"green"),
E("banana","🍌","banan","banana","банан","fruit",["sweet","tree"],"yellow"),
E("grapes","🍇","uzum","grapes","виноград","fruit",["sweet"],"purple"),
E("strawberry","🍓","qulupnay","strawberry","клубника","fruit",["sweet"],"red"),
E("cherry","🍒","gilos","cherry","вишня","fruit",["sweet","round","tree"],"red"),
E("peach","🍑","shaftoli","peach","персик","fruit",["sweet","round","tree"],"orange"),
E("pear","🍐","nok","pear","груша","fruit",["sweet","tree"],"green"),
E("orange","🍊","apelsin","orange","апельсин","fruit",["round","tree"],"orange"),
E("lemon","🍋","limon","lemon","лимон","fruit",["tree"],"yellow"),
E("watermelon","🍉","tarvuz","watermelon","арбуз","fruit",["sweet","round"],"green"),
E("pineapple","🍍","ananas","pineapple","ананас","fruit",["sweet"],"yellow"),
E("kiwi","🥝","kivi","kiwi","киви","fruit",["round"],"green"),
E("coconut","🥥","kokos","coconut","кокос","fruit",["round","tree"],"brown"),
E("mango","🥭","mango","mango","манго","fruit",["sweet","tree"],"orange"),
E("melon","🍈","qovun","melon","дыня","fruit",["sweet","round"],"yellow"),
# ---------------- sabzavotlar
E("carrot","🥕","sabzi","carrot","морковь","vegetable",[],"orange"),
E("corn","🌽","makkajo‘xori","corn","кукуруза","vegetable",[],"yellow"),
E("cucumber","🥒","bodring","cucumber","огурец","vegetable",[],"green"),
E("tomato","🍅","pomidor","tomato","помидор","vegetable",["round"],"red"),
E("eggplant","🍆","baqlajon","eggplant","баклажан","vegetable",[],"purple"),
E("potato","🥔","kartoshka","potato","картофель","vegetable",[],"brown"),
E("broccoli","🥦","brokkoli","broccoli","брокколи","vegetable",[],"green"),
E("pepper","🌶️","qalampir","pepper","перец","vegetable",[],"red"),
E("cabbage","🥬","karam","cabbage","капуста","vegetable",[],"green"),
E("mushroom","🍄","qo‘ziqorin","mushroom","гриб","vegetable",["forest"],"red"),
E("peanut","🥜","yeryong‘oq","peanut","арахис","vegetable",[],"brown"),
E("chestnut","🌰","kashtan","chestnut","каштан","vegetable",["tree"],"brown"),
# ---------------- uy hayvonlari
E("dog","🐶","it","dog","собака","animal",["pet","has_legs","home_animal"],"brown"),
E("cat","🐱","mushuk","cat","кошка","animal",["pet","has_legs","home_animal"],"orange"),
E("mouse","🐭","sichqon","mouse","мышь","animal",["has_legs","small"],"white"),
E("hamster","🐹","hamster","hamster","хомяк","animal",["pet","has_legs","small"],"orange"),
E("rabbit","🐰","quyon","rabbit","кролик","animal",["has_legs","home_animal"],"white"),
E("cow","🐮","sigir","cow","корова","animal",["farm","has_legs","big"],"white"),
E("pig","🐷","cho‘chqa","pig","свинья","animal",["farm","has_legs"],"pink"),
E("horse","🐴","ot","horse","лошадь","animal",["farm","has_legs","big"],"brown"),
E("sheep","🐑","qo‘y","sheep","овца","animal",["farm","has_legs"],"white"),
E("goat","🐐","echki","goat","коза","animal",["farm","has_legs"],"white"),
E("chicken","🐔","tovuq","chicken","курица","bird",["farm","has_legs"],"white"),
E("rooster","🐓","xo‘roz","rooster","петух","bird",["farm","has_legs"],"red"),
E("chick","🐤","jo‘ja","chick","цыплёнок","bird",["farm","small","baby"],"yellow"),
E("duck","🦆","o‘rdak","duck","утка","bird",["farm","flies","swims"],"green"),
E("turkey","🦃","kurka","turkey","индюк","bird",["farm"],"brown"),
E("camel","🐫","tuya","camel","верблюд","animal",["has_legs","big","desert"],"brown"),
# ---------------- yovvoyi hayvonlar
E("lion","🦁","sher","lion","лев","animal",["wild","has_legs","big"],"orange"),
E("tiger","🐯","yo‘lbars","tiger","тигр","animal",["wild","has_legs","big"],"orange"),
E("bear","🐻","ayiq","bear","медведь","animal",["wild","has_legs","big","forest"],"brown"),
E("panda","🐼","panda","panda","панда","animal",["wild","has_legs"],"white"),
E("koala","🐨","koala","koala","коала","animal",["wild","has_legs"],"white"),
E("fox","🦊","tulki","fox","лиса","animal",["wild","has_legs","forest"],"orange"),
E("wolf","🐺","bo‘ri","wolf","волк","animal",["wild","has_legs","forest"],"white"),
E("monkey","🐵","maymun","monkey","обезьяна","animal",["wild","has_legs"],"brown"),
E("elephant","🐘","fil","elephant","слон","animal",["wild","has_legs","big"],"white"),
E("giraffe","🦒","jirafa","giraffe","жираф","animal",["wild","has_legs","big"],"yellow"),
E("zebra","🦓","zebra","zebra","зебра","animal",["wild","has_legs","big"],"white"),
E("rhino","🦏","karkidon","rhinoceros","носорог","animal",["wild","has_legs","big"],"white"),
E("kangaroo","🦘","kenguru","kangaroo","кенгуру","animal",["wild","has_legs"],"brown",6),
E("hedgehog","🦔","tipratikan","hedgehog","ёжик","animal",["wild","has_legs","small","forest"],"brown"),
E("squirrel","🐿️","olmaxon","squirrel","белка","animal",["wild","has_legs","small","forest"],"brown"),
E("frog","🐸","qurbaqa","frog","лягушка","animal",["swims","small"],"green"),
E("turtle","🐢","toshbaqa","turtle","черепаха","animal",["swims","has_legs"],"green"),
E("snake","🐍","ilon","snake","змея","animal",["wild"],"green"),
E("crocodile","🐊","timsoh","crocodile","крокодил","animal",["wild","swims","has_legs"],"green"),
E("snail","🐌","shilliqqurt","snail","улитка","insect",["small"],"brown",6),
# ---------------- qushlar
E("bird","🐦","qush","bird","птица","bird",["flies"],"blue"),
E("owl","🦉","boyqush","owl","сова","bird",["flies","wild","forest"],"brown"),
E("eagle","🦅","burgut","eagle","орёл","bird",["flies","wild"],"brown"),
E("penguin","🐧","pingvin","penguin","пингвин","bird",["swims","cold"],"black"),
E("parrot","🦜","to‘tiqush","parrot","попугай","bird",["flies"],"green"),
E("swan","🦢","oqqush","swan","лебедь","bird",["flies","swims"],"white"),
E("peacock","🦚","tovus","peacock","павлин","bird",[],"blue",6),
# ---------------- hasharotlar
E("bee","🐝","ari","bee","пчела","insect",["flies","small"],"yellow"),
E("butterfly","🦋","kapalak","butterfly","бабочка","insect",["flies","small"],"blue"),
E("ladybug","🐞","xonqizi","ladybug","божья коровка","insect",["flies","small"],"red"),
E("ant","🐜","chumoli","ant","муравей","insect",["small"],"black"),
E("caterpillar","🐛","qurt","caterpillar","гусеница","insect",["small"],"green"),
E("spider","🕷️","o‘rgimchak","spider","паук","insect",["small"],"black",6),
# ---------------- suv hayvonlari
E("fish","🐟","baliq","fish","рыба","sea",["swims"],"blue"),
E("tropical_fish","🐠","rangli baliq","tropical fish","тропическая рыбка","sea",["swims"],"orange"),
E("whale","🐳","kit","whale","кит","sea",["swims","big"],"blue"),
E("dolphin","🐬","delfin","dolphin","дельфин","sea",["swims"],"blue"),
E("shark","🦈","akula","shark","акула","sea",["swims","big","wild"],"blue"),
E("octopus","🐙","sakkizoyoq","octopus","осьминог","sea",["swims"],"pink"),
E("crab","🦀","qisqichbaqa","crab","краб","sea",["swims","small"],"red"),
# ---------------- transport
E("car","🚗","mashina","car","машина","vehicle",["wheels","road"],"red"),
E("taxi","🚕","taksi","taxi","такси","vehicle",["wheels","road"],"yellow"),
E("bus","🚌","avtobus","bus","автобус","vehicle",["wheels","road","big"],"yellow"),
E("police_car","🚓","politsiya mashinasi","police car","полицейская машина","vehicle",["wheels","road"],"blue",6),
E("ambulance","🚑","tez yordam","ambulance","скорая помощь","vehicle",["wheels","road"],"white"),
E("fire_engine","🚒","o‘t o‘chirish mashinasi","fire engine","пожарная машина","vehicle",["wheels","road","big"],"red"),
E("truck","🚚","yuk mashinasi","truck","грузовик","vehicle",["wheels","road","big"],"blue"),
E("tractor","🚜","traktor","tractor","трактор","vehicle",["wheels","farm"],"green"),
E("bicycle","🚲","velosiped","bicycle","велосипед","vehicle",["wheels","road"],"blue"),
E("scooter","🛴","samokat","scooter","самокат","vehicle",["wheels","toy"],"blue"),
E("motorcycle","🏍️","mototsikl","motorcycle","мотоцикл","vehicle",["wheels","road"],"black",6),
E("airplane","✈️","samolyot","airplane","самолёт","vehicle",["flies","sky"],"white"),
E("helicopter","🚁","vertolyot","helicopter","вертолёт","vehicle",["flies","sky"],"blue"),
E("rocket","🚀","raketa","rocket","ракета","vehicle",["flies","sky"],"white"),
E("boat","⛵","qayiq","sailboat","лодка","vehicle",["swims","water"],"white"),
E("ship","🚢","kema","ship","корабль","vehicle",["swims","water","big"],"white"),
E("train","🚂","poyezd","train","поезд","vehicle",["wheels","rails","big"],"black"),
# ---------------- kiyim
E("tshirt","👕","futbolka","T-shirt","футболка","clothes",["body_top"],"blue"),
E("jeans","👖","shim","trousers","брюки","clothes",["body_bottom"],"blue"),
E("dress","👗","ko‘ylak","dress","платье","clothes",["body_top"],"green"),
E("coat","🧥","palto","coat","пальто","clothes",["cold"],"brown"),
E("scarf","🧣","sharf","scarf","шарф","clothes",["cold"],"red"),
E("gloves","🧤","qo‘lqop","gloves","перчатки","clothes",["cold","pair"],"green"),
E("socks","🧦","paypoq","socks","носки","clothes",["pair"],"red"),
E("cap","🧢","kepka","cap","кепка","clothes",["head","sun"],"blue"),
E("sneakers","👟","krossovka","sneakers","кроссовки","clothes",["pair","feet"],"blue"),
E("shoe","👞","tufli","shoe","туфля","clothes",["pair","feet"],"brown"),
E("boot","👢","etik","boot","сапог","clothes",["pair","feet","cold"],"brown",6),
E("hat","👒","shlyapa","hat","шляпа","clothes",["head","sun"],"yellow"),
E("glasses","👓","ko‘zoynak","glasses","очки","clothes",["head"],"black",6),
E("sunglasses","🕶️","quyosh ko‘zoynagi","sunglasses","солнечные очки","clothes",["head","sun"],"black"),
# ---------------- o'yinchoqlar
E("ball","⚽","to‘p","ball","мяч","toy",["round","sport"],"white"),
E("basketball","🏀","basketbol to‘pi","basketball","баскетбольный мяч","toy",["round","sport"],"orange"),
E("teddy","🧸","ayiqcha","teddy bear","мишка","toy",["soft"],"brown"),
E("balloon","🎈","havo shari","balloon","шарик","toy",["round","flies"],"red"),
E("gift","🎁","sovg‘a","gift","подарок","toy",[],"red"),
E("dice","🎲","o‘yin kubigi","dice","кубик","toy",["square"],"white"),
E("puzzle_piece","🧩","pazl","puzzle","пазл","toy",[],"green"),
E("kite","🪁","varrak","kite","воздушный змей","toy",["flies"],"blue",99),
E("drum","🥁","baraban","drum","барабан","toy",["music","round"],"red"),
E("guitar","🎸","gitara","guitar","гитара","toy",["music"],"orange",6),
E("robot","🤖","robot","robot","робот","toy",[],"white"),
E("car_toy","🏎️","poyga mashinasi","racing car","гоночная машина","toy",["wheels"],"red",6),
E("palette","🎨","bo‘yoq","paints","краски","toy",["school"],"brown"),
E("yarn","🧶","ip","yarn","пряжа","toy",["round"],"red",6),
# ---------------- oziq-ovqat
E("bread","🍞","non","bread","хлеб","food",[],"brown"),
E("cheese","🧀","pishloq","cheese","сыр","food",[],"yellow"),
E("egg","🥚","tuxum","egg","яйцо","food",["round"],"white"),
E("milk","🥛","sut","milk","молоко","food",["drink"],"white"),
E("honey","🍯","asal","honey","мёд","food",["sweet"],"yellow"),
E("cookie","🍪","pechenye","cookie","печенье","food",["sweet","round"],"brown"),
E("cake","🍰","tort","cake","торт","food",["sweet"],"white"),
E("candy","🍬","konfet","candy","конфета","food",["sweet"],"pink"),
E("lollipop","🍭","ledenets","lollipop","леденец","food",["sweet","round"],"pink"),
E("ice_cream","🍦","muzqaymoq","ice cream","мороженое","food",["sweet","cold"],"white"),
E("pizza","🍕","pitsa","pizza","пицца","food",[],"yellow"),
E("rice","🍚","guruch","rice","рис","food",[],"white"),
E("soup","🍲","sho‘rva","soup","суп","food",["hot"],"orange"),
E("tea","🍵","choy","tea","чай","food",["drink","hot"],"green"),
E("juice","🧃","sharbat","juice","сок","food",["drink"],"orange",99),
E("dumpling","🥟","chuchvara","dumpling","пельмень","food",[],"white"),
E("bone","🦴","suyak","bone","кость","food",[],"white"),
E("chocolate","🍫","shokolad","chocolate","шоколад","food",["sweet"],"brown"),
# ---------------- uy
E("house","🏠","uy","house","дом","home",["building"],"red"),
E("door","🚪","eshik","door","дверь","home",[],"brown"),
E("bed","🛏️","karavot","bed","кровать","home",["furniture"],"blue"),
E("chair","🪑","stul","chair","стул","home",["furniture"],"brown",99),
E("bathtub","🛁","vanna","bathtub","ванна","home",["water"],"white"),
E("key","🔑","kalit","key","ключ","home",[],"yellow"),
E("lock","🔒","qulf","lock","замок","home",[],"yellow"),
E("lamp","💡","lampochka","light bulb","лампочка","home",[],"yellow"),
E("clock","⏰","soat","clock","часы","home",["round"],"red"),
E("tv","📺","televizor","TV","телевизор","home",["square"],"black"),
E("phone","📱","telefon","phone","телефон","home",[],"black"),
E("broom","🧹","supurgi","broom","метла","home",[],"brown"),
E("basket","🧺","savat","basket","корзина","home",[],"brown"),
E("scissors","✂️","qaychi","scissors","ножницы","school",[],"red"),
E("spoon","🥄","qoshiq","spoon","ложка","home",["kitchen"],"white"),
E("cup","☕","piyola","cup","чашка","home",["kitchen","hot"],"white"),
E("umbrella","☂️","soyabon","umbrella","зонт","home",["rain"],"purple"),
E("soap","🧼","sovun","soap","мыло","home",["water"],"pink",99),
E("toothbrush","🪥","tish cho‘tkasi","toothbrush","зубная щётка","home",[],"blue",99),
E("candle","🕯️","sham","candle","свеча","home",[],"white",6),
E("hammer","🔨","bolg‘a","hammer","молоток","home",["tool"],"brown",6),
# ---------------- maktab
E("pencil","✏️","qalam","pencil","карандаш","school",["write"],"yellow"),
E("pen","🖊️","ruchka","pen","ручка","school",["write"],"blue"),
E("book","📖","kitob","book","книга","school",["read"],"blue"),
E("books","📚","kitoblar","books","книги","school",["read"],"red"),
E("backpack","🎒","ryukzak","backpack","рюкзак","school",[],"red"),
E("notebook","📓","daftar","notebook","тетрадь","school",["write"],"black"),
E("ruler","📏","chizg‘ich","ruler","линейка","school",[],"yellow"),
E("crayon","🖍️","rangli qalam","crayon","мелок","school",["write"],"red",6),
E("paper","📄","qog‘oz","paper","бумага","school",["write"],"white"),
E("school","🏫","maktab","school","школа","school",["building"],"brown"),
E("bell","🔔","qo‘ng‘iroq","bell","звонок","school",["music"],"yellow"),
E("globe","🌍","globus","globe","глобус","school",["round"],"blue",6),
# ---------------- tabiat
E("sun","☀️","quyosh","sun","солнце","nature",["sky","round","hot"],"yellow"),
E("moon","🌙","oy","moon","луна","nature",["sky","night"],"yellow"),
E("star","⭐","yulduz","star","звезда","nature",["sky","night"],"yellow"),
E("cloud","☁️","bulut","cloud","облако","nature",["sky"],"white"),
E("rain","🌧️","yomg‘ir","rain","дождь","nature",["sky","water","rain"],"blue"),
E("snowflake","❄️","qor","snow","снег","nature",["cold","water"],"blue"),
E("snowman","⛄","qor odam","snowman","снеговик","nature",["cold"],"white"),
E("rainbow","🌈","kamalak","rainbow","радуга","nature",["sky"],"red"),
E("tree","🌳","daraxt","tree","дерево","nature",["plant","forest"],"green"),
E("fir","🌲","archa","fir tree","ёлка","nature",["plant","forest","cold"],"green"),
E("cactus","🌵","kaktus","cactus","кактус","nature",["plant","desert"],"green"),
E("palm","🌴","palma","palm tree","пальма","nature",["plant","hot"],"green"),
E("flower","🌸","gul","flower","цветок","nature",["plant"],"pink"),
E("sunflower","🌻","kungaboqar","sunflower","подсолнух","nature",["plant"],"yellow"),
E("tulip","🌷","lola","tulip","тюльпан","nature",["plant"],"red"),
E("rose","🌹","atirgul","rose","роза","nature",["plant"],"red"),
E("leaf","🍁","barg","leaf","лист","nature",["plant","autumn"],"orange"),
E("seedling","🌱","nihol","sprout","росток","nature",["plant","small"],"green"),
E("mountain","⛰️","tog‘","mountain","гора","nature",["big"],"brown"),
E("wave","🌊","dengiz","sea","море","nature",["water"],"blue"),
E("fire","🔥","olov","fire","огонь","nature",["hot"],"orange"),
E("droplet","💧","tomchi","drop","капля","nature",["water"],"blue"),
E("desert","🏜️","cho‘l","desert","пустыня","nature",["hot","desert"],"yellow",6),
E("field","🌾","bug‘doy","wheat","пшеница","nature",["plant","farm"],"yellow"),
E("volcano","🌋","vulqon","volcano","вулкан","nature",["hot"],"red",6),
E("bamboo","🎋","bambuk","bamboo","бамбук","nature",["plant"],"green",6),
# ---------------- tana
E("eye","👁️","ko‘z","eye","глаз","body",["head"],None),
E("ear","👂","quloq","ear","ухо","body",["head"],None),
E("nose","👃","burun","nose","нос","body",["head"],None),
E("mouth","👄","og‘iz","mouth","рот","body",["head"],"red"),
E("tongue","👅","til","tongue","язык","body",["head"],"pink"),
E("hand","✋","qo‘l","hand","рука","body",["limb"],None),
E("foot","🦶","oyoq","foot","нога","body",["limb"],None),
E("leg","🦵","son","leg","нога","body",["limb"],None,99),
E("tooth","🦷","tish","tooth","зуб","body",["head"],"white"),
E("brain","🧠","miya","brain","мозг","body",["head"],"pink",6),
E("muscle","💪","mushak","muscle","мышца","body",["limb"],None,6),
# ---------------- oila
E("mother","👩","ona","mother","мама","family",["woman"],None),
E("father","👨","ota","father","папа","family",["man"],None),
E("girl","👧","qiz","girl","девочка","family",["child"],None),
E("boy","👦","o‘g‘il bola","boy","мальчик","family",["child"],None),
E("baby","👶","chaqaloq","baby","малыш","family",["child","small"],None),
E("grandmother","👵","buvi","grandmother","бабушка","family",["woman","old"],None),
E("grandfather","👴","bobo","grandfather","дедушка","family",["man","old"],None),
# ---------------- kasblar
E("doctor","👨‍⚕️","shifokor","doctor","врач","profession",[],None),
E("teacher","👩‍🏫","o‘qituvchi","teacher","учитель","profession",["school"],None),
E("cook","👨‍🍳","oshpaz","cook","повар","profession",["kitchen"],None),
E("farmer","👨‍🌾","dehqon","farmer","фермер","profession",["farm"],None),
E("firefighter","👨‍🚒","o‘t o‘chiruvchi","firefighter","пожарный","profession",[],None),
E("police","👮","politsiyachi","police officer","полицейский","profession",[],None),
E("pilot","👨‍✈️","uchuvchi","pilot","пилот","profession",["sky"],None),
E("builder","👷","quruvchi","builder","строитель","profession",["tool"],None),
E("artist","👨‍🎨","rassom","artist","художник","profession",[],None,6),
E("astronaut","👨‍🚀","kosmonavt","astronaut","космонавт","profession",["sky"],None,6),
]

# ================= Kengaytma (Content Phase 3): qo'shimcha rasmli tushunchalar =================
L += [
# oziq-ovqat
E("burger","🍔","burger","burger","бургер","food",[],"brown"),
E("fries","🍟","kartoshka fri","fries","картошка фри","food",[],"yellow"),
E("sandwich","🥪","buterbrod","sandwich","бутерброд","food",[],"yellow",6),
E("pancakes","🥞","quymoq","pancakes","блины","food",["sweet"],"yellow"),
E("salad","🥗","salat","salad","салат","food",[],"green"),
E("noodles","🍜","lag‘mon","noodles","лапша","food",["hot"],"orange"),
E("croissant","🥐","kruassan","croissant","круассан","food",[],"yellow",6),
E("donut","🍩","ponchik","donut","пончик","food",["sweet","round"],"pink"),
E("pie","🥧","pirog","pie","пирог","food",["sweet"],"brown"),
E("salt","🧂","tuz","salt","соль","food",[],"white"),
E("cupcake","🧁","keks","cupcake","кекс","food",["sweet"],"pink"),
E("popcorn","🍿","popkorn","popcorn","попкорн","food",[],"white"),
E("drink","🥤","ichimlik","drink","напиток","food",["drink","cold"],"red"),
E("fried_egg","🍳","quymoq tuxum","fried egg","яичница","food",["hot"],"yellow",6),
# hayvonlar
E("deer","🦌","bug‘u","deer","олень","animal",["wild","has_legs","forest"],"brown"),
E("ox","🐂","ho‘kiz","ox","бык","animal",["farm","has_legs","big"],"brown"),
E("ram","🐏","qo‘chqor","ram","баран","animal",["farm","has_legs"],"white"),
E("llama","🦙","lama","llama","лама","animal",["has_legs"],"white",6),
E("hippo","🦛","begemot","hippo","бегемот","animal",["wild","has_legs","big","swims"],"purple"),
E("bat","🦇","ko‘rshapalak","bat","летучая мышь","animal",["flies","night"],"black",6),
E("cricket","🦗","chigirtka","grasshopper","кузнечик","insect",["small"],"green"),
E("mosquito","🦟","chivin","mosquito","комар","insect",["flies","small"],"black"),
E("scorpion","🦂","chayon","scorpion","скорпион","insect",["desert"],"brown",6),
E("lizard","🦎","kaltakesak","lizard","ящерица","animal",["small"],"green"),
E("dinosaur","🦖","dinozavr","dinosaur","динозавр","animal",["big"],"green"),
E("dove","🕊️","kaptar","dove","голубь","bird",["flies"],"white"),
E("hen_chick","🐣","polapon","hatching chick","птенец","bird",["baby","small"],"yellow",6),
E("unicorn","🦄","yakshox","unicorn","единорог","animal",["has_legs"],"white",6),
# uy buyumlari
E("couch","🛋️","divan","sofa","диван","home",["furniture"],"brown"),
E("shower","🚿","dush","shower","душ","home",["water"],"blue"),
E("picture","🖼️","rasm","picture","картина","home",[],"blue"),
E("sponge","🧽","gubka","sponge","губка","home",["water"],"yellow"),
E("flashlight","🔦","fonar","flashlight","фонарик","home",[],"black"),
E("camera","📷","fotoapparat","camera","фотоаппарат","home",[],"black"),
E("computer","💻","kompyuter","computer","компьютер","home",[],"black"),
E("watch","⌚","qo‘l soati","watch","наручные часы","home",["round"],"black",6),
E("envelope","✉️","xat","letter","письмо","home",["write"],"white"),
E("box","📦","quti","box","коробка","home",["square"],"brown"),
# ---------------- ertak qahramonlari va bayram (alifbo misollari uchun: J, Q, Ю)
E("joystick","🕹️","joystik","joystick","джойстик","toy",[],"black"),
E("queen","👸","malika","queen","королева","fairy",["person"]),
E("prince","🤴","shahzoda","prince","принц","fairy",["person"]),
E("fireworks","🎆","mushakbozlik","fireworks","салют","holiday",["sky"],age=6),
E("magnet","🧲","magnit","magnet","магнит","home",[],"red",6),
E("plate","🍽️","likopcha","plate","тарелка","home",["kitchen","round"],"white"),
E("teapot_bell","🛎️","qo‘ng‘iroqcha","bell","звоночек","home",[],"yellow",6),
E("purse","👛","hamyon","purse","кошелёк","clothes",[],"pink"),
E("handbag","👜","sumka","bag","сумка","clothes",[],"brown"),
E("ring","💍","uzuk","ring","кольцо","clothes",["round"],"yellow"),
E("crown","👑","toj","crown","корона","clothes",["head"],"yellow"),
E("ribbon","🎀","bant","bow","бант","clothes",["head"],"pink"),
E("helmet","⛑️","kaska","helmet","каска","clothes",["head"],"red",6),
E("blouse","👚","kofta","blouse","кофта","clothes",["body_top"],"pink"),
# tabiat
E("lightning","⚡","chaqmoq","lightning","молния","nature",["sky"],"yellow"),
E("tornado","🌪️","bo‘ron","storm","буря","nature",["sky"],"white",6),
E("island","🏝️","orol","island","остров","nature",["water","hot"],"yellow"),
E("sunrise","🌅","tong","sunrise","рассвет","nature",["sky"],"orange",6),
E("wind","💨","shamol","wind","ветер","nature",["sky"],"white"),
E("herb","🌿","o‘t","grass","трава","nature",["plant"],"green"),
E("blossom","🌼","moychechak","daisy","ромашка","nature",["plant"],"yellow"),
E("clover","🍀","beda","clover","клевер","nature",["plant"],"green",6),
E("comet","☄️","kometa","comet","комета","nature",["sky"],"orange",6),
# transport
E("speedboat","🚤","kater","motorboat","катер","vehicle",["swims","water"],"white"),
E("metro","🚇","metro","metro","метро","vehicle",["rails"],"blue"),
E("minibus","🚐","mikroavtobus","minibus","микроавтобус","vehicle",["wheels","road"],"white",6),
E("moped","🛵","moped","moped","мопед","vehicle",["wheels","road"],"blue"),
E("traffic_light","🚦","svetofor","traffic light","светофор","vehicle",["road"],"green"),
E("tram","🚋","tramvay","tram","трамвай","vehicle",["rails"],"red",6),
E("sled","🛷","chana","sled","санки","toy",["cold"],"red"),
# o'yinchoq va maktab
E("target","🎯","nishon","target","мишень","toy",["round","sport"],"red"),
E("ping_pong","🏓","stol tennisi","table tennis","настольный теннис","toy",["sport"],"red",6),
E("skates","⛸️","konki","skates","коньки","toy",["cold","sport"],"white"),
E("trumpet","🎺","karnay","trumpet","труба","toy",["music"],"yellow"),
E("violin","🎻","skripka","violin","скрипка","toy",["music"],"brown"),
E("piano","🎹","pianino","piano","пианино","toy",["music"],"black"),
E("microphone","🎤","mikrofon","microphone","микрофон","toy",["music"],"black"),
E("headphones","🎧","quloqchin","headphones","наушники","toy",["music"],"black"),
E("paintbrush","🖌️","mo‘yqalam","paintbrush","кисточка","school",["write"],"red"),
E("calendar","📅","kalendar","calendar","календарь","school",[],"red",6),
E("telescope","🔭","teleskop","telescope","телескоп","school",["sky"],"blue",6),
E("microscope","🔬","mikroskop","microscope","микроскоп","school",[],"blue",6),
E("abacus","🧮","cho‘t","abacus","счёты","school",[],"brown"),
E("carousel","🎠","karusel","carousel","карусель","toy",[],"pink"),
E("circus","🎪","sirk","circus","цирк","toy",["building"],"red"),
E("ferris_wheel","🎡","charxpalak","ferris wheel","колесо обозрения","toy",["round"],"blue"),
E("soccer_goal","🥅","darvoza","goal","ворота","toy",["sport"],"white",6),
E("medal","🏅","medal","medal","медаль","toy",["round"],"yellow"),
E("trophy","🏆","kubok","cup","кубок","toy",[],"yellow"),
E("brick","🧱","g‘isht","brick","кирпич","home",["building"],"red"),
# oila va kasblar
E("family","👪","oila","family","семья","family",[],None),
E("programmer","👨‍💻","dasturchi","programmer","программист","profession",[],None,6),
E("mechanic","👨‍🔧","usta","mechanic","механик","profession",["tool"],None),
E("scientist","👨‍🔬","olim","scientist","учёный","profession",["school"],None,6),
E("singer","👨‍🎤","xonanda","singer","певец","profession",["music"],None),
E("worker","👨‍🏭","ishchi","worker","рабочий","profession",["tool"],None,6),
# binolar va joylar
E("hospital","🏥","kasalxona","hospital","больница","place",["building"],"white"),
E("shop","🏪","do‘kon","shop","магазин","place",["building"],"blue"),
E("castle","🏰","qasr","castle","замок","place",["building"],"white"),
E("mosque","🕌","masjid","mosque","мечеть","place",["building"],"blue"),
E("tent","⛺","chodir","tent","палатка","place",[],"green"),
E("factory","🏭","zavod","factory","завод","place",["building"],"brown",6),
E("stadium","🏟️","stadion","stadium","стадион","place",["building","sport"],"green",6),
E("bridge","🌉","ko‘prik","bridge","мост","place",["water"],"blue"),
E("yard_house","🏡","hovli","house with garden","дом с садом","place",["building"],"green"),
E("bank","🏦","bank","bank","банк","place",["building"],"white",6),
]

COLORS = [
 ("red","#E53935","qizil","red","красный"),
 ("yellow","#FDD835","sariq","yellow","жёлтый"),
 ("green","#43A047","yashil","green","зелёный"),
 ("blue","#1E88E5","ko‘k","blue","синий"),
 ("orange","#FB8C00","to‘q sariq","orange","оранжевый"),
 ("purple","#8E24AA","binafsha","purple","фиолетовый"),
 ("pink","#EC407A","pushti","pink","розовый"),
 ("brown","#795548","jigarrang","brown","коричневый"),
 ("black","#212121","qora","black","чёрный"),
 ("white","#FAFAFA","oq","white","белый"),
]
SHAPES = [
 ("circle","doira","circle","круг",0),
 ("square","kvadrat","square","квадрат",4),
 ("triangle","uchburchak","triangle","треугольник",3),
 ("rectangle","to‘rtburchak","rectangle","прямоугольник",4),
 ("oval","oval","oval","овал",0),
 ("star","yulduzcha","star","звёздочка",10),
 ("heart","yurakcha","heart","сердечко",0),
 ("rhombus","romb","rhombus","ромб",4),
]
# 99 = Android 9 da ko'rinmasligi mumkin — kontentda ishlatilmaydi (keyingi versiyalar uchun zaxira).
out = {
  "schemaVersion": 1,
  "note": "Original uch tilli lug'at. Emoji'lar Android 9+ da ko'rinadiganlaridan tanlangan; ageMin=99 bo'lganlar ishlatilmaydi.",
  "colors": [ {"id":c,"hex":h,"uz":uz,"en":en,"ru":ru} for c,h,uz,en,ru in COLORS ],
  "shapes": [ {"id":s,"uz":uz,"en":en,"ru":ru,"corners":k} for s,uz,en,ru,k in SHAPES ],
  "entries": L,
}
ids = [e["id"] for e in L]
assert len(ids) == len(set(ids)), "duplicate id"
path = os.path.join(os.path.dirname(__file__), "..", "..", "assets", "data", "lexicon.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print(len(L), "entries")
